giantswarm/happa

src/components/organizations/detail.js, src/components/users/index.js, src/components/users/user_row.js
The rationale here is to improve the "scannability" of the user tables and make it visible which domains (in many cases equalling companies) a user comes from. Check for example https://happa.g8s.gollum.westeurope.azure.gigantic.io/users/ for an installation with many users.
In a next step, these tables could be made sortable. Then having this column would allow to sort by email domain.
One thing I am unsure of: Would it be better to truncate the content of the `Email` column to the first part only? Like this:
| Email | Email Domain
|------|------|
| foo@ | example.com |
| bar@ | example.com |
This kind of defaces the email address as such.
=> Add mail domain column to user lists

src/components/signup/index.js, src/styles/components/_progress_button.sass, src/styles/components/_signup.sass
There appears to have been a regression in the sign up form. When reaching the final step, where the TOS has to be checked,
the button would appear green instead of disabled.
Clicking on the green button without checking the TOS would put the user in a invalid state.
This ensures the form does not go 'green' when reaching the final step.
=> Fix valid signup form despite TOS being unchecked.

src/components/organizations/detail.js
The label for an empty org said `This organization has no members, which shouldn't really be possible`.
This is quite possible, especially now with SSO.
=> Fix label regarding no org members

src/lib/helpers.js
It was off for me since it was parsing the timestamp in the local timezone as well.
=> Fix relative time text

src/actions/userActions.js, src/lib/giantswarm_v4_client_wrapper.js, src/reducers/appReducer.js
Originally we relied on a `401` response from the server as the 'trigger' to attempt a token refresh.
This can be handled in a smarter way, we know when the token is expired, so we can simply do a reauth before using the token.
Fixes: https://github.com/giantswarm/giantswarm/issues/4292
Fixes: https://github.com/giantswarm/happa/issues/364
=> Refresh a SSO token before using it if it's expired.

src/components/create_cluster/index.js, src/components/create_cluster/number_picker.js, src/components/create_cluster/provider_credentials.js
For https://github.com/giantswarm/giantswarm/issues/3987
This adds a line of info in the cluster creation page when the owner org has BYOC credentials set.
This should reassure BYOC users when creating a cluster.
If there are no specific credentials set for the org, the entire line does not appear.
=> Expose BYOC info in cluster creation

src/components/auth/oauth_callback.js, src/components/organizations/cluster_detail.js
I came accros some uses of `componentWillMount`, which is to be deprecated in React 16.3. See https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#initializing-state
This is so far only tested locally. Needs testing in SSO/OAuth context.
This also uses the most simple way to initialize the component state.
=> Remove componentWillMount

src/components/organizations/expiry_hours_picker.js, src/styles/components/_cluster_details.sass, src/styles/components/_create_key_pair.sass, src/styles/components/_expiry_hours_picker.sass
The main change here is the removal of the dynamic behaviour of the relative time labels. This was causing the layout to change during input.
In addition, inputs field are a bit narrower, and labels are lower case (which works better for me as this is practically a sentence) plus some more adjustments.
Preview
=> Key-pair creation dialog: make labels static, adjust layout

src/components/organizations/cluster_key_pairs.js, src/styles/components/_table.sass
The key pairs table with the static truncation didn't really use the available space for the best usability.
This PR makes the truncation dynamic, to let the table use the entire column width. In addition, some columns are hidden entirely in smaller viewports, to be able to render a recognizable table as such.
=> Dynamic truncation for the key pairs table

src/components/organizations/cluster_detail.js, src/components/organizations/cluster_key_pairs.js
Without the change the last two boxes appear to be wider then the others. 
With the change the alignment is fixed. Note that the padding on the right side is off regardless. I do not intend to fix this here.
=> aligns div widths in cluster details view

src/components/layout.js
This will give people some feedback if happa encounters an error while starting up.
If the API returns a 500 error, or is simply not reachable, a flash message will appear above the spinner.
If the API returns a 401 error, Happa will redirect to the login page and show an error message asking the user to log in again.
=> Give user some feedback if startup requests fail, and why.

src/components/create_cluster/index.js, src/components/create_cluster/new_azure_worker.js, src/styles/components/_create_cluster.sass
This adds a description column to the Azure VM size selection dialog
Only confirming that the CSS still works for AWS
=> Add azure vm size descriptions

src/components/auth/admin.js, src/lib/giantswarm_v4_client_wrapper.js, src/lib/helpers.js
This makes the `/admin-login` page a bit smarter. If credentials already exist, it attempts to use them. And otherwise it will redirect to auth0 as before.
=> Faster admin login

src/components/home/bar_chart.js, src/components/shared/input_field.js, src/components/signup/index.js
Setting eslint to the right React version yields complaints about us using `componentWillReceiveProps`, which is deprecated since 16.3.0.
Details: https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops
This replaces the former usage of `componentWillReceiveProps` in the following components:
- `InputField`, used in cluster creation to set worker machine/instance type, for both Azure and AWS.
- `SignUp`, which is the signup form.
- `BarChart` which is not in use.
=> Remove use of deprecated componentWillReceiveProps

.circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/4874
This adds a step `Lighthouse audits` to CI with this result:
```
RESULTS FOR URL https://testcontainer:8000/
-----------------------------
SELECTED AUDITS
first-contentful-paint: 4651.8055
first-meaningful-paint: 4801.8055
speed-index: 4651.8055
interactive: 4952.027
first-cpu-idle: 4801.8055
estimated-input-latency: 34.800000000000004
render-blocking-resources: 1005
uses-responsive-images: 0
unminified-css: 0
unminified-javascript: 0
unused-css-rules: 0
uses-optimized-images: 0
total-byte-weight: 529967
dom-size: 54
-----------------------------
SCORING
accessibility: 0.58
best-practices: 0.93
performance: 0.64
pwa: 0.44
seo: 0.6
```
The output currently depends on https://github.com/giantswarm/lighthouse/blob/3074344773ec009b1e …
=> Add lighthouse audits to CI

src/styles/components/_form.sass, src/styles/components/_number_picker.sass
Towards https://github.com/giantswarm/giantswarm/pull/2206. Note that this PR is based on [`feature-auto-scaling`](https://github.com/giantswarm/happa/pull/424). I noticed the number picker's input field is not aligned in height and the padding was confused with other input fields. Also the border outline on focus was wrong. I couldn't make the on focus border really useful so I took the shortcut and dropped it completely. Below are screenshots of before and after.
=> improves number picker style

Dockerfile
This closes some security vulnerabilities by upgrading from NGINX 1.13 to 1.14.
=> Upgrade nginx to 1.14

Makefile, docker-compose.yml
When running tools / dev env within container and running SELinux or
similar at the same time, one must allow Docker to relabel files in
order to maintain expected behavior. Since there might be dev env
running while running e.g. prettifier, z is used instead of Z.
=> Relabel bind mounts (docker volumes)

src/components/create_cluster/index.js, src/components/create_cluster/node_count_selector.js
NodeCountSelector provides number picker[s] and related labels for node
count selection and appropriate logic to provide either single node
count or min/max values for scaling limits.
This is also now wired for cluster creation view and there is a function
that decides based on provider and release version whether cluster
supports automatic scaling limits or just a static node count.
**NOTE:** This is just a change for cluster creation. I still need to do changes for existing cluster details page & scaling view.
**NOTE2:** Please, have a critical eagle eye on reasonability / code style of this change. :smile: 
Towards https://github.com/giantswarm/giantswarm/pull/2206
=> Add NodeCountSelector component for cluster creation

src/components/create_cluster/index.js
Set default values from the info endpoint.
For KVM,  we don't have default values for cpu, memory and storage from the api info endpoint, so setting them to what they always were in Happa.
=> Set default values

src/components/users/index.js
This PR adds some clientside validation to help us remember that only giantswarm.io emails may be invited to the giantswarm organization.
Related to: https://github.com/giantswarm/giantswarm/issues/4296
=> Only allow giantswarm.io emails to be invited to the giantswarm org.

src/components/cluster_detail/index.js, src/components/cluster_detail/scale_cluster_modal.js, src/components/cluster_detail/upgrade_cluster_modal.js, src/components/home/cluster_dashboard_item.js, src/styles/components/_cluster_dashboard.sass, src/styles/components/_create_cluster.sass, src/styles/vendor/_simple-grid.scss
I fixed a couple things as I was clicking around in Happa:
- There are some unused props in the modals of the cluster detail screen.
- The screen doesn't line up correctly with the menu on the right side on some screens, like the cluster detail screen.
- The create workers screen was not aligning well, as the min height for those elements was getting superseded by a css declaration with higher specificity from the simple-grid 'framework'
=> Refactor and fix style issues.

src/components/layout.js, src/lib/giantswarm_v4_client_wrapper.js
When you have a bearer token, but you are not able to refresh it at auth0, happa would end up in a 'soft locked' state, showing just the "Something went wrong loading organizations" error message.
This is because the error from auth0 was not bubbling up correctly to the layout component which handles login error issues.
=> Fix auth0 login error edge case.

src/components/home/cluster_dashboard_item.js
Worker array doesn't contain entry for each node any more. Instead one should
use node entries found from cluster status.
=> Fix number of nodes in home view

src/reducers/clusterReducer.js
Noticed this while testing some of the auto scaling branches. This guards against a race condition where scaling is not present yet (or empty) and thus omitted from the API response. Happa still tries to reach into it (`cluster.scaling.min`), which raises errors when `scaling` is null.
=> Guards against an edge case where scaling is not present yet.

src/components/cluster_detail/cluster_detail_table.js, src/components/home/cluster_dashboard_item.js
Initially I thought there is role=worker label for worker nodes just like there
is role=master label for master nodes. In earlier PRs I got noted that there
isn't such label (even though I checked this before creating this
implementation).
It turns out that by default k8s doesn't assign worker nodes the role label and
therefore it is actually missing in our tenant clusters. On control plane we
set this label manually as part of a node configuration so that's how I saw it
there.
I changed the code to count all nodes except masters as workers.
=> Fix worker node counting

src/styles/components/_cluster_apps.sass
Fixing what @xh3b4sd noticed. Not all the icons were correctly rounded.
Instead of fixing the actual image file, I apply a consistent border to all icons using css.
Result:
=> Add border-radius to all images.

src/components/cluster_detail/index.js
ClusterApps fails if for some reason we do not have release information for the cluster.
This is a rare edge case, but worth to guard against.
=> Don't show cluster apps when we don't have any release information.

src/components/cluster_detail/cluster_detail_table.js, src/components/home/cluster_dashboard_item.js
When number of nodes changes, calculate total amount of CPU cores, RAM and
storage space by number of running nodes, not by scaling limits.
=> Calculate total CPUs/RAM/Storage by running nodes

src/components/cluster_detail/cluster_detail_table.js, src/components/home/cluster_dashboard_item.js
When extracting number of CPU cores, amount of RAM or storage space, check for
zero workers before performing actual calculation.
This fixes inconsistence in cluster details when cluster is being created and
there are no nodes running yet.
=> Check for zero workers when extracting worker instance details

src/components/cluster_detail/scale_cluster_modal.js
Due to way how non-auto-scaling clusters adjust number of worker nodes,
auto-scaling changes broke function that calculates differences between
existing number of workers and desired scaling value.
Fix this calculation for non-auto-scaling clusters by simply comparing minimum
number of nodes.
=> Resume Scale button for non-auto-scaling clusters

src/components/cluster_detail/cluster_detail_table.js, src/components/home/cluster_dashboard_item.js
When there are no nodes running yet during cluster creation, display 0 instead
of n/a for CPUs, RAM and storage.
=> When nodes are not running yet, display 0 for resources

src/components/getting-started/1_download_kubectl.js
The kubectl version referenced  in current Happa download links is outdated.
This PR updates links to 1.11. version, which matches the latest Kubernetes version available through happa.
=> Bump kubectl download links to 1.11.7 (from 1.7.5)

src/reducers/clusterReducer.js
This fixes a scaling issue for certain older clusters.
=> Fix problem with scaling modal when min/max values aren't supplied by API.

package.json
This updates bootsrap from 3.4.0, which has a security vulnerability, to 3.4.1.
=> Upgrade bootstrap to 3.4.1

src/components/create_cluster/aws_instance_type_selector.js, src/components/create_cluster/vm_size_selector.js
For https://github.com/giantswarm/giantswarm/issues/5305
This makes use of the sorting of the allowed instance types/VM sizes array to sort the selection table.
=> Use sorting of allowed instances array

src/components/cluster_detail/key_pairs.js, src/components/home/index.js, src/components/organizations/detail.js, src/components/organizations/index.js, src/components/users/index.js, src/styles/components/_button.sass
Related to https://github.com/giantswarm/giantswarm/issues/5410
This adds a + icon to all create/add buttons I could find.
FYI: The `Set Credentials` button doesn't get the icon. I feel that's not right, as it's not about adding potentially multiple things. User can either set them or not set them.
=> Add plus icon to Create/Add buttons

src/components/cluster_detail/cluster_detail_table.js, src/components/home/cluster_dashboard_item.js
For https://github.com/giantswarm/giantswarm/issues/5410
Changes
- Remove organization name from cluster details in list
- Remove bold formatting of data vs. label
- Replace `Release version` with icon
- Re-order info
=> Add version tag icon, restructure cluster overview info

src/components/cluster_detail/index.js
and as it's not visible in the screenshot:
=> Add icons to buttons on cluster details page

.circleci/config.yml, Dockerfile, README.md, docs/Release.md, package.json, scripts/start.sh, src/index.html, src/styles/_base.sass
This adds a little footer to Happa with links to the github releases page.
As for the actual release process, I'm thinking something like:
1. Bump the version in package.json
1. git commit -m "Release ${VERSION}"
1. git tag -a ${VERSION}
1. git push
1. CI takes over and makes the release draft
And we change our CI to only continuously deploy tags. Master can still be continuously deployed to our own Giant Swarm installations though.
=> Add a footer with version number. Adjust release process.

src/components/create_cluster/release_selector.js, src/components/home/cluster_dashboard_item.js
Don't show `kubernetes n/a` on the cluster overview screen for all clusters.
We deprecated the `kubernetes_version` field, so there will never be anything in it.
I have some refactoring in mind for moving the setting of various information that components might want to display or act on further up to the actions. Allowing components to do less work to get the data they need. Part of that could be extracting the kubernetes version from the release information of a cluster and adding it to the cluster object so that Happa can display it easily in a place like this.
That's a bit of a refactoring in though, so for now I'd like to remove this `n/a` as it might be confusing for users.
=> Fix kubernetes n/a

src/components/home/cluster_dashboard_item.js
For https://github.com/giantswarm/giantswarm/issues/5410
This removes the details button, which is a redundancy to the linked cluster name
=> Remove details button

src/components/organizations/detail.js
This adds a release column to the clusters table in the organization details page.
=> Add release column to clusters table

src/components/shared/input_field.js, src/styles/components/_form.sass
This PR fixes the problem that the AWS EC2 instance type input field and the Azure VM size input field did not carry a `type=text` HTML attribute.
As a consequence, they were rendered like this:
=> Expose the InputField type property as HTML attribute

src/reducers/appReducer.js
I noticed the "Users" link in the navigation would sometimes appear and disappear. 
This is because on re-acquiring the auth token, we'd overwrite the user object instead of merge the existing user object with the new user data. The user object contained information about whether or not the user was an admin, which is determined when happa loads the list of organisations. 
This commit ensures that information is retained when a refreshed token is acquired. 
(Only relevant for giant swarm 'admins' that can see the global user list to begin with)
=> Fix 'Users' disappearing in nav after token refresh.

src/styles/components/_number_picker.sass
Fixes https://github.com/giantswarm/giantswarm/issues/5469
In Firefox, with the number picker being disabled, the input field would contain two tiny increment/decrement buttons.
This PR hides the buttons and aligns he appearance with Chrome.
=> Remove increment/decrement buttons for disabled input

src/components/home/cluster_dashboard_item.js
For https://github.com/giantswarm/giantswarm/issues/5410
This hides the `Get Started` button in the cluster overview if the cluster is older than 30 days.
Preview
=> Add age condition for showing Get Started button

src/components/cluster/detail/cluster_detail_table.js, src/components/cluster/detail/view.js, src/components/shared/refreshable_label.js, src/reducers/clusterReducer.js, src/styles/components/_cluster_details.sass
For https://github.com/giantswarm/giantswarm/issues/5556
This lets the cluster details refresh automatically. A note is added showing that this is a new feature and when the information has been last refreshed.
- Loading of freshest data is done via `window.setInterval` every 30 seconds.
- the view component refreshes every 10 seconds, to update relative date strings like `a few seconds ago.`
- When the [page visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) indicates that the tab is invisible, the refresh interval function is unregistered. When the page is revealed again the freshest data gets pulled immediately and the interval function is registered again.
- The current implementation doesn't simplify any re-use of the refresh mechanism in other …
=> Auto-refresh for cluster details 

src/actions/clusterActions.js, src/components/cluster/new/view.js
Fixes https://github.com/giantswarm/giantswarm/issues/5555
So far, after cluster creation, the organization details page is shown. This changes this to show the cluster details page instead.
=> After cluster creation, redirect to cluster details page

src/actions/clusterActions.js
Fixes https://github.com/giantswarm/giantswarm/issues/5596
Ensures that the clusters list is updated after deleting a cluster
=> Refresh clusters list after deletion

src/components/cluster/detail/view.js, src/components/shared/cluster_name.js, src/styles/components/_form.sass
Towards https://github.com/giantswarm/giantswarm/issues/2046
This PR makes the cluster name editable from the cluster details page.
- Affects the cluster details page only
- Hovering the cluster name will change the style and reveal a tooltip `Click to edit name`
- A click reveals a form in place with an OK and edit button
- Form submission is possible by hitting Enter/Return or clicking the OK button
- Cancelling is possible via the ESC key and by clicking Cancel
- If the submission fails, an error will appear and the form will remain in edit mode
- In case of a successful change, a flash message appears (not visible in the preview below)
Depends on https://github.com/giantswarm/cluster-service/pull/369
Caveats
- On narrow viewports, the form may break into several lines.
=> Make cluster name editable

src/components/cluster/detail/cluster_detail_table.js, src/components/cluster/detail/view.js, src/components/home/cluster_dashboard_item.js, src/components/home/index.js, src/lib/page_visibility_tracker.js, src/styles/_base.sass, src/styles/app.sass, src/styles/components/_cluster_dashboard.sass, src/styles/components/_cluster_details.sass, src/styles/components/_refreshable_label.sass
Towards https://github.com/giantswarm/giantswarm/issues/5446
This automatically refreshes the clusters list on the home screen. New data is loaded once every 30 seconds.
This includes some refactoring to make page visibility tracking re-usable.
Preview needs some patience, as the animation is a minutes long. Use [this link](http://recordit.co/myotVpsRZh) to scrub and fast-forward.
=> Auto-refresh cluster list on home screen

src/actions/clusterActions.js, src/reducers/clusterReducer.js
Fixes https://github.com/giantswarm/giantswarm/issues/5671 mostly
This seems to improve the situation.
Improvable: When values get first loaded, items highlight once, which they shouldn't ideally. But that's not the point of the fix.
Another thing I noticed, but couldn't explain when it happened:
Probably passed a bad value to `moment()`.
=> Merge clusters into state to avoid flapping of cluster info

src/reducers/clusterReducer.js
Clusters were showing up twice in the organization list.
This is because of a mistake in the recently introduced merging code.
In the `clusters load success`  reducer, we were merging `action.clusters` which is an array of clusters into the `entites.items` object, which is supposed to be a dictionary of cluster id's to cluster objects:
`items = Object.assign({}, state.items, action.clusters);`
=> Fix cluster duplicates.

src/components/cluster/detail/key_pairs.js
the function looks unused to me.
got added some years ago with this commit
https://github.com/giantswarm/happa/commit/12a460b2a84833b427f37ee0c5831b5de362e972
=> remove unused function

src/components/cluster/detail/key_pairs.js, src/components/shared/copyable.js, src/styles/app.sass, src/styles/components/_copyable.sass
This introduces a wrapper component called 'Copyable' and applies it to some elements in the keypair table.
It is a helper to allow us to make certain pieces of text quickly copyable to the clipboard.
See the behaviour in this gif:
As you can see, you can click anywhere on the element, not just on the copyable indicator icon that appears on hover.
I made a change to the keypair table as well, combining the description and ID field in one column to allow for a bit more breathing room, and made most elements `small`er
Related: https://github.com/giantswarm/giantswarm/issues/2903
=> Make parts of the keypair table copyable.

helm/happa-chart/templates/certs-secret.yaml, helm/happa-chart/templates/configmap.yaml, helm/happa-chart/templates/nginx-config.yaml, helm/happa-chart/templates/pull-secret.yml
A bit random, just something I noticed.
I feel like the `app` label has no purpose unless all resources belonging to happa have it set.
This lets us do `kubectl get -l app=happa all` and see all the things related to Happa.
=> Add the app=happa label to all resources.

src/components/app.js
I noticed this while working on the app catalog, but it is also present in `master`. 
The scroll position is not reset to the top of the page when navigating. This is only matters if you navigate between two pages that actually have some content to scroll for like when moving between the pages of the getting started guide for example.
It's a bit weird, because I never noticed this before, so at first I thought this is a regression in a library somewhere.. but I checked and it happens still all the way to our first tagged release (0.1.31)
=> Reset scroll position when navigating.

src/styles/_base.sass, src/styles/components/_nav.sass
This helps happa resize between its breakpoints in a smoother way.
This stops the effective viewport from getting smaller than it needs to before snapping into the 'medium' breakpoint.
=> Improve responsiveness.

src/components/cluster/detail/scale_cluster_modal.js
This changes the title of the scaling modal to `Edit scaling settings for <id>` to better match the situation we have since the introduction of autoscaling.
The cluster name is removed, since we are in the context of that cluster anyway and the name does not fit in some situations.
=> Change scaling modal title, remove cluster name

src/components/cluster/detail/certificate_orgs_label.js, src/components/cluster/detail/key_pairs.js, src/styles/components/_cluster_details.sass
- Splits multiple orgs, sorts them
- Highlights the cluster-admin org name `system:masters` (but not `systems:master` ;-))
=> Improve rendering of certificate orgs in key pairs table

src/components/cluster/detail/scale_cluster_modal.js, src/components/cluster/new/view.js, src/components/shared/node_count_selector.js
This removes the `Node Count` column from the `NodeCountSelector` component, as it should not appear in the scaling modal.
In the case of manual scaling, the extra `Number of nodes` label above the number picker is removed.
=> Fix node count selector, clean up scaling modal

scripts/start.sh, src/components/cluster/new/aws_instance_type_selector.js, src/index.html
Instead of having these devInstanceTypes in the source code, I move it to the dev configuration. This lets us avoid repeating checking wether or not instance types set and substituting in the dev values.
(Currently the cluster detail table is broken in dev, and this fixes it.)
Why I didn't do this in the first place? Not sure. I probably didn't think of the `.*` for the replacement in `start.sh`
=> Move dev instance types into dev cofiguration.

src/components/cluster/detail/certificate_orgs_label.js, src/components/cluster/detail/cluster_detail_table.js, src/components/cluster/detail/scale_cluster_modal.js, src/components/cluster/detail/view.js, src/components/shared/node_count_selector.js, src/styles/transitions/_slide.sass
Our warnings regarding scaling down needed improvements in several ways.
- Scenario: changing form pinned to 3 to min2/max3. The warnings indicated that worker nodes would be removed, which would in fact only happen if the autoscaler decides so. Accordingly, the submit button showed `Remove 1 node` when in fact only the scaling limits would be changed.
- We were lacking the info that a cluster with less than 3 nodes is not supported.
- We were showing some info regarding possible data loss that can be taken as general
This PR brings changes:
- Changed the logic regarding which warning appears in what situation, so that only warnings appear which apply to the situation
- change design of warnings, to prevent it from looking like an error message
- Simplify submit button working to make it …
=> Improve scaling dialog warnings

src/components/cluster/new/azure_vm_size_selector.js, src/index.html
This moves the azure dev vm sizes into configuration instead of source code as well, like was done in pr #555 for aws instance types.
=> Move azure dev vm sizes into config as well.

src/actions/organizationActions.js, src/lib/flash_message.js
reported by @jgsqware , we were using the `ERROR` type of flash message for a successful member adding.
Also noticed that only the first `<code> </code>` tag is whitelisted properly in our escapeHTML function. Fixed that as well.
=> Fix member add notification

src/styles/components/_cluster_details.sass, src/styles/components/_users_table.sass
This allows the fields grow/shrink in size, which was probably the case before, but once I added the bootstrap-table styles in https://github.com/giantswarm/happa/pull/542#issuecomment-478230923, `table-layout: fixed` came with it.
Before:
After:
=> Adjust table layout for users and keypairs

src/components/cluster/detail/tabs.js, src/components/cluster/detail/tabs.test.js, src/components/cluster/detail/view.js
I made a mistake and committed this, which I had set to `2` to more quickly test some changes I was making to the keypair table.
I'm gonna try to write a test so I don't make that same mistake again.
=> Don't show tab 2 as the first tab.

Dockerfile.dev, src/components/cluster/detail/certificate_orgs_label.js, src/components/cluster/detail/certificate_orgs_label.test.js, src/components/cluster/detail/key_pair_details_modal.js, src/components/cluster/detail/key_pairs.js, src/components/modals/generic_modal.js, src/styles/components/_cluster_details.sass, yarn.lock
This changes the key pairs table, based on user feedback, to contain the most important info only, but in more readable fashion.
- Removed ID and description from table, to appear in a details modal, added a Details button to open the modal
- Column order. Put CN in front, as it is perceived as the identifier users care about.
- Removing common suffix (cluster API domain) from CNs in the table.
- Show full group information instead of truncated.
- Color hashing on group names
=> Reduce key pairs table info, show details in modal

src/actions/userActions.js, src/reducers/appReducer.js
Theres a problem creating orgs as an admin when the cluster has no orgs yet.
As an admin, happa has to create the org without trying to add you to it at the same time. 
And, it already has code that does that. However, the way it knows you are an admin is if you are in the giantswarm org, which doesn’t exist yet.
This adjusts Happa's logic so that it determines whether or not you are an admin from a claim in the JWT token. This claim is only given to us admins. (And so far only us admins can even use SSO, but anyways this is better than simply granting `isAdmin` to all auth0 logins, since in the future we might have other users also making use of the SSO login route)
BTW, this has nothing to do with being an 'admin' on the API. In other words, if someone were to edit their localstorage …
=> Fix initial org create

src/actions/catalogActions.js, src/components/app_catalog/catalogs/index.js
This is a lil workaround while we do not cache and serve the index.yamls ourself.
fyi @puja108
=> Attempt fetching an index.yaml using cors anywhere if it fails.

package.json, src/components/cluster/new/cluster_creation_duration.js, src/components/cluster/new/view.js, yarn.lock
Towards https://github.com/giantswarm/giantswarm/issues/6005
This adds some info regarding the actual cluster creation duration to the creation page. The info is coming from the statistics provided via the API's info endpoint.
=> Show duration statistics on cluster creation page

src/components/cluster/detail/view.js
This PR removes the following notice:
=> Remove notice regarding moved content

README.md
This adds the badge
[![Known Vulnerabilities](https://snyk.io/test/github/giantswarm/happa/badge.svg?targetFile=package.json)](https://snyk.io/test/github/giantswarm/happa?targetFile=package.json)
to the README
=> Add Snyk vulnerabilities badge

.eslintrc
I have changed no-unused-vars error level from error to warning because when debugging I like to comment some parts of the code.
I also have sorted rules and favoured numbers instead of strings when defining levels of error.
=> .eslintrc minor mods

.eslintrc, package.json, yarn.lock
To merged into #600 
Adds checks regarding eslint (no CSS syntax checks though)
`emotion/syntax-preference` is about the string syntax being preferred and yields a warning of object syntax is used.
The other rules are checking imports.
=> Add eslint emotion plugin

src/components/cluster/detail/upgrade_cluster_modal.js
Towards https://github.com/giantswarm/giantswarm/issues/6400
This removes the list of unchanged components in the upgrade dialog, as it doesn't contain any information that is of value in this context.
=> Remove unchanged components list from upgrade dialog

src/components/UI/availability_zones_label.js
This turns an oval into a circle.
=> Adjust width of availability zone label (minor)

package.json, src/components/UI/component_changelog.js, src/components/UI/style_guide.js, src/components/cluster/detail/upgrade_cluster_modal.js, src/components/modals/release_details_modal.js, yarn.lock
Towards https://github.com/giantswarm/giantswarm/issues/6400
Goal of this PR is to group component changes in the release and upgrade dialog in a hierarchical way, with the component name as a sub-header and the changes in a list grouped together by component.
It introduces a new component which represents an items in a `<dl>` list. I wonder whether this is counterintuitive and whether there should be a component representing the entire list.
The component supports **Markdown** content, even multi paragraph, to allow for more advanced changelog entries.
Example in dialog context, not using Markdown
Markdown example from styleguide
=> Group release changelog by component, add capabilities for longer and MD-formatted changelog entries

src/actions/catalogActions.js, src/components/app_catalog/app_list/index.js, src/components/app_catalog/catalogs/index.js, src/components/app_catalog/index.js, src/styles/components/_app_catalog.sass
This shows all the app catalogs and allows people to visit app catalogs that have loaded before other ones, instead of blocking the whole feature while all app catalogs load.
=> Load app catalogs individually

src/actions/clusterActions.js, src/components/app_catalog/detail/cluster_picker.js, src/components/app_catalog/detail/install_app_modal.js, src/components/cluster/detail/view.js
This ensures we don't show app installation related features for clusters that don't support it.
=> Version constraint for app installation features

src/actions/clusterActions.js
When creating a cluster, a new cluster is added to the state without loading all clusters.
I was only computing the capabilities on the clusters load action, and not on the singular cluster load details action.
=> Also compute capabilities on cluster load details.

package.json
I have added the node pools branch of the JS client library, so I can use it for development.
@marians we talk about about creating a `node-pools` branch in Happa to issue all Node Pools related PRs against it. But this way we will have a long-lived branch and when we will want to merge it with `master` probably we will have a bunch of conflicts, so maybe it would be a better approach to commit Node Pools PRs directly to `master`. 
My two open PRs go in this direction. WDYT?
=> Two GS JS client libraries: master and node pools

src/reducers/clusterReducer.js
Minor refactor: I saw that inside every `case` we were overwriting state. I decided to refactor in a way that the state is modified, but never overwritten.
I also had simplified this:
`{ items: items }`
To this:
`{ items }`
But no real change here, it is the exact same thing with ES6 syntax.
Also I have removed state `isFetching: false` from returns because I haven't found a single `isFetching: true`, then we can remove them safely (?). I am wondering if we really need this property here...
If you are ok with this I will do the same in the other reducers
=> Cluster reducer with spread operator

src/components/UI/__tests__/catalog_type_label.js, src/components/UI/catalog_type_label.js, src/components/app_catalog/catalogs/index.js, src/styles/components/_app_catalog.sass
This adds a label to the catalog listing, which on hover, gives a bit of expectation management for the `incubator`, `test` and `community` catalog types.
The `test` type of catalog should by the way never appear on customer installations, but I decided to cover that case anyways.
I will also add a warning on app installation when someone is about to install a community app, but that will be in a different PR.
=> Add a label that does some expectation management depending on the catalog type.

src/components/UI/catalog_type_label.js, src/styles/components/_app_catalog.sass
I noticed I had messed up the font size. This sets it back to what it was, and adjust the space between the catalog type label and the text a bit.
=> Some small style adjustments to app catalog index

src/components/home/cluster_dashboard_item.js, src/components/home/index.js
Here I am computing the value for RAM (and CPUs) doing the following: RAM amount * number of NPs of the cluster * number of nodes that each NP has.
Is that correct @marians ?
And I am using the `nodePools` array in store instead of `window.config.environment` and cluster id
=> Added CPU and RAM to list items

src/components/cluster/detail/cluster_detail_table.js, src/components/cluster/detail/cluster_detail_view.js, src/components/cluster/detail/index.js, src/components/home/cluster_dashboard_item.js, src/utils/cluster_utils.js
What I am doing here in this PR is:
- Extracting functions duplicated in `ClusterDetailView`, `ClusterDashboardItem`,  `ClusterDetailTable` components (some of them will be  also in `ClusterDetailNodePoolsTable`) to a utils file
- Desctucturing props
- Renaming `view.js` to `cluster_detail_view.js` because it is easier, at least for me, to use (almost) same names for the exported component and the file. 
Sorry for the size of the PR... it is not as big if you take into account that there is a lot of destructuring. Let me know if you think that I should have done destructuring in another PR. Thanks ❤️
=> Refactor: shared functions in cluster view and list

src/components/UI/view_edit_name.js
This has been updated too many times lately, sorry
This fix an error that is thrown when `this.props.toggleEditingState`is not supplied
=> Fix error when no togglingState method is supplied

Dockerfile.dev, README.md, docker-compose.yml, scripts/dev.sh, webpack.dev.js
Things have changed a bit since we wrote the getting started part of the README.
This updates that.
It also removes passage and mailcatcher from the dockerfile, I will move it to the dockerfile in api instead, so we don't have to think about starting another docker-compose before testing anything related to invitations. 
FYI @ograu. I gave you some instructions on how to start `passage`, but now I am removing that from `happa`. So what I said here will no longer work after this PR is merged. Instead I will add it to the docker-compose in `api` so that it is always running, and invitations are always working.
https://github.com/giantswarm/happa/pull/712#issuecomment-521104734
=> Update getting started

src/components/app.js, src/index.html
This makes the initial load of Happa more calm.
The footer content won't show up on a blank page anymore, and the page should start off blue.
I've also fixed a unreadable portion of the warning that shows up when users do not have javascript enabled. The `strong` tag rendered the text in white.
=> Remove some flashing of unstyled content.

src/reducers/nodePoolsReducer.js
Added `return`s because I have observed that, even though in Immer docs they say `return`s are not needed (or at least this is what I understood [here](https://github.com/immerjs/immer#returning-data-from-producers)) in one specific case a fallthrought occurred.
=> Added returns & removed export

src/actions/clusterActions.js, src/components/UI/view_edit_name.js, src/components/cluster/detail/upgrade_cluster_modal.js
There were some problems after the recent changes to clusterpatch.
ClusterPatch is used for two things, changing the cluster name and upgrading the cluster version.
Both weren't working very well anymore from the old screen. I did some quick fixes to make it work again.
I think we should also reconsider the approach in ViewEditName component, I think it knows too much about what to do when pressing submit. 
Lets talk later @ograu !
=> Fix issues with cluster updating.

src/actions/clusterActions.js, src/components/home/index.js, src/reducers/clusterReducer.js
Instead of trying to merge things as they come in, this makes the clustersLoad action fetch everything about all clusters all at once.
The disadvantages here are that this will be fine for small installations, but not so great for installations with many clusters.
What is happening now, if we have 100 clusters across 10 orgs, is that each time we will do ~300~ 201 requests, even if we are only looking at a org that has only 10 clusters.
So that's probably one of the reason the code evolved the way it did. Lets keep thinking, and submitting this now so you can see what it looks like.
=> Fetch everything at once

src/actions/nodePoolsActions.js, src/components/UI/view_edit_name.js, src/components/cluster/detail/cluster_detail_view.js, src/components/cluster/detail/node_pool.js
@ograu, this would be my approach to make it so that the view and edit name component doesn't know it has to dispatch anything. 
Instead all it expects is a Promise for the onsubmit call, so it stays concerned with calling that function and dealing with a success or a failure.
Side effect, no more optimistic updates. Which I question a bit to be honest. I'd rather show a spinner, to let the user know something is happening, and then an error, instead of doing a optimistic update, and then throwing an error after the fact.
This PR is for discussion so you can see the approach I would take here, and see what you think of it.
Is this promise stuff too old school or weird or bad practice?
=> Make view and edit name know a bit less about our tech stack.

src/actions/clusterActions.js, src/components/UI/view_edit_name.js
This fixes something new that I don't have a good explanation for.
Suddenly the `getclusterstatus` call of the `giantswarm-js-client` started returning `{}` even though I could see in the network tab that a successful request had been made, and it contained real data in the response.
It's very weird, and couldn't be due to any changes or experiments in `giantswarm-js-client`, I haven't merged any of my changes there to master.
This PR also fixes some console warnings and output I noticed while debugging.
=> Fix errors getting cluster status

package.json, src/actions/appConfigActions.js, src/actions/catalogActions.js, src/actions/clusterActions.js, src/actions/nodePoolsActions.js, src/actions/organizationActions.js, src/actions/releaseActions.js, src/actions/userActions.js, src/components/account_settings/change_email_form.js, src/components/account_settings/change_password_form.js, yarn.lock
This removes the need to constantly set scheme and token when doing an api request.
The api wrapper handles fetching a new token when a call fails, however with the way we are doing it in some chained requests, when this new token is acquired, we're still using the old token that we took from the state, instead of being able to rely on the instance of the API having its authentication set correctly.
By removing the authentication header we manually added to each call in the api-spec, we can use the javascript client in this more 'natural' way.
=> Simplify auth state

src/actions/userActions.js
This fixes a problem with logins due to my change in how authentication is set for the giantswarm-js-client.
After authenticating, the `loginSuccess` action sets the api instance's authentication.
But that happened after some follow up calls (getCurrentUser, and getInfo). Those calls actually aren't necessary anymore, since the componentDidMount of the Layout component calls this as well. 
So I removed those, and let the `loginSuccess` action do the job of setting the auth token of the api client, so that future requests will work once the Layout component is mounted.
=> Fix logins for password users.

helm/happa-chart/templates/service.yaml, helm/happa-chart/values.yaml
- remove unecessary nodeport from service.
- migrate to using values instead of hardcoding.
=> Remove nodeport from service

src/components/cluster/new/view.js
This is a quick fix to make sure that Happa can't make clusters that are invalid. 
Once https://github.com/giantswarm/api/pull/855 is merged , kvm clusters with less than 2CPU and 3GB RAM are invalid, so this makes sure people can't even try to create smaller clusters.
Once https://github.com/giantswarm/api-spec/pull/167 is _implemented_ I will make this value dynamic, populated by what the info endpoint returns.
But for now this is a quick fix to stop people from making invalid clusters.
See also: https://gigantic.slack.com/archives/C76JX6YLQ/p1567516000045900?thread_ts=1567509332.042700&cid=C76JX6YLQ for the 4/4 default.
=> Set the cpu/ram default to 4/4 and min to 2/3

src/actions/clusterActions.js, src/actions/nodePoolsActions.js, src/components/cluster/detail/cluster_detail_view.js, src/components/home/cluster_dashboard_item.js, src/utils/cluster_utils.js
Marian has added the mocked NP cluster to the cluster list response in the `add-mock-cluster-to-list` API branch so now we can have a `clustersLoad` method that gets all clusters (v4 and v5)
In this PR I have:
- Modified the `clustersLoad()` function to fetch everything
- Removed logic for introducing `m0ckd` v5 cluster manually in the store
- Adapt `ClusterDashboardItem` to the modifications made
⚠️ ⚠️  From now on (once this is merged) in the local testing api we must use the `add-mock-cluster-to-list` branch. ⚠️ ⚠️
=> NPs clusters in cluster list

src/components/app.js, src/components/routes.js, test_utils/preloginState.js, test_utils/renderRouteWithStore.js
This makes sure we render really the _full_ app with `renderRouteWithStore` instead of just the `Layout` component.
This is because the routes for Login are 'before' we show the `Layout` component.
This will let me test the login screen going from the login form to the screen that shows the `Layout` component.
=> Extract routes and add preloginState

src/actions/clusterActions.js
I noticed in development we occasionally got the 0 node, 0 CPU bug again.
That's because of a change in the status action which wasn't carried through in the mocked status response part.
This feels like a regression though, not sure how this came back in the dev env, which is a bit scary.
=> Fix mocked status response.

src/components/UI/number_picker.js, src/components/cluster/new/view.js
Validation message in number picker was not popping up because the code responsible for it was never reached. Now it is:
=> Number picker refactor

.eslintrc, src/components/UI/availability_zones_label.js
- Unreacheable code to warning, because I like to do early returns when debugging without needing to comment x lines of code below the `return`statement.
- Removed sort imports rule because I prefer to sort imports in custom ways (node modules, components, custom hooks, UI, styles)  or not ordering them at all
WDYT Marian?
=> Es lint changes

src/actions/releaseActions.js, src/components/cluster/new/CreateNodePoolsCluster.js, src/components/cluster/new/CreateRegularCluster.js, src/components/cluster/new/NewCluster.js, src/components/cluster/new/ReleaseSelector.js, src/components/modals/release_details_modal.js, src/index.html, src/reducers/releaseReducer.js
In order to have two different cluster creation forms in Happa that can be switched when the user changes the release version in the form, we need to control release version from the parent wrapper component, `NewCluster`, instead of controlling it from `ReleaseSelector`.
the In this PR we are transforming `ReleaseSelector` into a _dumb_ component that is not connected to the store. Now it just returns a release version to its parent instead of deciding which release the form has a default value, so it is more reusable.
- Moved async logic to action file
- Lifted up state from `ReleaseSelector`to `NewCluster` which is the wrapper component for the two cluster creation forms (v4 and v5) so
=> Refactor ReleaseSelector and parent components

src/components/cluster/detail/AddNodePool.js, src/components/cluster/new/CreateRegularCluster.js
In this PR:
- When there is no release in create cluster form submit button is disabled
- *Unnamed cluster* as a default name and placeholder when input is empty
- Added meesage *X CPU Cores,  X GB RAM each* message next to the instance type selected.
- Fixed the message in `AddNodePool` component, data was wrongly placed.
=> V4 cluster form additions

__tests__/login.js
Because I saw that some calls are performed more than once, I had to persist api calls, otherwise "no match" `nock` error is thrown.
Should we open an issue to investigate this further?
=> Modified login test so it does not throw an error in CircleCi

src/actions/clusterActions.js, src/reducers/clusterReducer.js
The action we dispatched never included the cluster. So the reducer would always throw a `cannot read property id`
Brought it more in line with the other reducers.
=> Fix error loading cluster action.

src/components/UI/loading_overlay.js, src/components/cluster/detail/ClusterDetail.js, src/components/cluster/detail/ClusterDetailView.js
Fixes attempts to reach`cluster.id` on the cluster detail page when a cluster isn't there.
=> Fix direct visit to cluster detail view on clusters that don't exist anymore.

src/actions/clusterActions.js, src/actions/organizationActions.js, src/actions/userActions.js, src/components/UI/__tests__/catalog_type_label.js, src/components/UI/organization_list/index.js, src/components/UI/organization_list/row.js, src/components/auth/admin.js, src/components/auth/logout.js, src/components/cluster/detail/AddNodePool.js, src/components/cluster/detail/ClusterDetailView.js, src/components/cluster/detail/CredentialInfoRow.js, src/components/cluster/detail/KeyPairCreateModal.js, src/components/cluster/detail/ScaleClusterModal.js, src/components/cluster/detail/ScaleNodePoolModal.js, src/components/cluster/detail/V4ClusterDetailTable.js, src/components/cluster/new/CreateNodePoolsCluster.js, src/components/cluster/new/CreateRegularCluster.js, src/components/cluster/new/NewCluster.js, src/components/cluster/new/ProviderCredentials.js, src/components/organizations/detail/credentials.js, src/components/organizations/detail/view.js, src/lib/giantswarm_client_patcher.js, src/mockedStatus.js, src/shared/constants/AuthorizationTypes.js, src/shared/constants/Providers.js, src/shared/constants/index.js, src/shared/index.js, test_utils/initialState.js, test_utils/mockHttpCalls.js, test_utils/statusState.js
Fixes giantswarm/happa#859
- Create shared folder where we can place constants / other cool stuff
- Create constants for providers
- Create constants for authorization types
- Replace usage of hard-coded providers/authorization types with the enum-like object values
Please go on and suggest what else to write in this manner. (apart from the URLs, that will be separate)
=> Move providers to enums

src/components/cluster/detail/ScaleClusterModal.js, src/components/cluster/detail/ScaleNodePoolModal.js
Towards https://github.com/giantswarm/giantswarm/issues/5770
This replace a warning mentioning that we do not support or monitor clusters below three worker nodes (which is not the case) with a recommendation to have at least three worker nodes.
=> Replace less than three nodes warning with recommendation in scaling dialog

package.json, src/components/cluster/detail/ClusterApps.js, src/components/cluster/detail/__tests__/ClusterApps.js, test_utils/mockHttpCalls.js, yarn.lock
This filters out apps like `chart-operator`, `kube-state-metrics`, `metrics-server`, and `node-exporter`
from the user installed apps list. They appear there now because we have `App CRs` for them in the meanwhile and Happa assumed every App was user installed.
=> Filter out apps that are pre installed from the user installed apps list

src/components/cluster/detail/NodesRunning.js, src/components/cluster/detail/WorkerNodesAzure.js, src/components/cluster/detail/WorkerNodesKVM.js, src/index.html
This fixes worker nodes not being rendered when `workerNodes === 0`.
Also, this is a dirty fix for a warning from `PropTypes` in `NodesRunning` also when when `workerNodes === 0`.
I created an issue for improving this, cause it feels like we can do it better here: https://github.com/giantswarm/giantswarm/issues/7852
=> More minor fixes for Azure and KVM WorkersNodes components

.vscode/launch.json
Enable VSCode debugging with the help of an unsafe chrome session (no moar CORS)
=> Add unsafe chrome configuration

src/components/app_catalog/AppList/AppList.js
This PR restores the required Fragment to the AppList component in the AppCatalog. It seems the DocumentTitle Component only supports single element children. ¯\_(ツ)_/¯
=> Restore Fragment wrapper

.eslintrc
(Removed `no-invalid-this` since it gets triggered by class methods defined as expressions)
=> Configure rules further for better linting

src/components/UI/AvailabilityZonesLabel.js
This adds a check for `onToggleChecked` to the `onClick` action of the AZ Label, so that we do not try to call an undefined function.
I moved the onClick logic out of the JSX and into a function called `onClick` as a little refactoring.
another note I have here is that I think this component is too smart about what it is and what kinds of context it is used in.
I would just expect it to take a onClick function, that we will call if it is not undefined.
right now it seems to know more about the specific situations it will be in, and that kind of logic is I think better left to the implementor of this component. 
But opting not to refactor that now.
=> Fix an exception when clicking on an AZ label

package.json
So that we don't run prettier on `yaml` or `html` if they happen to be in our commit.
=> Make prettier only focus on js files.

yarn.lock
Towards https://github.com/giantswarm/giantswarm/issues/8212.
I only updated the minimal dependency to the one currently installed in yarn.lock which is the latest version of handlebar
I did not upgrade all depencies as I am not sure how I can test if upgrading them do not break the UI
=> Update handlebars version to fix CVE-2019-19919

src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
Fix https://github.com/giantswarm/giantswarm/issues/8205
The attribute name submitted in the POST request for cluster creation is fixed to `availability_zone`. Before, the name `availabilityZone` was used, which caused the API to ignore the attribute as unknown.
In addition, the `master` attribute is only set when the user has manually selected an availability zone to use. Otherwise it is not contained in the payload, to leave defaulting to the API.
=> Fix cluster creation payload structure for master node availability zone

__tests__/Login.js, __tests__/Organization.js, jest.config.js, src/actions/organizationActions.js, src/components/Modals/Modals.js, src/components/Organizations/Detail/View.js, testUtils/mockHttpCalls/constantsAndHelpers.js, testUtils/mockHttpCalls/user.js
This contains some changes:
- I changed the `API_ENDPOINT` to differ from the one used in local development, to prevent accidental usage of a locally running API
- Make the user response never expire in the user response mock
- Added Organization tests
=> More organizations tests

src/components/app.js
This fixes the missing URL and User Agent missing since https://github.com/giantswarm/happa/commit/d3365611c6cbf796485a750e488bdfbee4d3c3a6 from the requests to the exception notification endpoint
=> fix exception reporting

src/components/AppCatalog/AppDetail/Input.js, src/components/AppCatalog/AppDetail/InstallAppForm.js, src/components/AppCatalog/AppDetail/InstallAppModal.js, src/components/AppCatalog/AppDetail/__tests__/InstallAppForm.js
This ensures that the  `nginx-ingress-controller-app` can only be installed to the `kube-system` namespace.
=> Kubesystem for ingress app namespace

src/components/Modals/Modals.js
Towards giantswarm/giantswarm#8403
Validates the input field for creating organizations using `minlength`, `maxlength` and `pattern` fields and only allows to click the button if validation succeeds
=> Validate organization creation input

package.json, yarn.lock
- Remove the `pretty-quick` dependency
- Use `lint-staged` to only run tasks on staged files before commiting
Now both linting and formatting are running just on staged files, which increases development speed.
=> Fix pre-commit formatting not running on staged files

src/actions/clusterActions.js, src/reducers/loadingReducer.js
Several things going on here as a previous step for moving resource computations to `clusterActions`:
- Removed old `clusterLoadStatus()` because it was useless as we just call status endpoint for v4 clusters
- Added `NOT_FOUND` suffix to `loadingReducer.js` that will set loading flag to false (I owe you documentation explaining how this works, coming this week)
- And inlining action objects: I find that this is best for readibility, specially in big files. WDYT? Are you ok with this?
=> Minor refactor cluster status call

src/components/Organizations/Detail/Detail.js
Fixes https://github.com/giantswarm/giantswarm/issues/8474
Don't know exactly why we were selecting organization on `componentDidMount`, but with the new data flow I think it is not needed anymore.
=> Fix loading all clusters when in detail view

src/components/AppCatalog/AppDetail/InstallAppModal.js, src/components/Cluster/ClusterDetail/ClusterDetailView.js, src/components/Cluster/NewCluster/CreateRegularCluster.js, src/utils/__tests__/computeCapabilities.js, src/utils/clusterUtils.js
This pull request removes tennant cluster release versions from some places in happa.
I checked tennant cluster versions with lowest to be `8.0.0` (I've done this with [these](https://github.com/giantswarm/giantswarm/blob/master/ops-recipes/list-tenant-clusters.md) instructions)
I am sure you'll find this change to be very controversial in regard to removing these kind of guards. In my opinion removing these checks is a good thing because it removes code that isn't executed anyway when no one is using these old cluster versions.
=> Remove deprecated version checks

src/actions/batchedActions.js, src/actions/clusterActions.js, src/reducers/clusterReducer.js
Instead of deleting the cluster object, I am setting the `deleted_date`, which is more like how the API works too.
That way we don't remove it from the list, and then have it suddenly pop back in again in case it is taking a while to be deleted.
Related to: https://github.com/giantswarm/happa/issues/1034
=> Adjust deletion behaviour.

src/components/Cluster/ClusterDetail/WorkerNodesAWS.js, src/components/Cluster/ClusterDetail/WorkerNodesAzure.js, src/components/Cluster/ClusterDetail/WorkerNodesKVM.js, src/components/UI/RefreshableLabel.js, src/utils/clusterUtils.js
Fixes https://github.com/giantswarm/giantswarm/issues/8567
- Create a `ScalingNodeCounter` component, that it's reused for all providers, for consistent styling
- Show a `n/a` label instead of showing `0` nodes if the cluster is not loaded yet
- *BONUS:* Lower the precision of the total memory displayed in the cluster detail, as it would sometimes display 64-bit floats
**Preview**
=> Show a 'n/a' label when there are no nodes loaded yet

src/actions/clusterActions.js, src/components/Cluster/ClusterDetail/ClusterDetail.js, src/components/Cluster/ClusterDetail/ClusterDetailView.js, src/components/Home/ClusterDashboardItem.js, src/components/Home/ClusterDashboardResources.js, src/components/Home/Home.js
We have different names for the same concept: `isV5Cluster` and `isNodePoolsCluster`
I decided to drop `isNodePools` and use `isV5` instead because it is shorter and because it is less related to a specific feature.
=> Use isV5 instead isNodePools

package.json, src/components/Home/ClusterDashboardLoadingPlaceholder.js, src/components/Home/ClusterDashboardResources.js, src/styles/theme.js, yarn.lock
Added a component that renders placeholders in place of resources in cluster dashboard item when loading state === `true`.
Using react-content-loader, which is really lightweight: https://github.com/danilowoz/react-content-loader#features
Placeholders have an animated background using a two color linear gradient.
It renders just one box for v4 clusters and three for v5 clusters, as we are rendering more info for v5 clusters:
=> Placholder in clusters list using react-content-loader

src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
In cluster view, there is a small fraction of time during which you can see the _Add at least one node pool to this cluster so that you can actually run workloads_ message.
In this PR I am just using the cluster node pools loading flag to check that node pools loading process has actually finished. So the message won't be shown while loading node pools.
=> Hide no node pools message before node pools are loaded

src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
When a user deletes the last node pool in a cluster, Happa shows a spinner instead showing the no node pools message.
This PR fixes this behaviour.
Also it changes the initialization of local nodePools so you can see at a glance its type.
=> Let produceNodePools reset local nodePools in NodePools component

src/actions/clusterActions.js, src/components/Cluster/ClusterDetail/ClusterDetailView.js
The cluster upgrade and cluster scale modal do not pass the `isV5Cluster` param to the `clusterPatch` action. This should actually somehow mean it was never possible to correctly upgrade or scale v5 clusters, so I am a bit confused.
But instead of teaching them how to find out if their cluster is v5 or not, I moved the logic into the action, as that is a thing we do in some other actions as well. That way the components have to know less about the right way to call the action, which I think is a good thing.
=> Fix upgrading v5 clusters.

src/utils/clusterUtils.js
This makes happa be a bit more graceful about not getting the instance type details.
There will still be a buggy situation, we'll show 0 CPU and 0 RAM in this case, but this is just a way to make happa a bit more graceful in the meanwhile.
=> Don't crash if we can't get instance type details.

__tests__/PasswordForgot.js, jest.config.js, src/actions/forgotPasswordActions.js, src/components/SignUp/SignUp.js
This removes obsolete TODOs from Login tests
=> remove obsolete TODOs & switch to 5.6.7.8 for passage endpoint in tests

.circleci/config.yml
Using the old version makes CI fail
=> [CHANGE] Update circle CI node.js version to 12.15.0

.github/pull_request_template.md, .github/release-template.yml, .github/workflows/main.yml
Implement categorization of PR titles in draft release by PR labels
* Introducing a new feature
- `kind/feature`
* Changing existing functionality  
- `kind/change`
- `kind/refactor`
- `kind/ux-enhancement`
* Soon-to-be removed features
- `kind/deprecation`
* Removing features
-  `kind/removal`
* Fixing bugs
- `kind/bug`
* Fixing vulnerabilities
- `kind/security`
**Excluded from changelog**
* `dependencies` (Updating dependencies)
* `kind/dev-change` (Changing development commands, file structure, etc.)
=> Remove PR title prefix validation

src/actions/clusterActions.js, src/reducers/clusterReducer.js
When a cluster is finally removed (excluded from response in `/v4/clusters` after been marked as `deleted`) Happa has to remove the cluster from the store, otherwise it will be trying to fetch data for a cluster that no longer exists and triggering error messages.
=> Delete cluster on 404

src/components/Modals/Modals.js
Fixes https://github.com/giantswarm/giantswarm/issues/8823
- Clear organization modal state after closing
- Make organization input be automatically selected after opening the organization creation form
=> Reset create organization modal before closing

.circleci/config.yml
😅 Now that we prepend tags with `v` the deploy is not triggered.
=> Fix tag filter now that we prepend with v.

src/actions/userActions.js, src/components/Auth/AdminLogin.js, src/lib/giantswarmClientPatcher.js, src/reducers/appReducer.js
I found 2 problems:
- We were manipulating data in the `refreshUserInfo` action creator, and when the action got triggered, it would just revert the change made by the token refresh action
- There was a race condition between refreshing the token and executing requests, because the response from the Auth0 servers would sometimes not be quick enough, so the actual authorization header would not be updated
=> Fix JWT token not being used after being refreshed

src/actions/batchedActions.js
Wait for the cluster delete action to complete before redirecting to the organization overview.
It's possible that deleting fails, so then we should still be on the cluster detail page.
=> Wait for delete before redirecting.

src/reducers/errorReducer.js, src/reducers/index.js
Towards https://github.com/giantswarm/giantswarm/issues/6716
The idea is to centralise our error flags/messages into an `error` object in the store, and use them in error boundaries.
=> Add error reducer

src/components/Home/ClusterDashboardItem.js, src/components/UI/ErrorFallback.js, src/reducers/entityErrorReducer.js, src/reducers/errorReducer.js, src/reducers/index.js, src/selectors/clusterSelectors.js
Introducing `ErrorFallback` and `entityErrorReducer`.
I want to display meaningful info in the view when something did go wrong. For example, when for any reason we can't fetch node pools, I don't want `0 nodes`(which is not true)  in the place when resources should be detailed in clusters list. I'd prefer to have a message telling something to the user:
- `ErrorFallback` is like `LoadingOverlay` but for errors.
- `entityErrorReducer` is used to keep track of errors that happen to every cluster/node pools/entity. Errors are stored in an `errorsByEntity` object so we can fetch and use them quickly in components.
ps: forget about ErrorBoundaries, and sorry for mixing concerns. Error Boundaries are for catching errors in the view. I am more concerned by how we handle errors from API calls.
=> Add entity error reducer and ErrorFallback component

__tests__/V5ClusterManagement.js, src/components/Cluster/ClusterDetail/NodesRunning.js, src/components/Home/ClusterDashboardResources.js, src/shared/constants/fallbackMessages.js, src/shared/constants/index.js
Towards https://github.com/giantswarm/giantswarm/issues/8860
We want to give relevant information in the resources components when the cluster is being created. Now we are showing this:
In this PR I am proposing this:
And this:
ps: not sure if the message is really appropiate
=> Fallback message when nodes are not ready yet

src/components/Cluster/ClusterDetail/NodesRunning.js, src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js, src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js, src/components/Home/ClusterDashboardResources.js, src/utils/clusterUtils.js
Reverts giantswarm/happa#1108 as cluster data doesn't include timezone, so date comparisons are not possible.
=> Revert "Change nodes not ready condition"

webpack.dev.js
This fixes the webpack development config broken since #1130
=> Use [hash] for js asset in dev

__tests__/V4AzureClusterManagement.js
Adding the new assertions after tests finish and cleaned up calls.
Opened mostly because it was breaking the build on https://github.com/giantswarm/happa/pull/1145
=> Clean up V4AzureClusterManagement tests

src/actions/clusterActions.js, src/components/Cluster/NewCluster/CreateNodePoolsCluster.js, src/components/Cluster/NewCluster/CreateRegularCluster.js, src/reducers/errorReducer.js
Towards https://github.com/giantswarm/giantswarm/issues/8860
Fixes https://github.com/giantswarm/giantswarm/issues/9088
This fixes some quirks in v4/v5 creation form: https://gigantic.slack.com/archives/CQ465CFG8/p1582631553009400 . Basically, no error message and an endless spinner.
Now it will show a flash message and the actual error message instead the buttons:
This is a quick fix. IMO it's not ideal and we should think how do we want to translate these kind of errors into meaningful pieces of UI. Maybe adding a button for retry would be a better option.
=> Error handling in cluster creation views

src/components/Cluster/ClusterDetail/NodePool.js, src/components/Organizations/Detail/View.js, src/styles/index.js
Fixes https://github.com/giantswarm/giantswarm/issues/9083 in organization view.
Before:
After:
And adds `Ellipsis` as a composable styles that you can throw anywhere you want this behaviour as long as its parent is a `block` element and has `white-space: no-wrap`
=> Ellipsis in members list and as a composable

src/actions/appActions.js
Fixes error handling when creating an app already installed: https://gigantic.slack.com/archives/C13MG9F0W/p1582714381022700
=> Show app name instead of object Object in flash and error to reducer

src/components/App.js, src/components/index.js, webpack.common.js
While working on #1124 I've noticed hot reloading threw some error about using `hot` and `render` in the same file being discouraged and linking to the [Getting Started](https://github.com/gaearon/react-hot-loader/#getting-started) documentation of `react-hot-loader`. 
These changes resolve the error for me and also in #1124 
Somehow tests seem to be failing randomly on my machine.. lets see how this behaves in CI
=> moved Root app Component to own file

__tests__/GettingStarted.js
Towards: https://github.com/giantswarm/happa/issues/759
We're already indirectly testing that the get started button shows up in the Getting Started tests. I added a test now to check that it goes away when the cluster is older than 30 days.
Also refactored to non-persisted nock calls.
=> Get started button tests

__tests__/AppCatalog.js, src/components/Cluster/ClusterDetail/ClusterApps.js, testUtils/mockHttpCalls/releases.js
`cert-exporter` and `net-exporter` were originally not in the `releases` endpoint response. So we added them manually because we wanted to see them in Happa.
Now some clusters will have it in their release and some will not. So we need to deduplicate the app from the app detail pane.
This also adds a couple more tests to round off the app catalog tests, and organises the app catalog tests based on whether is about installing apps or if its about the app detail pane on the cluster detail page.
Fixes what you see below, the double cert-exporter and net-exporter:
=> Don't show cert-exporter and net-exporter twice. 

.circleci/config.yml
- Declare `NODE_VERSION` in the CI, so we could easily configure the Node.js version, without having to merge a pull request
- Upgrade to latest architect orb version
- Format Circle CI config file
=> Remove 'NODE_VERSION' variable declaration from ci configuration

src/components/AppCatalog/AppDetail/AppDetail.js, src/components/AppCatalog/AppDetail/Input.js, src/components/AppCatalog/AppDetail/InstallAppForm.js, src/components/AppCatalog/AppDetail/InstallAppModal.js, src/components/UI/VersionPicker/VersionPicker.js
Looks like this right now:
The 'test' versions feature of the version picker is not something I can implement yet, so I will make a tweak to the version picker to be able to not show the test version check box, since right now it does nothing.
~- [ ] Show what app version this will install.~ will do that as a UX improvement in another PR.
Towards: https://github.com/giantswarm/giantswarm/issues/8021
Some design discussion: https://github.com/giantswarm/giantswarm/issues/8846
=> Version picker during app installation

src/components/Cluster/ClusterDetail/ClusterDetailView.js
Removed the conditional because we are not doing the check here. 
Not sure what is cheaper: checking if the cluster can update or rendering the modal.
=> Fix triggering of update cluster modal

src/components/Cluster/NewCluster/CreateNodePoolsCluster.js, src/components/Cluster/NewCluster/CreateRegularCluster.js, src/components/Cluster/NewCluster/NewCluster.js
Right now, we have the following scenario:
* Go to the organizations page
* Click on an organization that is not your currently selected one
* Press on the `Create Cluster` button
* Create a cluster
The new cluster will not be created in the organization that you clicked on, but on the currently selected organization (in the top dropdown)
This PR makes clusters be created in the organization that you clicked on 👍
=> Clusters are created in the currently selected organization, instead of a picked organization

src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
Fixes this https://gigantic.slack.com/archives/C3MCF5EJK/p1583932105000800
The problem is that the modal is rerendewring without props after the dispatching/submitting. 
The quick and dirty solution is this one in this PR, but we should refactor it following the new data flow. Will try to do it tomorrow.
=> Upgrade cluster modal: avoid rerendering after dispatching the action

src/model/clients/HttpClient.js, src/model/clients/__tests__/HttpClient.js
Just for our pleasure 😬 
**Before**
```javascript
client.setHeader('TestHeader');
client.setHeader('TestHeader2', config.headers.TestHeader2);
client.setHeader('TestHeader3', config.headers.TestHeader3);
client.setAuthorizationToken('testScheme', token);
client.setRequestMethod('POST');
client.setBody({
test: 'test',
});
client.setURL('/api/test');
```
**After**
```javascript
client
.setHeader('TestHeader')
.setHeader('TestHeader2', config.headers.TestHeader2)
.setHeader('TestHeader3', config.headers.TestHeader3)
.setAuthorizationToken('testScheme', token)
.setRequestMethod('POST')
.setBody({
test: 'test',
})
.setURL('/api/test');
```
=> Add support for chaining HttpClient methods

__tests__/AppCatalog.js, src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
Fixes the order in which we close the app detail modal and fetch an updated list of apps.
Otherwise we run into a problem after deleting an app, if the app is gone before the modal closes, the modal will throw an error as it tries to render a non existing app.
Also edits the tests to recreate what actually happens. (Made it fail like in production, then fixed it.)
=> Fix an error when deleting an app.

__tests__/KeyPairs.js, src/components/Cluster/ClusterDetail/KeyPairCreateModal.js, testUtils/mockHttpCalls/index.js, testUtils/mockHttpCalls/keypairs.js
Towards: https://github.com/giantswarm/happa/issues/759
To check off `Key pairs tab: renders data correctly` and `Creating a keypair`
I don't think we need to copy the test for a v4 cluster, since it's the same tab and would exercise pretty much the same code... what do you guys think?
=> More keypair tests.

src/components/Cluster/ClusterDetail/ClusterDetailView.js
Fix for `undefined` `api_endpoint` in cluster details view: https://gigantic.slack.com/archives/C3MCF5EJK/p1584444878000300
Adding the specific cluster flag for the cluster because when accessing it directly it doesn't exists in the store, so this:
```javascript
<LoadingOverlay loading={this.props.loadingCluster}>
<KeyPairs cluster={cluster} />
</LoadingOverlay>
```
can't do its job.
=> Fix for undefined API endpoint in cluster details view

__tests__/V4AWSClusterManagement.js, __tests__/V5ClusterManagement.js, src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js, src/components/Cluster/ClusterDetail/ClusterDetailView.js, src/components/Cluster/ClusterDetail/NodePool.js, src/components/UI/ViewEditName.js, src/components/UI/__tests__/ViewEditName.js, src/components/index.js, src/lib/ErrorReporter.js, testUtils/setupTests.js
Fixes https://github.com/giantswarm/giantswarm/issues/9428
* Wrote unit tests for initial component, to not refactor blindly
* Refactored the component, disconnected it from the store
* Made the `OK` button have the success look (to be different from the cancel button)
* Removed the success message after editing cluster/node pool names, we're going full optimistic here (if the request fails, an error flash message would be shown, and the value will be reverted to the one before the change)
* Updated the tests that asserted those messages
* Instead of displaying a flash message with an error if the input validation fails, we're displaying a tooltip with the error message, giving the input a red border, and disabling the submit button
* **Error state**
* **All bueno**
=> Optimistic update on cluster name change

__tests__/AdminLogin.js, __tests__/ForgotPassword.js, __tests__/SignUp.js, testUtils/renderUtils.js, testUtils/setupTests.js
This should fix the problem with the tests in https://github.com/giantswarm/happa/pull/1124/
This was branched off of that brach, and is meant to be merged back into it
The problem was when rendering a route during tests:
* The `/` path would be the initial path
* We would push to the desired path provided to the `renderRouteWithStore` function
The problem in the `SignUp` tests was that we would first push to `/` with an user in the storage, so the app would deserialize it and act like it was logged in, which would mount the `Layout` component and trigger the API calls. Then we would redirect to `SignUp`, but we would cut the test before the api calls were actually done.
The reason why this only surfaced now is that lazy rendering is asynchronous, which gave the API requests time to …
=> Fix test router redirecting

src/styles/components/_flash_messages.sass
This PR moves the topRight noty notification a little bit lower so it does not overlap with user and org controls on small displays:
Before:
After:
=> Remove noty top right overlapping user & org components

package.json, src/index.html, yarn.lock
https://github.com/advisories/GHSA-6c8f-qphg-qjgp
Forcing all packages that have the `kind-of` dependency  to use the patched `6.0.3` version.
=> Fix CVE 2019 20149

src/components/Cluster/ClusterDetail/ClusterApps.js, src/components/Cluster/ClusterDetail/ClusterDetailView.js, src/components/Cluster/ClusterDetail/KeyPairs.js, yarn.lock
As seen on slack: https://gigantic.slack.com/archives/CQ465CFG8/p1585817925007000
This was happening inside of `V5 Cluster Details` -> `Add new node pool`
This also adds an ordering fix to `yarn.lock`, which I forgot to push in my previous vulnerability fix PR.
=> Fix instance type position inside the create node pool form

src/components/Home/ClusterDashboardItem.js, src/styles/_base.sass
Just a couple of minor changes in mobile view to make better use of available view height:
- I've moved the _get started_ button to the top and to the right, and have made it smaller
- I've reduced the space above the _launch new cluster_ button
Before:
After:
=> Happa home mobile changes

__tests__/AppCatalog.js, __tests__/AppDetailPane.js, src/actions/appConfigActions.js, src/actions/appSecretActions.js, src/components/AppCatalog/AppDetail/InstallAppForm.js, src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js, src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
I've been working on some documentation around app configuration and some domain language is emerging that I'd like to carry through in the UI as well.
The way I labeled the configuration fields was confusing at best and misleading at worst.
This might be a lot more verbose, but the intention is to explain that you are uploading a file containing values for a specific configuration level. I will eventually add something like "click here for an example file" or "click here for docs" to explain that further.
The toasts are also adjusted to be very explicit about what is happening.
=> Clarify app configuration fields.

yarn.lock
I've added types to the GS API client (60% generated, 40% by hand) -> they are mostly good
https://github.com/giantswarm/giantswarm-js-client/tree/master/%40types
This means we can have code completion and good interop with TypeScript, so we can migrate our store/actions to TypeScript.
Example
=> Update GS API client to expose TypeScript types

Makefile, package.json, src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js, src/components/UI/AppContainer.js, src/components/UI/AppDetails/AppDetails.js, src/components/UI/AppDetails/ChartVersionsTable.js, src/components/UI/Truncated.tsx, src/components/UI/__tests__/Truncated.ts, src/lib/__tests__/helpers.js, src/lib/helpers.js, testUtils/renderUtils.js, tsconfig.json
Provide more useful truncations.
For long similar strings, it's easier to find differences by looking at the beginning or at the end of each of them.
**Before**
**After**
**After, on hover**
=> Implement smart truncation for strings

src/components/Home/ClusterDashboardItem.js
Fix for `TypeError: Cannot read property 'delete_date' of undefined`. 
I can't reproduce the issue. I think this is something that happens when the cluster is deleted using `gstl`. This fix is based in this assumption.
[Error log](https://gigantic.slack.com/archives/C3MCF5EJK/p1586258998001700) in slack #exceptions channel.
=> Add a guard in dashboard item

__tests__/V5ClusterManagement.js, src/components/Modals/Modals.js
This is something requested by a user: [check the slack thread](https://gigantic.slack.com/archives/C03LYSJL0/p1586276256002400) where this was discussed.
Before (no matter how many node pools the cluster has):
After with two or more node pools:
With just one node pool:
=> Node pools messages in delete modal

src/components/Home/Home.js, src/selectors/clusterSelectors.js
For some reason, clusters sorting is not stable, and this tricks the selector comparison, producing a lot of extra re-renders. Sorting in the selector to fix this.
=> Fix cluster list selector

src/actions/clusterActions.js, src/components/Cluster/ClusterDetail/ClusterDetailView.js
Fixes https://github.com/giantswarm/giantswarm/issues/9879
I added support for the case when the cluster is deleted: it is not `undefined`, but we don't want the user to access the details view. 
Now, on delete, the user will be redirected and a toast will notify him that the cluster has been deleted or it is not in her organizations.
Also removed redirection from `clusterActions` because I think this is not the place for this, as this action can be dispatched in different contexts.
=> Redirect from details after deletion

.circleci/config.yml
This should fix tags not deployed. 
This is caused by me not reading the [circle ci docs].
> CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must specify tag filters for those jobs.
[circle ci docs]: https://circleci.com/docs/2.0/configuration-reference/#tags
=> run all ci jobs for vX.X.X tags & all branches

src/index.html, webpack.common.js
I noticed sometimes commits which changed `apiEndpoint` and `passageEndpoit` sneaked past human review. 
This PR should make it easier to change the andpoints in development by setting `HAPPA_API_ENDPOINT` and `HAPPA_PASSAGE_ENDPOINTS`. Webpack will now take care of setting the desired values. If the environment variables are missing, default values will be used.
=> Use templated endpoints in index.html

src/components/UI/AppDetails/AppDetails.js
The chart versions table length is being fixed in: https://github.com/giantswarm/happa/pull/1351
=> Show the readme if it is there and make it look ok.

src/components/UI/AppDetails/ChartVersionsTable.js, src/components/UI/AppDetails/VersionsRow.js
Clicking on the "+ 7 more" label expands them all. With no way to 'recollapse' them. I think this is something that very few people will interact with and once it's open they probably don't want to close it again.
=> On the App Detail Page, hide most chart versions, but make them expandable.

src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
Adds the apps release status field the app detail modal.
Closes: https://github.com/giantswarm/giantswarm/issues/8665
=> Show app release status in the app detail modal.

src/actions/__tests__/appActions.js, src/actions/appActions.js, src/actions/errorActions.js, src/components/AppCatalog/AppDetail/AppDetail.js, src/components/UI/AppDetails/AppDetails.js
This PR ensures we don't show a blank readme when there is a 404 or other error while loading a readme.
It also handles an edge case created by me when I incorrectly created some app releases where the 'v' is missing from the URL.
I added a error clearing action, instead of using the hook I made last time, because in this case the component I want to use it in is not a pure functional component, and I opted to create a new action instead of refactoring the component :)
=> Improve Error Handling when fetching Readmes

.gitignore, package.json, webpack.common.js, yarn.lock
This makes adding environmental variables possible with a configuration file. It is very useful in my case (where the testing api doesn't work and I always have to use a testing api).
The configuration file consists in a file called `.env`, stored in the root of the project. (it is not stored in git)
Example `.env` file
```
HAPPA_API_ENDPOINT=https://api.someendpoint.com
HAPPA_PASSAGE_ENDPOINT=https://passage.someendpoint.com
```
Importance level (from less important to most important)
- defaults
- `.env` file
- variables taken from the environment
It is also possible to mix and match (for example, only providing the api endpoint in the `.env` file, and providing the passage endpoint through the command line)
=> Add the possibility to provide environmental variables with a configuration file

src/actions/appActions.js, src/components/GettingStarted/GettingStarted.js, src/components/GettingStarted/Steps/ConfigureKubectl.js, src/components/GettingStarted/Steps/InstallIngress.js, src/components/GettingStarted/Steps/Overview.js, src/components/GettingStarted/Steps/SimpleExample.js, src/components/UI/ClusterIDLabel.js, src/selectors/clusterSelectors.js, src/shared/constants/routes.js, src/styles/components/_step_selector.sass
towards: https://github.com/giantswarm/giantswarm/issues/7783
A step gets inserted into the getting started guide for clusters that have an optional ingress controller:
Which presents a bit of an explanation and a convenient button for installing the ingress controller immediately.
=> Adjust the guide to support optional ingress controller clusters.

src/actions/appActions.js, src/components/AppCatalog/AppDetail/InstallAppModal.js
towards: https://github.com/giantswarm/giantswarm/issues/9166
related: https://github.com/giantswarm/api/pull/1013
instead of "something went wrong" we now show a slightly more specific error message.
=> Show a more appropriate error for certain cases of app creation failure.

src/lib/giantswarmClientPatcher.js
This fixes the odd case of seeing an error with a status of 401 internally in Happa even though there was no 401 in the network tab.
=> Catch only errors from renewing the token.

package.json, yarn.lock
Something is not working will with the latest version of moment introduced here: https://github.com/giantswarm/happa/pull/1418
Reverting it.
I'd like to analyse why the tests passed and what we can do to fix it.
=> Revert moment dependency upgrade.

__tests__/ClusterManagement.js, __tests__/V4AzureClusterManagement.js, src/components/Modals/ReleaseDetailsModal.js, testUtils/mockHttpCalls/releases.js
this is a follow up to #1448 
The release selection modal now shows `flatcar` for releases containing container linux >= 2345.3.1
also very little test refactoring
=> Show flatcar in release selection modal

src/components/Cluster/NewCluster/CreateNodePoolsCluster.js, src/components/UI/Inputs/RadioInput.tsx, src/styles/index.ts
Towards https://github.com/giantswarm/giantswarm/issues/10831
Replace the `Master node availability zones selection` radio inputs with the new implementation:
* Further improve the styling of the `RadioInput` component to be the same as it was before
=> Use 'RadioInput' instead of the previous implementation

src/actions/invitationActions.js, src/actions/userActions.js, src/components/Cluster/ClusterDetail/UpgradeClusterModal.js, src/components/Home/Home.js, src/components/Modals/ReleaseDetailsModal.js, src/components/UI/Navigation/OrganizationDropdown.js, src/lib/helpers.js
This PR refactors some ocurrences of `underscore` usage in happa. The import name `_` prevented our eslint rules from picking up that it wasn't used in the `Home` component.
=> Underscore cleanup

src/actions/clusterActions.js
Part of https://github.com/giantswarm/happa/pull/1486
Useful if we don't want optimistic updates.
=> Add support for reloading the cluster details after modifying them

__tests__/AppCatalog.js, src/components/AppCatalog/AppCatalog.js, src/components/AppCatalog/AppList/AppListInner.js, src/components/AppCatalog/CatalogList/CatalogList.js, src/components/UI/CatalogTypeLabel.js, src/stores/appcatalog/actions.ts
Internal catalogs now show up for admins.
Added an icon so it's hopefully clear that this does not show up for customers.
FYI @sslavic
=> Render internal catalogs for admins.

src/components/Cluster/ClusterDetail/MasterNodes/MasterNodes.tsx, src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesConverter.tsx, src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesInfo.tsx, src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesUtils.ts, src/components/Cluster/ClusterDetail/MasterNodes/__tests__/MasterNodes.ts, src/components/Cluster/ClusterDetail/MasterNodes/__tests__/MasterNodesUtils.ts, tsconfig.json
Part of #1486
**Non-HA, with the master node not ready**
**Non-HA, switch to HA**
**Non-HA, switching to HA - loading state**
**Non-HA, switching to HA - error state**
**HA, not all master nodes ready**
**HA, all master node ready**
**HA, no info on number of master nodes ready**
=> Add components for displaying master nodes in the cluster detail page

src/components/Home/ClusterDashboardResourcesV5.js
Fixes https://github.com/giantswarm/giantswarm/issues/11230
Cluster overview will show '1 node pool' instead of '1 node pools' for single node pool.
=> Show '1 node pool' instead of '1 node pools' in cluster overview

src/@types/clusterLabels.d.ts, src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx, src/stores/clusterlabels/actions.ts
I've noticed that label key change added a new label but did not clean up the label with the old key.
=> Delete old label on label key change

src/components/Cluster/NewCluster/ClusterCreationDuration.js, src/components/Cluster/NewCluster/CreateNodePoolsCluster.js, src/components/Cluster/NewCluster/CreateRegularCluster.js, src/components/Cluster/NewCluster/NewCluster.js
Fixes https://github.com/giantswarm/giantswarm/issues/11052
This PR adds a 'Cancel' button to the v4 cluster creation page & wires up both the new and the existing one to navigate to the cluster overview.
=> add 'Cancel' button to v4 cluster creation & wire it up

__tests__/AppCatalog.js, src/components/AppCatalog/AppList/AppListInner.js, src/components/AppCatalog/CatalogList/CatalogList.js, src/components/AppCatalog/CatalogList/CatalogRepo.js, src/components/UI/CatalogTypeLabel.js, testUtils/mockHttpCalls/appCatalogs.js
Catalogs can be type:test, type:stable, and type:community, and until now type:internal
`type:internal` controlled the visibility of catalogs. However, we also have test catalogs that we do not want to be visible. So this implements the new `catalog-visibilty` label, with backwards compatibility.
see also: https://gigantic.slack.com/archives/C76JX6YLQ/p1590710379008600
=> Implement catalog visibility

src/selectors/clusterSelectors.js
Missed this in https://github.com/giantswarm/happa/pull/1506
=> Make upgrades to inactive releases possible for admins

package.json, yarn.lock
Putting it back now that https://github.com/giantswarm/giantswarm-js-client/pull/113 got merged and the branch is gone. Fixes CI error 
`error Couldn't find match for "24de0aa4432eeb96e841f398bb7489eff3198d8e" `
=> Set gs client back to master.

src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
Changing the `Add labels` button label to all caps makes it more in line with other buttons present in happa.
=> Make add labels button label all caps

src/components/ForgotPassword/ForgotPassword.js
As seen in https://gigantic.slack.com/archives/CQ465CFG8/p1592250996010600
=> Remove escaped html character from reset password error

src/components/Home/ClusterDashboardItem.js
Following #1564 , this PR changes the label of the "Get Started" button to all caps in the cluster list overview.
On the cluster detail page, it is already in all caps.
=> Display Get Started button label on cluster list page in all caps

src/utils/clusterUtils.js
Missed this in https://github.com/giantswarm/happa/pull/1568
When cluster is really early in its creation phase, there will not be any `conditions` field to check, and this accounts for that.
=> Account for having no conditions when cluster is creating

src/actions/clusterActions.js, src/actions/nodePoolActions.js
Towards https://github.com/giantswarm/giantswarm/issues/11389
This will include errors from the API, or from the failed request, or fallback to a generic error.
=> Use errors from the server, if they are available

webpack.dev.js
This speeds up dev rebuilds a whole lot, at the cost of a bit less information I think in the console when an error happens. But it still shows the filename and line number, and I think it is generally speaking enough info compared to the other method.
Curious what you guys think, and if you have any opinions about that.
Related docs: https://webpack.js.org/configuration/devtool/
=> Faster rebuilds by changing the dev sourcemap generator

src/actions/clusterActions.js
As seen on https://gigantic.slack.com/archives/C0148R1G12N/p1592337017206400
Since we're overwriting the existing cluster while fetching cluster details, deleting the creation date means we actually won't have any date to show
=> Always display the cluster creation date

src/components/Cluster/ClusterDetail/NodesRunning.js, src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js, src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js, src/components/Cluster/ClusterDetail/WorkerNodesAWS.js, src/components/Cluster/ClusterDetail/WorkerNodesAzure.js, src/components/Cluster/ClusterDetail/WorkerNodesKVM.js, src/components/Home/ClusterDashboardItem.js, src/components/Home/ClusterDashboardNodes.tsx, src/components/Home/ClusterDashboardResourcesV4.js, src/components/Home/ClusterDashboardResourcesV5.js, src/utils/clusterUtils.js
As seen on https://gigantic.slack.com/archives/C0148R1G12N/p1592478994263500
This makes use of the actual `Creating` condition in the CR, as opposed to waiting an hour before checking if the nodes are there.
=> Fix broken nod in cluster overview, when they were actually ready

__tests__/V4AWSClusterManagement.js, __tests__/V5ClusterManagement.js, src/actions/batchedActions.js
As seen on https://gigantic.slack.com/archives/CQ465CFG8/p1592483898013600
Redirecting users to the homepage after deleting a cluster, instead of redirecting them to the organization details page.
=> Redirect user to homepage after they deleted a cluster

__tests__/AppCatalog.js, src/components/AppCatalog/AppCatalog.js, src/components/AppCatalog/CatalogList/CatalogList.js, src/components/AppCatalog/CatalogList/CatalogRepo.js
We did this as a kind of preloading, but I think it is too aggressive, especially now that the list of catalogs can get pretty log when you are logged in as an admin.
This avoid making a ton of requests and hitting github pages too hard.
Downside is opening the helm-stable catalog takes longer the first time. The other catalogs all load fast enough to not need to preload them.
I think that's an acceptable trade off to avoid downloading many megabytes of index.yamls that most users will probably not use.
=> Dont fetch all catalog indexes from the catalog listing page

scripts/webpack/proxyPlugin.js
Makes sure we don't expose the proxy to whatever networks your dev machine is a part of.
=> Listen for connections on local interface only.

src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx, src/components/Cluster/ClusterDetail/Ingress/__tests__/Ingress.ts, src/components/Cluster/ClusterDetail/Ingress/__tests__/InstallIngressButton.ts, src/lib/effects/useDelayedChange.js
- Fixes `useDelayedChange` when multiple changes come in sooner than the default delay.
- Make the ingress button start off in a loading state so that it doesnt flicker from green to gray to green again.
See this thread for videos: https://gigantic.slack.com/archives/CQ465CFG8/p1593759099004300
=> Fix flickery ingress button states

jest.config.js, src/@types/global.d.ts, src/actions/clusterActions.js, src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js, src/components/Cluster/NewCluster/NewClusterWrapper.tsx, src/selectors/featureSelectors.ts, src/selectors/mainInfoSelectors.ts, src/shared/FeatureFlags.ts, src/utils/__tests__/computeCapabilities.js, src/utils/clusterUtils.js, webpack.common.js
This PR:
* Removes the HA Masters feature flag
* Uses the minimum version coming from the server for computing the `supports HA Masters` capability, instead of a hard-coded one.
=> Remove HA Masters feature flag and use server-side feature flag

Dockerfile
Noticed there was a CVE out for `jq` added in our production Dockerfile.
I don't think we use `jq` at all.. removing it to see what happens.
=> Remove jq from dockerfile.

.circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/12168
I think executing the built container at least once in CI is really useful, so I kept the step and remodeled the offending job after the `architect-orb/push-to-docker` command.
=> Don't push container image twice

src/components/Cluster/ClusterDetail/NodePoolDropdownMenu.js, src/components/UI/DropdownMenu.js, src/components/UI/Navigation/Hamburger.js, src/components/UI/Navigation/MainMenu.js, src/components/UI/VersionPicker/VersionPicker.tsx, src/styles/index.ts, src/styles/theme.ts
While working on giantswarm/giantswarm#11928 I noticed we're having a Dropdown component. This PR changes the existing uses of this component to better re-use the styles defined in the Dropdown component. 
It also removes the bootstrap class `dropdown-trigger` and adds a new color to our theme which defines a `dropdownBackground` color.
<details>
<summary>Mobile Navigation Dropdown</summary>
</details>
<details>
<summary>Node pools Menu Dropdown</summary>
</details>
<details>
<summary>Version picker Dropdown</summary>
</details>
=> remove bootstrap from existing dropdowns

package.json
Dependabot is still complaining about it not being at 4.17.19, even though in the lockfile it looks to me like it resolved to 4.17.19.. anyways, forcing it now to 4.17.19 in the package.json file, to see if that clears the warning.
=> Set lodash to 4.17.19

src/components/UI/DropdownMenu.js, src/components/UI/Navigation/OrganizationDropdown.js
Towards giantswarm/giantswarm#11928
This PR refactors the OrganizationSelector 
- to use the DropdownMenu of Happa
- remove lodash & Bootstrap 
- make it scrollable
=> Refactor Organization Dropdown & make it scrollable

src/components/UI/Navigation/OrganizationDropdown.js
These changes should fix [the issues identified](https://github.com/giantswarm/happa/pull/1654#issuecomment-660617434) in #1654 
- No more highlighting of "active" links
- Switching organizations through clicking of items actually works now
=> Fix borked organization dropdown

scripts/webpack/proxyPlugin.js
This PR adds `access-control-expose-headers: Location` & `access-control-max-age: 86400` headers to proxied requests.
=> make dev cors headers more production alike

__tests__/AppCatalog.js, src/actions/catalogActions.js, src/components/AppCatalog/AppList/AppList.js, src/components/AppCatalog/AppList/AppListInner.js
As seen on https://gigantic.slack.com/archives/C3MCF5EJK/p1595517097001000
If the apps are not loaded yet, then the property is `null`.
Now we're taking that into account.
=> Fix trying to use apps before loading them in an app catalog

src/model/clients/HttpClient.js, src/model/clients/__tests__/HttpClient.js
As seen on https://gigantic.slack.com/archives/C3MCF5EJK/p1595519133001200 and https://gigantic.slack.com/archives/C3MCF5EJK/p1595518780001100
So apparently the `response` property can exist, but have an `undefined` value (this comes from `axios`). We now take that into account.
=> Fix trying to use an 'undefined' response in HttpClient

src/utils/__tests__/computeCapabilities.js, src/utils/clusterUtils.js
Towards https://github.com/giantswarm/giantswarm/issues/12326
Make Ingress Controller optional in KVM releases newer or equal to `v12.2.0`. 🥳
=> Make IC optional for KVM releases >= v12.2.0

__tests__/V5ClusterManagement.js, src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx, src/utils/clusterUtils.js, src/utils/labelUtils.ts
Closes https://github.com/giantswarm/giantswarm/issues/12431
This PR:
* hides and blocks the creation of the cluster API cluster name label (`cluster.x-k8s.io/cluster-name`) from the label editor - this is used by Azure V5
* centers the `This cluster has no labels` placeholder vertically
<details>
<summary>Before - no labels placeholder</summary>
</details>
<details>
<summary>Before - with the CAPI label</summary>
</details>
<details>
<summary>After</summary>
</details>
=> azure v5: hide CAPI cluster name label

src/actions/batchedActions.js, src/actions/clusterActions.js, src/components/Cluster/ClusterDetail/UpgradeClusterModal.js, src/components/Home/UpgradeNotice.tsx, src/components/Organizations/Detail/View.js, src/selectors/clusterSelectors.js, src/styles/index.ts, src/styles/theme.ts, src/utils/__tests__/clusterUtils.ts, src/utils/clusterUtils.js, testUtils/mockHttpCalls/status.js
Closes https://github.com/giantswarm/giantswarm/issues/12443
In this PR:
* Fix a bug that would make the upgrade cluster modal be in a broken state if an upgrade request failed
* Hide the upgrade cluster modal cancel button when an upgrade request is in progress
* Don't display the `Upgrade Available` button if a cluster is not ready
* Display whether a cluster has an upgrade in progress or not
* Handle cluster condition checks for V4 clusters, too (it was previously working just for V5 ones)
<details>
<summary>Upgrade in progress - Cluster overview</summary>
</details>
<details>
<summary>Upgrade in progress - Cluster detail</summary>
</details>
<details>
<summary>Upgrade in progress - Organization detail</summary>
</details>
=> Prevent upgrade when cluster not ready

__tests__/ClusterManagement.js, src/selectors/releaseSelectors.ts, src/stores/releases/actions.ts, src/stores/releases/reducer.ts, src/stores/releases/types.ts
Fixes giantswarm/giantswarm#12526
This makes the sorted list of release dependant on the available releases which is already filtered for admins/non-admins.
=> Fix empty release rows in cluster creation for non-admins

src/components/Layout.js, src/components/UI/Navigation/OrganizationDropdown.js
Towards: https://github.com/giantswarm/giantswarm/issues/12705 
I noticed what was happening is actually that two route change events were occurring right after one another.
The dropdown menu item is a NavLink that wants to go to "#" after being clicked on.
Let's use the NavLink to bring us home instead.
=> Use the NavLink to go Home.

src/actions/batchedActions.js
Closes https://github.com/giantswarm/giantswarm/issues/12490
Previously, if refreshing the user info, or fetching the installation info failed, the app would be stuck in a loading state. (can be tested easily by trying to use happa locally with VPN turned off)
Now, we redirect the user to the login page and we display this flash message:
=> Redirect user to the login page if initial data fetch fails

.eslintrc.js, src/actions/metadataActions.ts, src/components/AppCatalog/CatalogList/CatalogExternalLink.js, src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesConverter.tsx, src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesInfo.tsx, src/components/Cluster/ClusterDetail/NodePool.tsx, src/components/Cluster/NewCluster/MasterNodes.tsx, src/components/Home/UpgradeNotice.tsx, src/components/UI/Inputs/FileInput.tsx, src/components/UI/Inputs/Input.tsx, src/components/UI/ViewEditName.tsx, src/lib/errors/ErrorReporter.js, src/lib/flashMessage.js
This PR uses the alternative `@typescript-eslint/no-unused-expressions` linter rule, instead of the built-in `no-unused-expressions`, to add support for optional chaining, so we won't need to disable the rule every time.
=> Use alternative unused expressions typescript-eslint rule

src/components/AppCatalog/AppDetail/ClusterPicker.js, src/components/AppCatalog/AppDetail/InstallAppModal.js
Fixes https://github.com/giantswarm/giantswarm/issues/12545
This simply removes the `Next` button from the first page of the app installation modal since it allowed to proceed to the actual app installation page without selecting a cluster.
=> remove 'next' button from install app modal

src/components/AppCatalog/AppDetail/InstallAppModal.js
As seen on https://gigantic.slack.com/archives/C3MCF5EJK/p1597247224000200
1. Open the app installation modal
<details>
<summary>2. Press on 'Choose file' and select a file</summary>
</details>
<details>
<summary>3. Press on 'Choose file' again</summary>
</details>
<details>
<summary>4. Press 'Cancel'</summary>
</details>
<details>
<summary>5. The input should now be empty again</summary>
</details>
<details>
<summary>6. Now if you check your console, you'll see the error. Also, if you now install the app, and check its details afterwards, you'll see that the app has config values set up, even though the file showed up as empty before</summary>
</details>
=> Fix error on app values/secrets upload cancellation

src/components/Home/ClusterDashboardItem.js, src/components/UI/ErrorFallback.tsx, src/components/UI/ErrorText.tsx, src/components/shared/ErrorBoundary.tsx
This PR adds an ErrorBoundary component which can be used to wrap Components and display a fallback.
Its first use is wrapping ClusterDashboardItems and displaying a fallback component like this:
=> add ErrorBoundary around Clusterlist to catch Errors there

src/components/Cluster/ClusterDetail/ClusterApps.js
As seen on https://gigantic.slack.com/archives/C13MG9F0W/p1597918009003000
This PR makes the `nginx-ingress-controller` app visible under the `Installed Apps` section, if it's installed and if ingress controllers are optional in the cluster's release version.
=> customer bug: nginx IC is not visible under installed apps, if ICs are optional

package.json, src/lib/OAuth2/OAuth2.ts, src/lib/OAuth2/OAuth2CustomMetadata.ts, src/lib/OAuth2/OAuth2User.ts, yarn.lock
Part of the larger #1547
This includes a wrapper around the `oidc-client-js` library, so we could replace the internal library at some point, and not have to cry about it.
=> [CP Auth 2/5]: Add OIDC login helpers

package.json, src/components/Auth/AdminLogin.tsx, src/components/Cluster/ClusterDetail/__tests__/UpgradeClusterModal.tsx, src/components/index.tsx, src/model/clients/CPClient.ts, src/model/clients/FetchAdapter.ts, src/model/clients/GenericResponse.js, src/model/services/controlplane/appcatalogs/appcatalogs.ts, src/model/services/controlplane/appcatalogs/types.ts, src/model/services/controlplane/base.ts, src/reducers/types.ts, src/selectors/ingressTabSelectors.ts, src/stores/appcatalog/__tests__/actions.ts, src/stores/appcatalog/actions.ts, src/stores/appcatalog/reducer.ts, src/stores/appcatalog/types.ts, src/stores/configureStore.ts, webpack.common.js, yarn.lock
Part of the larger #1547
This PR adds the CP client library, client and handlers.
It also links the newly created types throughout the app.
=> [CP Auth 3/5]: add CP client and catalog service

src/components/Cluster/ClusterDetail/NodePool.tsx, src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
As seen on https://github.com/orgs/giantswarm/projects/85#card-40662167
This PR:
* disables the NP `appear` transition (which is executed when the component is rendered).
* makes the `enter` transition quicker (when a node pool is created)
* adds an `exit` transition (when a node pool is deleted)
* fixes a bug that would make the `exit` transition display a loading spinner fading out, instead of the actual node pool
GIFs don't do this justice. Please take a look 👍
=> Remove NP appear transitions and make enter and exit transitions quicker

src/components/Cluster/ClusterDetail/RegionAndVersions.js, src/components/Home/ClusterDashboardItem.js, src/components/Home/ClusterStatus.tsx, src/components/Home/UpgradeNotice.tsx, src/components/Home/__tests__/ClusterStatus.tsx, src/components/Organizations/Detail/View.js
Closes https://github.com/giantswarm/giantswarm/issues/12912
This PR:
* Refactors the `UpgradeNotice` component to display multiple cluster statuses.
* Displays a label near clusters that are in creation state.
* Adds a tooltip that explains what all the statuses mean.
* Moves the cluster status icon from near the `Release` column in the Organization detail view, to near the `Name` column.
* Includes tests for all the `ClusterStatus` functionality.
<details>
<summary>Cluster overview - upgrade available (hover)</summary>
</details>
<details>
<summary>Cluster overview - cluster creating (hover)</summary>
</details>
<details>
<summary>Cluster overview - cluster upgrading (hover)</summary>
</details>
<details>
<summary>Cluster details - cluster creating</summary>
</details>
<details> …
=> Add creation in progress label

src/components/Cluster/ClusterDetail/ClusterDetailView.js
This PR lets the ClusterDetailView access all releases instead of just the active ones.
Users with lowered permissions couldn't:
- List preinstalled apps on clusters with inactive releases
- Open the releases information modal on clusters with inactive releases
- Show the kubernetes version in the Giant Swarm release on clusters with inactive releases
=> Supply ClusterDetailView with all releases

src/stores/clusterapps/__tests__/actions.ts, src/stores/clusterapps/actions.ts, yarn.lock
This PR fixes the payload for updating an app in a cluster
(& a change in yarn.lock. Possibly related to recent http-proxy vulnerabilities)
=> Fix updateApp action request payload

helm/happa/ci/default-values.yaml, helm/happa/templates/configmap.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12047
This PR makes use of the `.Values.Installation.V1.GiantSwarm.Happa.EnableUserMonitoring` introduced in https://github.com/giantswarm/installations/pull/1493 to enable RUM.
So far, the fact that an installation is a test installation also enabled user monitoring. As we want to roll it out to more non-testing installations, we need a dedicated switch.
=> Use EnableUserMonitoring setting to enable user monitoring

src/actions/nodePoolActions.js, src/components/Cluster/ClusterDetail/AddNodePool.js, src/components/Cluster/ClusterDetail/NodePool.tsx, src/components/Cluster/ClusterDetail/NodePoolScaling.tsx, src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js, src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js, src/components/Cluster/ClusterDetail/V5ClusterDetailTableNodePoolScaling.tsx, src/shared/constants/index.ts
This PR:
* adds support for node pool autoscaling on Azure V5
* displays the actual error message when a node pool name change fails
The behaviour is the same as on AWS, so no logic changes.
=> azure v5: Enable node pool autoscaling

src/components/AppCatalog/AppList/AppListInner.js, src/components/AppCatalog/AppList/AppListItems.js, src/components/shared/VirtualizedScrollableGrid.js
If you use a screen that is not very wide, this is what currently happens when clearing the search bar contents quickly after typing:
=> Fix breaking app catalog layout after clearing the search bar

package.json, yarn.lock
Allows us to fix https://snyk.io/vuln/SNYK-JS-UAPARSERJS-610226
=> Force 'ua-parser-js' version v0.7.22 to fix vulnerability

package.json, yarn.lock
This is so we could fix https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311
=> Force 'node-fetch' version v2.6.1 to fix vulnerability

src/components/Home/ClusterStatus.tsx
This PR changes the icon shown for a cluster in creation.
The new cogs icon fits our other icons in use better and can also be used to indicate all sorts of infrastructure changes in progress (scaling, upgrades, deletion).
=> Change icon for cluster creation in progress

scripts/rum.inc.html
For https://github.com/giantswarm/giantswarm/issues/12047
This PR removes Google Analytics tracking code, which has been included temporarily for test purposes.
=> Remove Google Analytics tracking code used in test installations

src/components/Cluster/ClusterDetail/RegionAndVersions.js, src/components/Home/ClusterDashboardItem.js
Closes https://github.com/giantswarm/giantswarm/issues/13478
This PR adds the k8s version number to the cluster overview.
=> Show kubernetes version in cluster overview

src/@types/appcatalogs.d.ts, src/@types/v4clusters.d.ts, src/components/Cluster/ClusterDetail/ClusterApps.js
Closes https://github.com/giantswarm/giantswarm/issues/12568
This PR accounts for having a `null` label map in the app spec. It also defines other label maps as nullable, since that's how they behave in Go, and how they are serialized and passed around.
=> Allow having apps defined without labels

helm/happa/templates/configmap.yaml, helm/happa/templates/deployment.yaml
Happa fails to be installed on AWS tenant cluster due to missing Azure configuration (which should not be expected on AWS)
=> Do not check non-related to cloud capabilities

src/components/Cluster/ClusterDetail/RegionAndVersions.tsx, src/components/Home/ClusterDashboardItem.js, src/components/UI/KubernetesVersionLabel.tsx
Extracts the Kubernetes version label into a component. Also reduces the amount of information given to the minor version, cuts off the patch version (in the cluster overview only).
Preparation for https://github.com/giantswarm/giantswarm/issues/13439
=> Extract k8s version into component, remove patch level

src/components/Cluster/ClusterDetail/AddNodePool.js, src/components/Cluster/ClusterDetail/NodePoolScaling.tsx, src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js, src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js, src/components/Cluster/ClusterDetail/V5ClusterDetailTableNodePoolScaling.tsx, src/components/Cluster/ClusterDetail/WorkerNodesAWS.js, src/shared/constants/index.ts, src/stores/nodepool/utils.ts
Towards https://github.com/giantswarm/giantswarm/issues/13649
This disables node pool autoscaling for Azure V5 clusters. We decided to postpone this feature.
Also, with the changes in this PR, turning autoscaling back on should be just a matter of adding 2 lines of code.
<details>
<summary>Node pools list</summary>
</details>
<details>
<summary>Node pool creation form</summary>
</details>
=> azure v5: disable node pool autoscaling

src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js, src/stores/cluster/actions.ts, src/utils/__tests__/errorUtils.ts, src/utils/errorUtils.ts
As seen on https://gigantic.slack.com/archives/CNUDS3AMU/p1602056757165900
This makes sure that the error received from the API is visible in the UI. Especially useful when a cluster upgrade is blocked by a webhook, and you have no idea why.
I also wrote an utility function that we can reuse for getting the error message from other requests.
=> Display full cluster update error details

src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx, src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
Closes https://github.com/giantswarm/giantswarm/issues/13589
Listed this as a `dev-change`, because it is only relevant for GS Staff, as this behaviour was already present for non-GS staff.
This PR makes the latest active version be selected by default in the cluster creation form, regardless if you are an admin or not.
=> Automatically enable the latest active version, even for admins

src/components/Cluster/ClusterDetail/NodesRunning.tsx
When you have a cluster ready, with no node pools (and therefore no nodes), the node count display is broken.
=> Worker node counter is broken when there are no node pools

src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx, src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts, src/stores/cluster/__tests__/selectors.ts, src/stores/cluster/__tests__/utils.ts, src/stores/cluster/selectors.ts, src/stores/cluster/utils.ts, src/stores/releases/__tests__/utils.ts, src/stores/releases/utils.ts
Semver pre-releases can have the following formats:
* 1.0.0-alpha (or beta, rc1 etc.)
* 1.0.0+buildmetadata
* 1.0.0-alpha+buildmetadata
This PR:
* Blocks pre-release versions from being selected by default when you're creating a new cluster.
* Prevents upgrades from regular versions to pre-release versions.
* Moves cluster utils tests to the correct folder.
=> Discourage the usage of pre-release versions

src/index.html
This PR attempts to change the loading behaviour so that the final background color of the viewport is set as early as possible, preventing a white flash during loading.
Note that this uses the background color of the login page, which is darker than the app's normal background
Timing here based on webpagetest.org with "cable" as network bandwith (5 MBit/Sec).
Results: https://www.webpagetest.org/result/201016_DiYT_ae9f28b21731b39e2c4c287dfa1455ba/
Results: https://www.webpagetest.org/result/201019_DiDF_5a79b726d23f0ad1c5c95755a8cebb8c/
=> Set background color early

src/components/AppCatalog/AppDetail/InstallAppModal.js, src/components/Home/ClusterDashboardItem.js, src/components/Organizations/Detail/Detail.js, src/components/UI/OrganizationList/OrganizationList.js, src/lib/__tests__/helpers.ts, src/lib/helpers.tsx, src/stores/cluster/actions.ts, src/stores/cluster/selectors.ts, src/stores/nodepool/actions.ts, src/stores/organization/__tests__/utils.ts, src/stores/organization/selectors.ts, src/stores/organization/utils.ts
Related to https://github.com/giantswarm/api/pull/1159
Because organization IDs are now normalized in the API cluster lister, some calls and checks no longer work like before (e.g. we filter clusters using the `owner` reference field, to see if any of them belong to a specific organization).
To achieve this, we now get the original organization ID from the global state, based on the cluster `owner` reference, in order to get the ID with the proper casing.
=> Select the organization ID from storage before comparing it to the cluster owner reference

src/stores/appcatalog/actions.ts
The Helm Stable catalog is going EOL, but a mirror will be kept up at a new url.
Unfortunately that new URL doesn't really play nice with our assumptions, so have to add a special case here in Happa. 
Towards: https://github.com/giantswarm/giantswarm/issues/9985
See also: https://gigantic.slack.com/archives/C76JX6YLQ/p1604058274081800
Fyi @rossf7
=> Hack the catalog urls for helm stable special case.

src/components/UI/AppDetails/ChartVersionsTable.js
Related to https://github.com/giantswarm/happa/pull/1957
In the `Other versions` tab, currently we show `undefined` if the charts provide no appVersion.
This PR changes this to display `unknown`.
=> Display unknown if appVersion not given

src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
Fixes: https://github.com/giantswarm/giantswarm/issues/13774
This was an Edge only bug. My approach was to set the widths to something reasonable to avoid things recalculating. Exactly why it recalculated in such way that things would wrap is not totally clear to me.
=> Lock down the widths a bit so they don't recalculate.

src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
Closes https://github.com/giantswarm/giantswarm/issues/14201
This doesn't seem to have any bad impact on how the release version selector on the cluster creation page looks, so it's safe.
**Before**
**After**
=> Remove minimum width from the release selector component

src/components/Cluster/ClusterDetail/UpgradeClusterModal.js, src/components/Cluster/ClusterDetail/__tests__/UpgradeClusterModal.tsx, src/styles/_base.sass
Towards https://github.com/giantswarm/giantswarm/issues/13348
- Add target version number to dialog title
- Link from step 1 to upgrade checklist
- Make title in step 2 shorter ("Inspect Changes" -> "Changes", "version" -> "v")
- Renamed "Changes" sub-headline to "Details", added spacing above
<details>
<summary>Show screenshot of current behavior</summary>
</details>
<details>
<summary>Show screenshot of current behavior</summary>
</details>
=> UX enhancements in the "About upgrading" dialog

src/@types/clusters.d.ts, src/components/Cluster/ClusterDetail/ClusterDetailView.js, src/stores/batchActions.ts, src/stores/cluster/actions.ts, src/stores/cluster/reducer.ts, src/stores/cluster/types.ts, src/stores/cluster/utils.ts
Towards https://github.com/giantswarm/giantswarm/issues/14122
This PR improves the UI experience on the Azure upgrade from V4 to V5:
* The cluster details UI is automatically changed to the one that includes node pools during the upgrade
* The cluster information in the cluster overview is no longer lost during the upgrade (e.g. the cluster name is no longer set to the cluster ID)
Bonus: Clusters that don't have any conditions are no longer considered in creation.
=> Improve upgrade UI interaction during Azure v4 to v5 cluster upgrade

src/components/Footer/Footer.tsx, src/components/Footer/FooterUtils.ts
Closes https://github.com/giantswarm/giantswarm/issues/13817
With this PR we no longer display that there's a new version of `happa` available if there is no user logged in.
If a new version becomes available before the user logs in, the notification would be displayed after the user logs in.
=> Only display that a new happa version is available if a user is logged in

src/components/UI/VersionPicker/VersionPicker.tsx, src/components/UI/VersionPicker/VersionPickerUtils.ts, src/components/UI/VersionPicker/__tests__/VersionPicker.js
Closes https://github.com/giantswarm/giantswarm/issues/14253
Bonus: Some cleanup in the `VersionPicker` component.
**Before**
**After**
=> Clean up version picker component and truncate values

src/components/Footer/FooterUtils.ts
For https://github.com/giantswarm/giantswarm/issues/3870
For v1.0.4 this would be https://docs.giantswarm.io/changes/web-ui/happa/v1.0.4/
=> Let the 'Release notes' link in the footer point to the docs.giantswarm.io release page

src/components/AppCatalog/AppDetail/AppDetail.js, src/components/AppCatalog/AppDetail/ClusterPicker.tsx, src/stores/main/reducer.ts, src/stores/main/types.ts, testUtils/preloginState.js
As seen in https://github.com/orgs/giantswarm/projects/85#card-49438733
Nothing too special, just me getting punched by JS.
With this occasion, I also changed the type of the selected cluster ID in the global store.
=> Fix cluster not being selected for app installation

src/components/Cluster/NewCluster/CreateNodePoolsCluster.js, src/shared/constants/realUserMonitoring.ts
Towards: https://github.com/giantswarm/giantswarm/issues/12101 and https://github.com/giantswarm/giantswarm/issues/13842
This PR has 2 goals:
1. Remove the usage of the deprecated `masters` field in the v5/cluster/create API call and replace it with the new `master_nodes` field.
2. Allow more fine grained control over the availability zone that master nodes should be put in for an azure cluster (the same we already do for node pools).
The AZ selection before my change was:
My proposed change makes it look like this:
I tested this as best as I could but I please bear in mind I am not fluent with TypeScript
=> Added support for selecting no availability zones for azure masters

src/components/AppCatalog/AppDetail/InstallAppModal.js, src/components/AppCatalog/AppDetail/__tests__/InstallAppForm.js, src/components/UI/VersionPicker/__tests__/VersionPicker.js
Hi @pipo02mix , here's what would need to change to make sure the useEffect block isn't being called all the time, and thus resetting the state of namespace back to `kube-system`
=> Fix nginx limitation removal

src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js, src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolAZSelection.tsx
When creating node pools in regions that do not support AZs (on azure) there is only one option for the availability zone choice: "Not Specified".
This PR hides the other options in this scenario.
=> Hide availability zone options when location does not support AZs

src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
Stops happa from crashing when cluster details cannot be fetched for whatever reason.
Fixes exception report:
```
TypeError: Cannot convert undefined or null to object
at keys (webpack:///./src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx:73:26)
```
=> Fix a crash when labels is undefined.

src/@types/appcatalogs.d.ts, src/components/AppCatalog/AppDetail/AppDetail.js, src/stores/appcatalog/__tests__/actions.ts, src/stores/appcatalog/actions.ts, src/stores/appcatalog/selectors.ts
We've changed the location of the app README url to the 'annotations' block in Chart.yaml instead of the 'sources' array.
Happa should be backwards compatible for a while though. This PR lets Happa also check for README's in the "application.giantswarm.io/readme" annotation, with a fallback to the original 'sources' location.
https://github.com/giantswarm/giantswarm/pull/13982
fyi @cokiengchiara
=> Support readme urls in annotations as well as sources of an app's Chart.yml.

src/stores/cluster/reducer.ts
It seems that if you try to upgrade a cluster, even if the cluster upgrade request fails, the cluster is still stuck with the `Awaiting upgrade` status. This PR fixes that.
=> Fix cluster stuck on 'Awaiting upgrade' after the upgrade request failed

src/components/Cluster/ClusterDetail/ClusterApps.js, src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx, src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModal.js, src/components/UI/KubernetesVersionLabel.tsx, src/components/UI/__tests__/KubernetesVersionLabel.tsx, src/stores/releases/__tests__/utils.ts, src/stores/releases/utils.ts
Closes https://github.com/giantswarm/giantswarm/issues/14987
This PR adds clarification regarding the `EOL`( end of life) marker displayed next to a Kubernetes version. This should help avoid the impression that the Giant Swarm tenant cluster release is EOL.
The wording change makes the function specific to Kubernetes, so I renamed it from `getReleaseEOLStatus` to `getKubernetesReleaseEOLStatus`.
=> Clarify that the EOL tag is associated with the Kubernetes release

scripts/webpack/getServiceURL.js
This updates happa to the latest behaviour of `opsctl show installation`, which prints some variables we need with mixed case names.
=> Change variables to uppercase

__tests__/V4AzureClusterManagement.js, src/components/UI/NumberPicker.js, src/components/shared/__tests__/NodeCountSelector.js
Reproduce the problem:
- Enter the cluster creation page
- Select a release version that supports node pool autoscaling
- Try to create a new node pool, set the minimum scaling to `3`, and select the text in the maximum input, and try to enter `20`
- Notice that the value is `30` instead of `20`
With this PR, we let the user enter the value they want via keyboard. But don't worry, if the user tries to enter an invalid value, the input will be marked as invalid, and a validation error will be shown. This improves UX by letting the user enter the value they want.
cc @whites11 for extra details about the issue
Affected components:
- Node pool scaling (both autoscaling on or off)
- Node pool availability zone count
- V4 cluster creation availability zone counter
=> Improve number picker UX to allow the user enter the value they want

src/lib/helpers.tsx
This prevents the functions from breaking when passing `Date` objects to them (which occasionally happened in the cluster overview, after switching to `date-fns`)
=> Allow passing date objects to date formatting utilities

src/components/Apps/AppsList/AppsList.tsx, src/components/Apps/AppsList/Facets.tsx, src/components/Apps/AppsList/SortingDropdown.tsx, src/components/Apps/AppsList/Toolbar.tsx, src/components/UI/AppList/Icon.tsx, src/components/UI/Inputs/Checkbox.js, src/components/UI/Inputs/Facets.tsx, src/components/UI/Inputs/Input.tsx
This adds the remaining UI elements and controls to the new App listing page.
Not hooked up to any actual data yet. Just the UI elements, and a bit of the presentational logic.
Icons will have to have transparent backgrounds, but used what we have for now.
=> Add a search query input, sorting dropdown, and an area for facets

src/components/UI/Controls/ExpandableSelector/Items.tsx
This probably occured as a result of the button refactor
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Fix release selector buttons being cut off

src/components/UI/Inputs/NumberPicker.js, src/components/shared/NodeCountSelector.js, src/components/shared/__tests__/NodeCountSelector.js
This was a problem found by the app destroyer (@whites11).
Let's say you wanted to create a node pool, and you wanted to set up the autoscaling configuration. Let's say you don't want any autoscaling, and you want `2` nodes set to both minimum and maximum.
If you set the `MIN` value first, and the `MAX` value second, everything's perfect. However, if you set the `MAX` value first, and then the `MIN` value, you'll still see the validation error near the `MAX` input, and you wouldn't be able to create your node pool, even though the values are valid (theoretically).
This PR addresses the issue by re-validating the number pickers if their minimum or maximum limits change.
=> Allow setting node counter values in any order

src/components/AppCatalog/AppCatalog.js, src/components/Apps/AppsList/AppsList.tsx, src/components/Apps/AppsList/utils.tsx, src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.stories.tsx, src/components/UI/Display/Apps/AppList/AppsListPage.stories.tsx, src/components/UI/Display/Apps/AppList/Toolbar.tsx, src/stores/appcatalog/actions.ts, src/stores/appcatalog/types.ts, src/stores/batchActions.ts
Now enabling a catalog on actually causes the catalog index to load. 
I don't load the helm-stable catalog on startup, but all the other available catalogs I do.
Also fixes some unrelated linting warnings.
=> Catalog facets part 2

src/components/UI/Inputs/CurrencyInput/index.tsx
<details>
<summary>Chrome</summary>
</details>
<details>
<summary>Firefox</summary>
</details>
<details>
<summary>Safari</summary>
</details>
=> Make currency input have consistent layout on all major browsers

src/@types/appcatalogs.d.ts, src/components/Apps/AppsList/AppsList.tsx, src/components/UI/Display/Apps/AppList/App.tsx, src/components/UI/Display/Apps/AppList/AppsListPage.tsx, src/stores/appcatalog/__tests__/actions.ts, src/stores/appcatalog/actions.ts, src/stores/appcatalog/selectors.ts, src/stores/appcatalog/types.ts
Trying to keep PR's small, this one focuses on the selector used to get all the apps that belong to the catalogs that the user selected in the facets.
I renamed `IAppCatalogApp` to `IAppCatalogAppVersion`, and created a new `IAppCatalogApp` interface.
What used to be `IAppCatalogApp` was actually just a single version of an app. Catalogs contain all known versions of an app, so I created a new interface which kind of wraps all the known versions and surfaces the name and other details relevant for rendering in the AppList component.
=> Wire apps into the applist

src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js, src/components/Cluster/ClusterDetail/AddNodePool/__tests__/AddNodePool.tsx
Towards https://github.com/giantswarm/giantswarm/issues/15310
With this change, we let the API default the value it wants when using on-demand as maximum price, instead of setting the value to `0`.
=> Rely on API to set the default max price for spot instances on Azure

src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js
Closes https://github.com/giantswarm/giantswarm/issues/15557
This PR the warning saying `We recommend that you run clusters with at least 3 workers`, when trying to set a node pool's minimum scale to a value lower than `3`.
=> Remove the warning regarding runnin minimum 3 nodes in a pool

src/@types/clusters.d.ts, src/components/Home/ClusterDashboardItem.js, src/components/Home/__tests__/ClusterStatus.tsx, src/stores/cluster/__tests__/utils.ts, src/stores/cluster/reducer.ts
Fixes an exception I've noticed recently.
It looks like the delete_date of a cluster can be "Invalid Date" for a while.
=> Fix a crash when delete dates are somehow invalid

src/components/Apps/AppDetail/AppDetail.tsx, src/components/Apps/AppsList/utils.tsx, src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx, src/components/UI/Display/Apps/AppList/App.tsx, src/components/UI/Display/Apps/AppList/CatalogLabel.tsx
This adds a little tooltip with the description of the catalog for each facet. 
(I don't really like the UX of this btw, ping @marians, this was specced but now that I see it in action im not sure it feels that great. if you want me to deploy it somewhere so you can see, let me know)
It also adds the managed label to the giant swarm catalog, currently the logic for determining that is just based on the name of the catalog. Eventually it will be a specific label on the AppCatalogCR, but we haven't specced that and agreed on it yet.
&
=> Managed app label & Catalog description tooltip

src/components/UI/Display/Apps/AppList/App.tsx, src/components/UI/Display/Apps/AppList/AppIcon.tsx
[When I made all the app icons myself](https://github.com/giantswarm/web-assets/tree/master/assets/app-icons/1/png), I made two versions, for dark and light backgrounds.
Now that we're switching, I'd like it to already look good, instead of forcing all apps to change the URL and release a new version. This way we let Happa detect apps which would have a dark-bg version of their logo, and use that instead
=> Use dark bg app icons if possible

src/components/Apps/AppsList/AppsList.tsx, src/stores/appcatalog/selectors.ts
This makes sure that when the helm catalog takes a while to load, the apps listing page still updates eventually.
=> Make sure toggling helm catalog the first time works.

src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairSuccessTemplate.tsx, src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx, src/components/Cluster/ClusterDetail/KeypairCreateModal/__tests__/KeyPairCreateModal.tsx, src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/TextArea/__tests__/index.tsx, src/components/UI/Inputs/TextArea/index.tsx, src/components/UI/Inputs/TextArea/stories/Disabled.tsx, src/components/UI/Inputs/TextArea/stories/Error.tsx, src/components/UI/Inputs/TextArea/stories/Help.tsx, src/components/UI/Inputs/TextArea/stories/Info.tsx, src/components/UI/Inputs/TextArea/stories/Label.tsx, src/components/UI/Inputs/TextArea/stories/Simple.tsx, src/components/UI/Inputs/TextArea/stories/TextArea.stories.tsx, src/styles/theme.ts
Towards giantswarm/giantswarm#11004 and towards the grommet migration
This PR includes a new `textarea` input. There were no components that I could add it to. There was one old usage of `textarea` in the keypair creation success modal, which was also not displayed correctly, and I replaced it with the `FileBlock` component.
<details>
<summary>With label</summary>
</details>
<details>
<summary>With error</summary>
</details>
<details>
<summary>With info message</summary>
</details>
<details>
<summary>With help message</summary>
</details>
<details>
<summary>Disabled</summary>
</details>
<details>
<summary>Keypair creation success modal - BEFORE</summary>
</details>
<details>
<summary>Keypair creation success modal - AFTER</summary>
</details>
=> Create textarea input

src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstancesAzure.tsx, src/components/UI/Inputs/CurrencyInput/__tests__/CurrencyInput.tsx, src/components/UI/Inputs/CurrencyInput/__tests__/__snapshots__/CurrencyInput.tsx.snap, src/components/UI/Inputs/CurrencyInput/index.tsx, src/components/UI/Inputs/CurrencyInput/stories/Constraints.tsx, src/components/UI/Inputs/CurrencyInput/stories/Currencies.tsx, src/components/UI/Inputs/CurrencyInput/stories/FloatValues.tsx, src/components/UI/Inputs/CurrencyInput/stories/Label.tsx, src/components/UI/Inputs/CurrencyInput/stories/Simple.tsx, src/components/UI/Inputs/CurrencyInput/stories/ValidationError.tsx
Towards the `grommet` migration
The new component keeps the same functionality as the old one, but adds consistency to the visual and programmatical interface with the other inputs.
=> Refactor CurrencyInput to use the new input and structure

src/components/UI/Controls/Button/index.js
The Button with style `danger` was 32 pixels high instead of the 34 pixels the other styles use. This PR fixes that.
=> Fix dimensions of Button style "danger"

src/components/index.tsx
Closes https://github.com/giantswarm/giantswarm/issues/16339
This PR turns off the airbrake remote configuration feature. Having this on by default caused requests to an airbrake.io server, which resulted in 403 responses.
=> Disable airbrake remoteConfig to prevent requests to notifier-configs.airbrake.io

src/components/MAPI/organizations/AccessControl/utils.ts, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItem.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItemLoadingPlaceholder.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRolePlaceholder.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleSearchPlaceholder.tsx, src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleList.tsx, src/components/UI/Display/MAPI/AccessControl/types.ts
Towards giantswarm/giantswarm#16306
This PR adds the UI components, UI types, and business logic required to render the role list sidebar in the `Access control` page.
=> access control: add components needed for displaying the role list sidebar

__tests__/Login.tsx, src/model/services/mapi/k8sUrl.ts, src/model/services/mapi/organizations/__tests__/key.ts, src/model/services/mapi/organizations/getOrganization.ts, src/model/services/mapi/organizations/index.ts, src/model/services/mapi/organizations/key.ts, src/stores/organization/actions.ts, testUtils/mockHttpCalls/mapiOrganizations.js, testUtils/modelMocks.js
For users logged in through a SSO, we have transitioned to relying on the MAPI for the source of truth for the organisations list.
This adjusts that logic to support the new `ui.giantswarm.io/original-organization-name`
=> Use what's in the ui annotation for org name if it's there.

testUtils/mockHttpCalls/catalogIndex.js
Updates the catalog domain to giantswarm.github.io instead of giantswarm.github.com. Towards giantswarm/giantswarm#15898
=> Update catalog domain to github.io

src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItemLoadingPlaceholder.tsx
Looks like since the role column was made narrower, the loading animation no longer looks like the content.
<details>
<summary>Content</summary>
</details>
<details>
<summary>Loading animation before</summary>
</details>
<details>
<summary>Loading animation after</summary>
</details>
=> access control: fix role loading animation content

src/components/MAPI/organizations/AccessControl/__tests__/index.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx, src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRolePermissions.tsx
Closes https://github.com/giantswarm/giantswarm/issues/16464
With this PR, we now display `All (*)`, instead of `All`, where all verbs are supported for a role, in the `Permissions` tab.
=> access control: display 'All (*)' where all verbs are supported

src/components/MAPI/organizations/AccessControl/utils.ts
Closes https://github.com/giantswarm/giantswarm/issues/16466
With this PR, we now look for the role search query in:
- the role names
- role subjects
- group names
- user names
- service account names
- role permissions
- api groups
- resources
- resource names
Performance is fine at the moment, but as datasets get larger, we will probably have to execute this in a web worker.
=> access control: extend search to look for queries EVERYWHERE

src/components/MAPI/organizations/AccessControl/__tests__/utils.ts, src/components/MAPI/organizations/AccessControl/utils.ts
Closes https://github.com/giantswarm/giantswarm/issues/16467
With this PR we aggregate similar permission verbs (if they have the same API Groups, Resources and Resource Names, the verbs will be shown into a single table row).
Also, as a bonus, we now sort permissions by these fields:
* API Groups
* Resources
* Resource Names
(e.g. if 2 permissions have the same API Group, they will be ordered by `Resources`, and so on)
=> access control: aggregate similar permission rules

src/components/MAPI/organizations/AccessControl/__tests__/index.tsx, src/components/MAPI/organizations/AccessControl/utils.ts, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItem.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx, src/model/services/mapi/rbacv1/types.ts
Closes https://github.com/giantswarm/giantswarm/issues/16463
This PR includes the following:
* Display permission verbs in tooltips in the same order they are displayed in the table
* Fix an error that would be displayed when a `Role`'s `rules` property was `null`.
* Fix a bug that was causing horizontal scroll in the role list when a role had a longer name
* Make the role search input and role items have the same width.
=> access control: various ux improvements and bug fixes

src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx, src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx, src/components/MAPI/organizations/AccessControl/__tests__/index.tsx, src/components/MAPI/organizations/AccessControl/__tests__/utils.ts, src/components/MAPI/organizations/AccessControl/index.tsx, src/components/MAPI/organizations/AccessControl/utils.ts, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectAddForm.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx, src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleDetail.tsx, src/components/UI/Inputs/TextInput/index.tsx, src/components/UI/Inputs/TextInput/stories/Suggestions.tsx, src/components/UI/Inputs/TextInput/stories/TextInput.stories.tsx, src/model/services/mapi/corev1/getServiceAccountList.ts, src/model/services/mapi/corev1/index.ts, src/model/services/mapi/corev1/types.ts, testUtils/mockHttpCalls/corev1/serviceAccounts.ts
Closes https://github.com/giantswarm/giantswarm/issues/16468
This PR includes a bunch of improvements for service account creation (some also apply to subject creation in general):
* you can bind existing service accounts (a new one will only get created if it doesn't exist)
* you get suggestions for existing service account names
* when you remove a service account from a role binding, the `ServiceAccount` resource no longer gets deleted
* you are no longer able to create multiple subjects with the same name at the same time (it resulted in an error)
* fix a subject name parsing bug that would try to bind subjects with empty names (e.g. `test1, ` would bind both `test1`, and ` `)
<details>
<summary>Full suggestion list</summary>
</details>
<details>
<summary>Suggestions based on the text …
=> access control: reuse existing service accounts and display existing ones as suggestions

src/stores/batchActions.ts
This removes an error notification for the case that the user is no longer authenticated, which happens frequently when credentials expire.
=> Remove error notification for expired credentials

src/components/Cluster/ClusterDetail/ClusterApps.js, src/components/MAPI/apps/AppDetailsModal/AppDetailsModalInitialPane.tsx, src/components/MAPI/apps/AppDetailsModal/index.tsx, src/components/MAPI/apps/utils.ts, src/model/services/mapi/applicationv1alpha1/deleteApp.ts, src/model/services/mapi/applicationv1alpha1/getApp.ts, src/model/services/mapi/applicationv1alpha1/getAppCatalogEntryList.ts, src/model/services/mapi/applicationv1alpha1/index.ts, src/model/services/mapi/applicationv1alpha1/key.ts, src/model/services/mapi/applicationv1alpha1/types.ts, src/model/services/mapi/applicationv1alpha1/updateApp.ts
Towards https://github.com/giantswarm/roadmap/issues/328
As with the previous PR with app installation, this one duplicates the existing necessary components, and replaces the REST API logic with the MAPI one.
=> apps: update app configuration via MAPI

package.json, yarn.lock
Pins underscore to mitigate https://snyk.io/vuln/SNYK-JS-UNDERSCORE-1080984
Tested all BootstrapTable instances, seems fine.
=> Pin underscore version to 1.13.1

.circleci/config.yml, README.md
To keep up with upstream, this PR sets the NodeJS version used to v14, which is the current LTS (long term support) version of NodeJS.
=> Set nodeJS version to v14

.github/pull_request_template.md
... to make room for more information in the next steps
Preview:
---
Release notes for happa are generated automatically, based on pull request titles and labels. Please provide a nice title and select the right labels for this PR. Thank you!
Relevant labels are:
- Introduction of a new feature:
- `kind/feature`
- Changes in existing functionality:
- `kind/change`
- `kind/ux-enhancement`
- Soon-to-be removed features:
- `kind/deprecation`
- Removal of a user-facing feature:
- `kind/removal`
- Bugfix:
- `kind/bug`
- Mitigation of security vulnerabilities:
- `kind/security`
PRs with any of these labels will be excluded from the release notes:
- `dependencies` - Updating dependencies
- `kind/dev-change` - Changing development commands, file structure, etc.
- `kind/refactor` - Improving the …
=> Make the PR template more concise

src/lib/OAuth2/OAuth2.ts
I broke this with https://github.com/giantswarm/happa/pull/2430
Turns out that these events still need to be executed, especially when resuming an existing session
=> auth: fix resuming an existing SSO session

src/components/Footer/FooterUtils.ts
Closes https://github.com/giantswarm/happa/issues/2433
Broke this in https://github.com/giantswarm/happa/pull/2393
=> footer: add `v` prefix to the version in the release notes URL

webpack.prod.js
Fixes a problem with missing images, as they were placed in the wrog path under `/www`.
Also consolidates the Sentry ignore configuration in the webpack config.
=> Revert copy path for images

.circleci/config.yml
New orb version required to generate App CR without status in app-collection
=> Update architect-orb to 2.8.0

src/components/MAPI/apps/AppDetailsModal/index.tsx, src/components/MAPI/apps/ClusterDetailApps.tsx
As seen on https://gigantic.slack.com/archives/C010L893ZFW/p1621609237092300
With this change, it doesn't mean if the app has a custom name or not, we will always use the original app name when fetching app catalog entries.
=> Use app name and catalog from app spec

__tests__/AdminLogin.tsx, __tests__/Login.tsx, src/components/Cluster/ClusterDetail/ClusterDetailView.js, src/components/GettingStarted/Steps/InstallIngress.js, src/components/Layout.js, src/shared/featureSupport.ts, src/stores/batchActions.ts
Towards https://github.com/giantswarm/roadmap/issues/328
With this PR we no longer execute the global app-specific requests if they are possible via MAPI (if the user is logged in via SSO and it is not a KVM installation).
=> apps: remove global app-specific requests when MAPI features are supported

src/components/MAPI/apps/AppList/index.tsx, src/components/MAPI/apps/Apps.tsx, src/components/MAPI/apps/AppsProvider.tsx
Closes https://github.com/giantswarm/giantswarm/issues/17361
With this PR, the selected catalogs in the sidebar of the `Apps` page will be persisted between route changes (disclaimer: only if we change routes between the app-specific routes - app list and app details, if we navigate outside of that, the selection will be reset).
=> apps: persist selected catalogs when navigating between app pages

src/components/MAPI/apps/AppList/AppDetail.tsx
As part of the: `can you break happa every day of the week?` challenge
=> apps: use the correct catalog name when installing app in workload cluster

src/components/Footer/FooterUtils.ts, src/stores/metadata/reducer.ts, testUtils/mockHttpCalls/metadata.ts, testUtils/preloginState.js
Closes https://github.com/giantswarm/giantswarm/issues/17418
While the app is loading `/metadata.json`, this version will be invalid
=> Prevent throwing an error if the app metadata is not loaded yet and the footer version is invalid

package.json, yarn.lock
This upgrades the `ws` dependency due to a security vulnerability (https://github.com/advisories/GHSA-6fc8-4gx4-v693)
=> Upgrade ws

src/components/MAPI/apps/__tests__/utils.ts, src/components/MAPI/apps/utils.ts
As seen on https://gigantic.slack.com/archives/CRZN9GLJW/p1622460313091900
=> apps: use the correct chart name when installing an app

src/lib/passageClient.ts
This bug was created during the HTTP Client refactor. As seen on https://gigantic.slack.com/archives/CLPMFRVU6/p1622535930048700
=> Set JSON content type header for Passage requests

src/model/clients/HttpClient.ts, src/model/clients/__tests__/HttpClient.ts
Fixes https://github.com/giantswarm/giantswarm/issues/17524
This PR removes the phrase "This is embarrassing". In a distributed system it's expected that some requests fail, sometimes.
=> Change error message wording

src/components/Cluster/ClusterDetail/URIBlock.js, src/components/GettingStarted/GettingStarted.js, src/components/MAPI/clusters/Cluster.tsx, src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx, src/components/MAPI/clusters/ClusterDetail/index.tsx, src/components/MAPI/clusters/ClusterDetail/utils.ts, src/components/MAPI/organizations/Organization.tsx, src/components/UI/Display/Cluster/ClusterIDLabel/index.js, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverviewDelete.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/index.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/index.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/stories/ClusterDetailWidget.stories.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/stories/Inline.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/stories/Simple.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetKubernetesAPI.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLoadingPlaceholder.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetOptionalValue.tsx, src/components/UI/Display/MAPI/clusters/types.ts, src/components/UI/Inputs/ViewEditName.tsx, src/model/services/mapi/capiv1alpha3/deleteCluster.ts, src/model/services/mapi/capiv1alpha3/getCluster.ts, src/model/services/mapi/capiv1alpha3/index.ts, src/model/services/mapi/capiv1alpha3/key.ts, src/model/services/mapi/capiv1alpha3/updateCluster.ts, src/shared/featureFlags.ts
Towards https://github.com/giantswarm/giantswarm/issues/9077
This PR adds some basic features for the new `Cluster detail` page layout, which uses the Management API for fetching information.
What's in this PR:
- Cluster description renaming
- Cluster deletion (behaves the same as organization deletion)
- Info about clusters (name, description, kubernetes API URL, creation date)
- Cluster details widget (will be used for all the different panes on the page)
The rest will be implemented in next PRs
<details>
<summary>Details</summary>
</details>
<details>
<summary>Deletion confirmation</summary>
</details>
<details>
<summary>Loading animations</summary>
</details>
=> clusters: add a new cluster detail page with basic functionality

src/components/Cluster/ClusterDetail/ClusterDetailView.js, src/components/MAPI/apps/ClusterDetailApps.tsx, src/components/MAPI/apps/ClusterDetailIngress.tsx, src/components/MAPI/clusters/ClusterDetail/index.tsx
This PR adds the `Apps` and `Ingress` tabs to the MAPI cluster detail page. Luckily, these have already been refactored to use the MAPI, so it's just a matter of a few small tweaks
=> clusters: add the Apps and Ingress tabs to the MAPI cluster detail page

src/components/index.tsx, src/shared/constants/realUserMonitoring.ts
With this change, every URI visited in the app will be logged to RUM. So far, only URIs with other RUM events happening were logged.
This gives us more complete information regarding which parts of happa are used.
=> Submit each URI visited to RUM

jsconfig.json, package.json, scripts/swc/PropTypesStripper.ts, scripts/swc/__tests__/PropTypesStripper.ts, src/components/Cluster/ClusterDetail/ClusterDetailView.js, src/components/SignUp/SignUp.tsx, src/components/Users/DeleteUserModal.js, src/components/Users/InviteUserModal/index.js, src/components/Users/UnexpireUserModal.js, src/components/Users/UsersModal.js, src/components/shared/ErrorBoundary.tsx, src/styles/transitions/BaseTransition.tsx, src/styles/transitions/SlideTransition.js, tsconfig.json, webpack.common.ts, webpack.dev.ts, webpack.prod.ts
This PR adds a plugin for the `swc` compiler, which strips react component `propTypes` and removes the `prop-types` import when building the production app. We don't need them because they don't run in production anyway, so they just take up extra code.
The savings are not noticeable (~40 KB), but it was an occasion for me to have some fun with `swc`.
Not all possible scenarios are handled (you can see what's handled in the `PropTypesStripper` test), but all the patterns that we use right now work.
In order to make my job easier, I've changed the code that was not following our current pattern, to have everything working smoothly. 👍🏻
=> Create swc plugin that removes prop types in production builds

src/components/MAPI/clusters/utils.ts, src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx, src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx, src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModalSection.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailStatus.tsx, src/model/services/mapi/releasev1alpha1/key.ts
Towards https://github.com/giantswarm/giantswarm/issues/9077
This PR adds:
* modal that displays the release details when clicking on the release version
* upgrading/upgradable status label/icon
Actually upgrading the cluster (and the upgrade options at the bottom of the release details modal) will be coming in the next PR
<details>
<summary>Upgrade available</summary>
</details>
<details>
<summary>Release details</summary>
</details>
=> clusters: display release details when clicking on release version

src/components/MAPI/clusters/ClusterDetail/index.tsx, src/components/MAPI/keypairs/ClusterDetailKeyPairDetailsModal.tsx, src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx, src/components/MAPI/keypairs/utils.ts, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/shared/Copyable.tsx, src/lib/helpers.tsx
This PR adds a read-only GUI for key pairs. It behaves pretty much like the old one, but you can't create key pairs.
The PR also includes a fix for the `Copyable` component, as well as some keyboard navigation improvements for it.
<details>
<summary>Random keypair list</summary>
</details>
<details>
<summary>Some details</summary>
</details>
<details>
<summary>Nothing to display</summary>
</details>
=> clusters: add key pairs tab for the MAPI cluster detail page

src/components/MAPI/clusters/ClusterDetail/utils.ts, src/components/MAPI/clusters/utils.ts, src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx, src/components/MAPI/releases/ClusterDetailUpgradeModal.tsx, src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx, src/components/MAPI/releases/__tests__/utils.ts, src/components/MAPI/releases/utils.ts, src/components/UI/Display/MAPI/releases/ClusterDetailReleaseDetailsUpgradeOptions.tsx, src/components/UI/Display/MAPI/releases/ClusterDetailUpgradeModalChangelog.tsx, src/components/UI/Display/MAPI/releases/ClusterDetailUpgradeModalDisclaimer.tsx, src/components/UI/Display/MAPI/releases/types.ts, testUtils/mockHttpCalls/releasev1alpha1/releases.ts
Closes https://github.com/giantswarm/giantswarm/issues/9077
This PR adds all the upgrade logic necessary for the MAPI cluster details page. This means:
- The upgrade button (visible when the cluster is done creating, or when it's not already upgrading)
- The upgrade modal
- Disclaimer pane (saying that an upgrade can break your loved cluster)
- Changelog pane (what changed between the current version and the version you're trying to upgrade to)
- The supported releases section in the release details modal
The look and feel should be 95% the same as the current GS API implementation, with a few improvements.
Also, please take a look at the PR comments to find out more about the implementation details.
<details>
<summary>Upgrade button</summary>
</details>
<details>
<summary>Disclaimer …
=> clusters: add support for upgrading clusters using the MAPI cluster detail page

src/components/MAPI/clusters/ClusterDetail/index.tsx, src/components/MAPI/types.ts, src/components/MAPI/utils.ts, src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/WorkerNodesAzureMachinePoolSpotInstances.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/types.ts, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/workernodes/styles.tsx, src/components/shared/Copyable.tsx, src/model/services/mapi/capiv1alpha3/exp/index.ts, src/model/services/mapi/capiv1alpha3/exp/key.ts
This PR adds the `Worker nodes` tab to the new MAPI Cluster detail UI. It behaves mostly like the old one, with an exception: the node pool name can now be copied to clipboard.
There is some stuff missing currently:
- the `Actions` button on the right of each node pool row. This will be added together with node pool renaming.
- a placeholder for when are no node pools. This will be added with node pool creation.
<details>
<summary>Some node pools sitting in a tree</summary>
</details>
=> clusters: add the worker nodes tab and the list of node pools

src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/utils.ts, src/components/UI/Controls/DropdownMenu.js, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx, src/components/UI/Inputs/ViewEditName.tsx, src/components/UI/__tests__/ViewEditName.js, src/model/services/mapi/capiv1alpha3/exp/getMachinePool.ts, src/model/services/mapi/capiv1alpha3/exp/index.ts, src/model/services/mapi/capiv1alpha3/exp/updateMachinePool.ts
This PR adds support for updating a node pool's description.
<details>
<summary>The actions button</summary>
</details>
<details>
<summary>Updating the description</summary>
</details>
=> clusters: add support for updating node pool descriptions via the MAPI cluster detail page

src/components/MAPI/clusters/utils.ts, src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts, src/components/MAPI/types.ts, src/components/MAPI/utils.ts, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItemDelete.tsx, src/components/MAPI/workernodes/utils.ts, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx, src/model/services/mapi/capiv1alpha3/exp/deleteMachinePool.ts, src/model/services/mapi/capiv1alpha3/exp/index.ts
This PR includes the node pool deletion functionality in the MAPI `Cluster detail` page. It also includes a slight change that lets us display deleting node pools in the UI.
Same as with clusters, deleted node pools appear at the bottom.
<details>
<summary>Delete confirmation</summary>
</details>
<details>
<summary>Node pool has been deleted</summary>
</details>
=> clusters: add support for node pool deletion from the MAPI cluster detail page

src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItemScale.tsx, src/components/MAPI/workernodes/utils.ts, src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx, src/components/shared/NodeCountSelector.js
This PR adds support for scaling node pools in the MAPI cluster detail page. The implementation is slightly different compared to deletion, as the logic for scaling is not included in the `WorkerNodesNodePoolItem` component. I will update the deletion component, for consistency, in a separate PR.
<details>
<summary>no value changed</summary>
</details>
<details>
<summary>increased min by 2</summary>
</details>
<details>
<summary>made max lower than current number of nodes</summary>
</details>
=> clusters: add support for node pool scaling from the MAPI cluster detail page

.circleci/config.yml, src/components/Cluster/ClusterDetail/KeypairCreateModal/Utils.ts, src/components/Footer/Footer.tsx, src/components/Footer/FooterUtils.ts, src/components/Footer/__tests__/Footer.ts, src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js, src/index.ejs, src/shared/constants/index.ts
Towards https://github.com/giantswarm/giantswarm/issues/16699
This PR removes all user-facing strings "happa" and replaces them with "web interface".
=> Replace 'happa' with 'web interface'

src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx, src/components/Cluster/ClusterDetail/AppDetailsModal/YAMLFileUpload.tsx, src/components/MAPI/apps/AppInstallModal.tsx
With this PR we turn off the error notification (submission to Sentry) for errors happening if a user tries uploading an invalid values.yaml file.
=> Avoid error notification for invalid app values file

src/components/Cluster/AZSelection/AZSelection.tsx, src/components/Cluster/AZSelection/AZSelectionAutomatic.tsx, src/components/Cluster/AZSelection/AZSelectionCheckbox.tsx, src/components/Cluster/AZSelection/AZSelectionManual.tsx, src/components/Cluster/AZSelection/AZSelectionNotSpecified.tsx, src/components/MAPI/__tests__/utils.ts, src/components/MAPI/utils.ts, src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx, src/components/MAPI/workernodes/WorkerNodesCreateNodePoolAvailabilityZones.tsx, src/components/MAPI/workernodes/patches.ts, src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabel.js, src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/RadioInput/index.tsx
This PR adds support for setting availability zones when creating node pools. It uses the same underlying components as the current GS API implementation. However, I've made some improvements in how those components behave (consistent font sizes, improved keyboard navigation).
<details>
<summary>Automatic AZ selection</summary>
</details>
<details>
<summary>Manual AZ selection</summary>
</details>
<details>
<summary>Not specified selection</summary>
</details>
=> clusters: add support for setting AZs when creating NPs via the MAPI cluster detail page

src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js, src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx, src/components/MAPI/workernodes/WorkerNodesCreateNodePoolScale.tsx, src/components/MAPI/workernodes/patches.ts, src/components/MAPI/workernodes/utils.ts, src/components/UI/Inputs/NumberPicker/index.tsx, src/components/shared/NodeCountSelector.js
No fancy stuff here, this allows us to set node pool scaling when creating node pools via the MAPI cluster details page.
<details>
<summary>The form with the new option</summary>
</details>
=> clusters: add support for configuring scaling when creating NPs via the MAPI cluster detail page

src/stores/cluster/__tests__/selectors.ts, src/stores/cluster/selectors.ts
As seen on https://gigantic.slack.com/archives/C7865GLSY/p1625574670362400
This is a left-over from the days when we had the `Change version` button in the `Upgrade cluster` modal. It was then possible for admins (GS staff) to see the `Upgrade available` warning for inactive/pre-release versions, in order to test upgrades on testing installations, or execute upgrades to pre-release versions on the customers' behalf.
Now, as we have upgrading to beta versions (or inactive versions) available through the `Release details` modal, it is no longer necessary to display the warning (as it might confuse users).
To be clear, this PR removes the ability of admins to see the `Upgrade available` warning when newer versions are inactive or pre-releases.
=> Stop displaying inactive versions as upgradable for admins

src/components/MAPI/clusters/Cluster.tsx, src/components/MAPI/clusters/GettingStarted/GettingStartedPlatformTabs.tsx, src/components/MAPI/clusters/GettingStarted/GettingStartedProvider.tsx, src/components/MAPI/clusters/GettingStarted/index.tsx, src/components/MAPI/utils.ts, src/components/UI/Display/Documentation/Styles.js, src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedGetAccess.tsx, src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedInstallIngress.tsx, src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedNavigation.tsx, src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedNextSteps.tsx, src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedOverview.tsx, src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedSimpleExample.tsx, src/components/shared/Tabs/index.tsx, src/lib/blog.ts
Closes https://github.com/giantswarm/giantswarm/issues/17531
This PR adds the MAPI-specific getting started guide for clusters.
The information displayed is *almost* the same as the GS API one. The difference is that the MAPI one doesn't have the alternative keypair creation method (since it is unsupported via MAPI at the moment).
Implementation wise, the new MAPI-specific components are brand new, and they use `grommet` for styling (the old mostly used SASS and were dependent on the clusters coming from the global state).
> ⚠️  In the screenshots the cluster base URL includes `localhost`. This is not the case when deployed in production.
<details>
<summary>Overview</summary>
</details>
<details>
<summary>Configure kubectl</summary>
</details>
<details>
<summary>Install ingress</summary> …
=> clusters: add getting started guide specific for MAPI clusters

src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js, src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstancesAzure.tsx, src/components/Cluster/ClusterDetail/AddNodePool/__tests__/AddNodePool.tsx, src/components/Cluster/ClusterDetail/NodePoolScalingSpotInstancesDetails.tsx, src/components/Cluster/ClusterDetail/V5ClusterDetailTableSpotInstancesTab.tsx, src/components/Cluster/ClusterDetail/__tests__/NodePoolScaling.tsx, src/components/Cluster/ClusterDetail/__tests__/V5ClusterDetailTableNodePoolScaling.tsx, src/components/MAPI/utils.ts, src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/WorkerNodesAzureMachinePoolSpotInstances.tsx, src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx, src/components/MAPI/workernodes/WorkerNodesCreateNodePoolSpotInstances.tsx, src/components/MAPI/workernodes/patches.ts, src/components/UI/Inputs/CheckBoxInput/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/CheckBoxInput/index.tsx, src/model/services/mapi/capzv1alpha3/types.ts, src/model/services/mapi/metav1/key.ts, src/model/services/mapi/metav1/types.ts, src/shared/constants/index.ts
This PR adds support for configuring Azure spot instances when creating node pools from the MAPI cluster detail page. It uses the same UI components as the current GS API implementation, so nothing too crazy on that part.
The PR also includes a small change in the way we display the maximum spot instance pricing in node pools that have already been created. Because the max price is a `Quantity` type, and not a regular string or number, it represents a serialized value of a number, with certain suffixes that represent the number that the prefix should be multiplied by to get the actual value.
> For example, `"10u"` represents `0.00001`.
The utility for parsing these types of data structures has been copied from the official …
=> clusters: add support for configuring spot instances on NP creation via the MAPI page

jest.config.js, src/components/MAPI/clusters/Cluster.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterDescription.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterName.tsx, src/components/MAPI/clusters/CreateCluster/index.tsx, src/components/MAPI/clusters/CreateCluster/patches.ts, src/components/MAPI/clusters/utils.ts, src/components/MAPI/utils.ts, src/model/services/mapi/capiv1alpha3/createCluster.ts, src/model/services/mapi/capiv1alpha3/index.ts, src/model/services/mapi/capiv1alpha3/key.ts, src/model/services/mapi/capzv1alpha3/createAzureCluster.ts, src/model/services/mapi/capzv1alpha3/createAzureMachine.ts, src/model/services/mapi/capzv1alpha3/index.ts, src/model/services/mapi/capzv1alpha3/types.ts, src/shared/constants/index.ts, testUtils/mockHttpCalls/capzv1alpha3/azureMachines.ts
This PR adds support for basic cluster creation via the MAPI cluster creation page. It includes defaulting, viewing the cluster name in a disabled form and modifying the cluster description.
As for the implementation, it is pretty much the same as with node pool creation. I re-used the same `patch` pattern as I used there. The only twist is that we have to fetch all releases and determine the latest (active and non-prerelease) release that we can use. Until that data is fetched, the `Create cluster` button is disabled.
<details>
<summary>The form</summary>
</details>
=> clusters: add support for really basic cluster creation via the MAPI cluster creation page

src/components/Cluster/AZSelection/AZSelection.tsx, src/components/Cluster/AZSelection/AZSelectionAutomatic.tsx, src/components/Cluster/NewCluster/CreateNodePoolsCluster.js, src/components/Cluster/NewCluster/NewClusterWrapper.tsx, src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx, src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx, src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts, src/components/MAPI/clusters/CreateCluster/CreateClusterControlPlaneNodeAZs.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterDescription.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx, src/components/MAPI/clusters/CreateCluster/index.tsx, src/components/MAPI/clusters/CreateCluster/patches.ts, src/components/UI/Controls/ExpandableSelector/Items.tsx, src/components/UI/Display/Cluster/ReleaseComponentLabel/index.js, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/RadioInput/index.tsx
This PR adds the rest of the inputs required for creating clusters via the MAPI cluster creation UI:
* Release version
* Control plane node availability zone selection
These are implemented using the GS API components, so no major changes there.
The PR also includes a few accessibility-related changes to the `ReleaseSelector` component.
<details>
<summary>The form</summary>
</details>
<details>
<summary>Some releases</summary>
</details>
<details>
<summary>A custom AZ</summary>
</details>
=> clusters: add release and CP node AZ configuration to MAPI cluster creation

src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx, src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx, src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverviewDelete.tsx, src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetControlPlaneNodes.tsx, src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailOverviewDelete.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetControlPlaneNodes.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetCreated.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetKubernetesAPI.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetLabels.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetProvider.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx, src/components/MAPI/clusters/utils.ts, src/components/MAPI/keypairs/__tests__/ClusterDetailWidgetKeyPairs.tsx, src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx, src/components/MAPI/releases/__tests__/ClusterDetailWidgetRelease.tsx, src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx, src/components/MAPI/workernodes/__tests__/ClusterDetailWidgetWorkerNodes.tsx, src/components/UI/Display/Cluster/ReleaseComponentLabel/index.js, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/index.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/index.tsx, src/model/services/mapi/capiv1alpha3/key.ts, testUtils/mockHttpCalls/capiv1alpha3/clusters.ts, testUtils/mockHttpCalls/capzv1alpha3/azureClusters.ts, testUtils/mockHttpCalls/capzv1alpha3/azureMachines.ts, testUtils/mockHttpCalls/capzv1alpha3/index.ts, testUtils/mockHttpCalls/legacy/clusterService.ts, testUtils/mockHttpCalls/legacy/index.ts, testUtils/mockHttpCalls/releasev1alpha1/releases.ts
This PR adds unit and integration tests for all the functionality on the `Cluster details` page - `Overview` tab.
These did uncover a few minor issues, which were also fixed in the PR.
These are just to gain a bit of confidence in the implementation, and to allow me to do some refactoring later.
=> clusters: write tests for all the cluster details overview functionalities

src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx, src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx, src/components/MAPI/apps/AppInstallModal.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterDescription.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterName.tsx, src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx, src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabel.js, src/components/UI/Display/Cluster/ClusterIDLabel/index.tsx, testUtils/assertUtils.ts
This PR adds integration tests for cluster creation logic. As with the previous PRs, these are not exhaustive, but cover the most important cases.
=> clusters: write tests for MAPI cluster creation

src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/WorkerNodesAzureMachinePoolSpotInstances.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/__tests__/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/utils.ts, src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx, testUtils/mockHttpCalls/capiv1alpha3/exp/machinePools.ts
This PR adds integration tests for MAPI node pool listing/updating logic. As with the previous PRs, these are not exhaustive, but cover the most important cases.
=> clusters: write tests for MAPI node pools listing/updating

src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx, src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx, src/components/MAPI/workernodes/WorkerNodesCreateNodePoolAvailabilityZones.tsx, src/components/MAPI/workernodes/__tests__/WorkerNodesCreateNodePool.tsx, testUtils/mockHttpCalls/gscorev1alpha1/index.ts, testUtils/mockHttpCalls/gscorev1alpha1/sparks.ts
This PR adds integration tests for the MAPI node pool creation logic. As with the previous PRs, these are not exhaustive, but cover the most important cases.
=> clusters: write tests for MAPI node pool creation

src/components/MAPI/apps/utils.ts, src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx, src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx, src/components/MAPI/releases/__tests__/ClusterDetailWidgetRelease.tsx, src/components/MAPI/releases/__tests__/utils.ts, src/components/MAPI/releases/utils.ts
This was different compared to the GS API implementation, because for release managed apps (such as `external-dns`), we would see the app version, and not the underlying component version (we would see the version of the `external-dns` GS app, and not the version of upstream `external-dns` used). This was also the case for release upgrade diffs.
Previous `cluster-service` implementation
https://github.com/giantswarm/cluster-service/blob/c457bd785a5bd61520b019bba8a00357534f46ee/server/endpoint/release/lister/endpoint.go#L105
With this PR, we use the `app.componentVersion` when available, and we fallback to `app.version` when not.
=> releases: use app `componentVersion` property where available in the MAPI world

src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
In the current implementation, in the MAPI cluster listing, if the `Release` CR that corresponds to the cluster's release version is not found, the k8s version will have an infinite loading animation. This PR fixes that.
=> clusters: display MAPI cluster release version k8s component version as `n/a` when the release cannot be found

src/components/MAPI/clusters/ClusterDetail/index.tsx, src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterName.tsx, src/components/UI/Display/Cluster/ClusterIDLabel/index.tsx, src/components/UI/Display/Cluster/ClusterIDLabel/stories/ClusterIDLabel.stories.tsx
Closes [giantswarm/giantswarm#18138](https://github.com/giantswarm/giantswarm/issues/18138)
=> Fix cluster name in MAPI UI to display `Cluster name` label on hover.

helm/happa/Chart.yaml, helm/happa/templates/configmap.yaml, helm/happa/values.yaml
Needs https://github.com/giantswarm/config/pull/270/
This PR makes the MAPI cluster management feature flag controlled by the `giantswarm/config` repo.
=> Control MAPI cluster management feature flag from the config repo

src/components/UI/Display/MAPI/CLIGuide/CLIGuideAdditionalInfo.tsx, src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/CLIGuide/__tests__/index.tsx, src/components/UI/Display/MAPI/CLIGuide/index.tsx, src/components/UI/Display/MAPI/CLIGuide/stories/AdditionalInfo.tsx, src/components/UI/Display/MAPI/CLIGuide/stories/CLIGuide.stories.tsx, src/components/UI/Display/MAPI/CLIGuide/stories/Simple.tsx, src/styles/theme.ts
Towards https://github.com/giantswarm/giantswarm/issues/16564
This PR adds the UI components necessary for creating CLI Guides (see issue for more info). The actual CLI guides will be implemented in a separate PR.
<details>
<summary>Closed</summary>
</details>
<details>
<summary>Open</summary>
</details>
<details>
<summary>Open (with additional information)</summary>
</details>
=> Add CLI Guide UI components

src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
Closes [giantswarm/giantswarm#18275](https://github.com/giantswarm/giantswarm/issues/18275).
This PR aligns the node pools header style with the key pairs table to have the same font size of 12px.
=> Change Node Pools table header font size in MAPI UI to align with Key Pairs table

src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSetItem.tsx
Closes [giantswarm/giantswarm#16822](https://github.com/giantswarm/giantswarm/issues/16822).
When clicking the "X" delete icon on a subject item, it is briefly replaced by a loading spinner before deletion is complete.
Aligning the loading spinner's width and margin to that of the delete icon's resolves the shift in layout when the subject item is being deleted.
Before deletion:
After deletion is initiated:
=> Align Access Control subject item's loading spinner width and margin with delete icon's

src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx, src/components/MAPI/keypairs/ClusterDetailKeyPairDetailsModal.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterDetails.tsx
As noticed by Sandy in https://github.com/giantswarm/happa/pull/2608#issuecomment-893451618, we always display a tooltip with the full date while hovering on relative dates, even when the full date is displayed near the relative one.
Turns out we actually have an utility that only formats the relative date, and does not return a React component.
So with this PR, we no longer display full date tooltips over relative dates, if the full date is already displayed in the UI.
=> Don't display tooltips with the full date on relative dates when they are not needed

src/components/UI/Controls/VersionPicker/VersionPicker.tsx
Quick and easy fix. Previously when ticking the `Use test versions` checkbox (which is only available to GS staff, hence the `kind/refactor` label), the dropdown would close itself before you could interact with any of the list items. This fixes that.
=> Fix version picker closing itself when ticking 'Use test versions'

src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx, src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx, src/components/MAPI/organizations/AccessControl/__tests__/index.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSetItem.tsx, src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
Closes [giantswarm/giantswarm#16790](https://github.com/giantswarm/giantswarm/issues/16790).
The confirmation prompt displayed when removing a binding between a service account subject and a role should be more specific, especially to clarify that removing the binding does not remove the service account that may have been created when the binding was created.
Replacing the text "Are you sure?" with a more specific message for removing bindings (service account subjects only):
The label for the delete button has also been changed from `Yes, delete it` to `Remove`.
The `Remove` and `Cancel` buttons should have the same height now after Adrian's button refactoring 👍 
Changing the z-index of the tooltip shown when hovering over the delete icon, so it appears behind the prompt:
=> Access control: Improve deletion confirmation prompt for deleting service account subjects

src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectAddForm.tsx
Closes [giantswarm/giantswarm#16791](https://github.com/giantswarm/giantswarm/issues/16791).
This is a small change that turns off spell-checking for the subject name input. Note that the change only affects this input field.
Before:
After:
=> Access control: Turn of spell-checking for subject name input

src/components/MAPI/organizations/OrganizationDetail.tsx
Closes [giantswarm/giantswarm#16569](https://github.com/giantswarm/giantswarm/issues/16569).
Throughout the MAPI UI, a utility function for extracting error messages from Kubernetes API responses is used to return more meaningful error messages to the user. This function is now also used for errors related to loading organization details.
Example:
=> Use utility function for extracting error message from org error

src/components/GettingStarted/Steps/SimpleExample.js, src/components/MAPI/clusters/Clusters.tsx, src/components/MAPI/clusters/CreateCluster/index.tsx, src/components/MAPI/clusters/guides/CreateClusterGuide.tsx, src/components/MAPI/clusters/guides/ListClustersGuide.tsx, src/components/MAPI/guides/__tests__/utils.ts, src/components/MAPI/guides/utils.ts, src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedSimpleExample.tsx, src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap, src/lib/__tests__/helpers.ts, src/lib/docs.ts, src/lib/helpers.tsx
Towards https://github.com/giantswarm/giantswarm/issues/18343
Nothing too crazy, following the spec. The cluster creation guide gets data such as the provider, organization and cluster name from the state (so when you refresh the page, you see that you get the same UID in the guide as you do in the form)
<details>
<summary>List clusters</summary>
</details>
<details>
<summary>Create cluster</summary>
</details>
=> Add CLI guides for listing and creating clusters

src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx, src/components/MAPI/clusters/guides/InspectClusterGuide.tsx, src/components/MAPI/clusters/guides/InspectClusterReleaseGuide.tsx, src/components/MAPI/clusters/guides/SetClusterLabelsGuide.tsx, src/components/MAPI/guides/__tests__/utils.ts, src/components/MAPI/guides/utils.ts, src/components/UI/Display/MAPI/CLIGuide/CLIGuideStep.tsx, src/lib/docs.ts
Towards https://github.com/giantswarm/giantswarm/issues/18343
<details>
<summary>Chilling</summary>
</details>
<details>
<summary>Inspect cluster</summary>
</details>
<details>
<summary>Inspect cluster's release version</summary>
</details>
<details>
<summary>Set cluster labels</summary>
</details>
=> Add CLI guides for the cluster overview tab

src/components/MAPI/organizations/AccessControl/utils.ts
Closes [giantswarm/giantswarm#16835](https://github.com/giantswarm/giantswarm/issues/16835).
The roles list was previously unordered - it is now sorted by (cluster) role name in alphabetical order:
=> Access Control: Sort roles list by (cluster) role name

src/components/MAPI/guides/ListNodePoolsGuide.tsx, src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/lib/docs.ts
Towards [giantswarm/giantswarm#18343](https://github.com/giantswarm/giantswarm/issues/18343).
This PR adds a CLI guide to the Cluster Details > Worker Nodes tab, and provides information on how to node pools for a cluster using the Management API.
Collapsed:
Expanded:
=> Add CLI guide for listing a cluster's node pools

src/components/MAPI/apps/ClusterDetailApps.tsx, src/components/MAPI/clusters/guides/ListAppsGuide.tsx, src/components/MAPI/guides/__tests__/utils.ts, src/components/MAPI/guides/utils.ts, src/lib/docs.ts
Towards https://github.com/giantswarm/giantswarm/issues/18343
This PR adds a MAPI guide for listing apps installed in a cluster.
=> Add Management API guide to list installed apps

src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/guides/DeleteNodePoolGuide.tsx
Towards [giantswarm/giantswarm#18343](https://github.com/giantswarm/giantswarm/issues/18343).
This PR adds a CLI guide to the Cluster Details > Worker Nodes tab, and provides information on how to delete a node pool using the Management API.
Collapsed:
Expanded:
=> Add CLI guide for deleting a node pool

helm/happa/Chart.yaml, helm/happa/templates/configmap.yaml, helm/happa/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/17978
This PR
- removes the logic that all testing installations automatically have SSO auth enabled, while production ones don't.
- adds a feature flag configuration value `mapiAuth`
This requires a config change before releasing.
=> Create feature flag value for mapiAuth (SSO)

src/components/MAPI/guides/__tests__/utils.ts, src/components/MAPI/guides/utils.ts, src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx, src/components/MAPI/workernodes/guides/CreateNodePoolGuide.tsx, src/lib/docs.ts
Towards [giantswarm/giantswarm#18343](giantswarm/giantswarm#18343).
This PR adds a CLI guide to the Cluster Details > Worker Nodes tab > Add Node Pool form, and provides information on how to template and create a node pool using the Management API.
The contents of the node pool manifest aligns with user input from the Add Node Pool form.
Collapsed:
Expanded:
=> Add CLI guide for creating a node pool

src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx, src/components/MAPI/clusters/guides/DeleteClusterGuide.tsx
Towards [giantswarm/giantswarm#18343](https://github.com/giantswarm/giantswarm/issues/18343).
This PR adds a CLI guide to the Cluster Details > Actions tab, and provides information on how to delete a cluster using the Management API.
Collapsed:
Expanded:
=> Add CLI guide for deleting a cluster

src/components/Footer/FooterUpdateButton.tsx, src/components/UI/Controls/Button/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Controls/Button/index.tsx, src/components/UI/Controls/ConfirmationPrompt/__tests__/__snapshots__/index.tsx.snap, src/components/UI/DataTable/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/Table/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/Tabs/__tests__/__snapshots__/Tabs.tsx.snap, src/components/UI/Inputs/CheckBoxInput/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/CurrencyInput/__tests__/__snapshots__/CurrencyInput.tsx.snap, src/components/UI/Inputs/DateInput/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/FileInput/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/InputGroup/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/MultiSelect/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/Select/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/TextInput/__tests__/__snapshots__/index.tsx.snap
Towards https://github.com/giantswarm/giantswarm/issues/18607
This PR removes the custom styling from the `Update the web interface now` button in the footer. It is now using the default `small` padding that all buttons use. Also, I played with the `warning`'s button colors for a bit, to increase color contrast.
<details>
<summary>Chill</summary>
</details>
<details>
<summary>Hover</summary>
</details>
=> Keep footer button padding consistent while hovering and increase color contrast

__tests__/Users.js, src/components/Layout.js, src/components/UI/Controls/Navigation/MainMenu.js, src/components/UI/Controls/Navigation/Navigation.js
Closes https://github.com/giantswarm/giantswarm/issues/18597
Simply put, right now we have a `Users` page visible to GS staff. With the changes in this PR, if the customer SSO feature flag is on, the `Users` page is not displayed, and the `/users/` route is not accessible.
=> Hide Users page if the customer SSO feature flag is enabled

renovate.json
This activates Renovate's dependency dashboard feature, which will make it maintain an issue with an overview of the current PRs and some functions to re-trigger updates etc.
=> Activate renovate dependency dashboard

src/components/MAPI/releases/ClusterDetailUpgradeModal.tsx
Closes [giantswarm/giantswarm#18671](https://github.com/giantswarm/giantswarm/issues/18671).
A small change to add spacing between the "Inspect changes" and "Cancel" button in the cluster upgrade modal.
=> Add spacing between buttons in upgrade modal

src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx, src/components/Cluster/NewCluster/NewClusterWrapper.tsx, src/components/Home/ClusterDashboardItem.js, src/lib/helpers.tsx, src/stores/cluster/actions.ts, src/stores/cluster/selectors.ts, src/stores/nodepool/actions.ts
As seen on https://gigantic.slack.com/archives/C13MG9F0W/p1630578781011000
Turns out that while working on https://github.com/giantswarm/happa/pull/2683 I didn't take into account happa hybrid mode (SSO enabled, but MAPI cluster management disabled -> currently only used by GS staff, on AWS and KVM).
For migrated organizations, that used to have names that didn't adhere to the DNS standard, there were no clusters showing up. Also, cluster creation was not happening in the right organization. This PR fixes those issues.
=> Fix organization usage when SSO is used but MAPI cluster management is disabled

src/components/MAPI/apps/ClusterDetailAppListItem.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppList.tsx, src/components/MAPI/apps/utils.ts, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
Towards giantswarm/giantswarm#18522
This PR adds a different display style for apps that are currently deleted (have the `deletionTimestamp` set). It also introduces sorting to the list of cluster apps. The list is now sorted by the app name in an ascending order, leaving deleted apps at the end of the list (same as clusters on the home page).
<details>
<summary>Details</summary>
</details>
=> apps: display deleted cluster apps in a different way

src/stores/main/actions.ts
As seen on https://gigantic.slack.com/archives/C02MS174K/p1630671483018400
The problem was that we weren't taking into account that `Organization` CRs might not have the `status.namespace` field populated. Which meant that we were creating `SelfSubjectRulesReviews` using empty namespaces (which resulted in errors).
This PR addresses that, by computing the organization name manually if the CR does not provide it. Also, now if one of the `SelfSubjectRulesReview` request fails, we still compute permissions for other namespaces. One failure does no longer mean that we block access to the whole app.
=> Compute namespace if the Organization CR does not have the required status field

src/utils/labelUtils.ts
We don't want the user to edit the `cluster.x-k8s.io/watch-filter` as it will break functionality of CAPI clusters.
=> Block possibility to edit the `cluster.x-k8s.io/watch-filter` label.

src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx, src/components/MAPI/apps/utils.ts
Closes https://github.com/giantswarm/giantswarm/issues/18827
The problem: Some versions have a `v` prefix, while others don't.
Solution: Always remove the `v` prefix before doing semver comparisons ✅
=> apps: use normalized app versions for comparisons

src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
Sentry issue: [HAPPA-5A](https://sentry.io/organizations/giantswarm/issues/2634389081/?referrer=github_integration)
🤦
=> Prevent trying to select an app version when version loading fails

src/components/MAPI/apps/ClusterDetailAppListItem.tsx, src/components/MAPI/apps/ClusterDetailAppListItemStatus.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppList.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppListItemStatus.tsx
Closes https://github.com/giantswarm/giantswarm/issues/18826
This PR adds the app version status next to the version in collapsed mode, so you don't have to open each app to see if they need to be updated or if they are updating.
The PR also adds truncation for long pre-release versions displayed in collapsed mode, because with the version status, the text would be too long.
=> apps: display cluster app status next to app version in collapsed mode

src/components/MAPI/organizations/AccessControl/guides/ListRolesGuide.tsx
Closes https://github.com/giantswarm/giantswarm/issues/18361
We use the `ui.giantswarm.io/display=true` label selector to display Roles/ClusterRoles in the UI, so let's also include it in the command examples.
=> Use consistent labelling in the role listing CLI guide

__tests__/Login.tsx, __tests__/Logout.js, __tests__/Users.js, src/components/UI/Controls/Navigation/UserDropdown.tsx
Closes [giantswarm/giantswarm#18874](https://github.com/giantswarm/giantswarm/issues/18874).
Long names in the User dropdown menu are truncated so they don't break the UI.
Tooltip shows the full name on hover:
=> Fix: truncate long names in User dropdown UI

src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx, src/components/Cluster/ClusterDetail/AppDetailsModal/YAMLFileUpload.tsx, src/components/MAPI/apps/AppInstallModal.tsx, src/components/MAPI/apps/utils.ts
Closes https://github.com/giantswarm/giantswarm/issues/17553
This PR exposes the actual reasons for why YAML validation failed when uploading app values/secrets. This is handled on app installation and app updating. It is also implemented for the GS API UI, not because I wanted to, but because the `YAMLFileUpload` component is shared between the GS API and MAPI implementations, so it was actually easier to have everything consistent.
=> apps: display error details when YAML validation fails

.circleci/config.yml
The legacy `circleci/node` images have been deprecated
https://circleci.com/developer/images/image/cimg/node
=> Use CircleCI convenience image

.github/release-template.yml
This removes the `## What's changed` headline from the release notes template. I usually remove it manually anyway since it's not needed. Release notes are expected to talk about changes, and the sub headlines like `## Added` and `## Changed` give enough structure.
=> Remove "What's changed" headline from release notes template

src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersionInspector.tsx
Closes [giantswarm/giantswarm#18967](https://github.com/giantswarm/giantswarm/issues/18967).
The messages for successfully updating an installed app are aligned with other information shown in the UI. The length of time for which the flash messages are displayed is also increased, and they are visible for the same amount of time as an unsuccessful update message.
The messages can still be pinned by pointing the cursor on the message (no changes needed here).
Successful upgrade:
Successful downgrade:
=> Align flash messages for updating installed apps

src/components/Layout.js
Closes https://github.com/giantswarm/giantswarm/issues/18978
Just something I broke in a previous PR ✅
=> Only display the `Users` page to admins, and only if customer SSO is disabled

src/lib/__tests__/semver.ts, src/lib/semver.ts
When comparing a version without labels (e.g. `12.0.0`) to a version of the same number with labels (e.g. `12.0.0-something`), the `compare` function is returning "0", indicating that the versions are equal. This creates a bug where it is not possible to downgrade an app's version:
This is fixed by changing the order of operands in the logical operation so that the last value returned is a boolean.
=> Fix semver comparison

src/components/MAPI/clusters/utils.ts, src/components/MAPI/types.ts, src/components/MAPI/utils.ts, src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/WorkerNodesAzureMachinePoolSpotInstances.tsx, src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx, src/components/MAPI/workernodes/WorkerNodesCreateNodePoolScale.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItemScale.tsx, src/components/MAPI/workernodes/utils.ts, src/components/UI/Controls/DropdownMenu.tsx, src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx, src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolListPlaceholder.tsx, src/components/UI/Inputs/ViewEditName.tsx, src/model/services/mapi/capiv1alpha4/createMachinePool.ts, src/model/services/mapi/capiv1alpha4/deleteMachinePool.ts, src/model/services/mapi/capiv1alpha4/getMachinePool.ts, src/model/services/mapi/capiv1alpha4/getMachinePoolList.ts, src/model/services/mapi/capiv1alpha4/index.ts, src/model/services/mapi/capiv1alpha4/key.ts, src/model/services/mapi/capiv1alpha4/types.ts, src/model/services/mapi/capiv1alpha4/updateMachinePool.ts, src/model/services/mapi/capzv1alpha4/createAzureMachinePool.ts, src/model/services/mapi/capzv1alpha4/getAzureMachinePool.ts, src/model/services/mapi/capzv1alpha4/index.ts, src/model/services/mapi/capzv1alpha4/key.ts, src/model/services/mapi/capzv1alpha4/types.ts, src/shared/constants/index.ts
Closes https://github.com/giantswarm/giantswarm/issues/18770
Starting with the Giant Swarm Azure alpha release `v20.0.0`, we support full blown CAPZ clusters and node pools, and since these use `v1alpha4` `MachinePool` and `AzureMachinePool` CRs, which are now part of a different API group, we need to make some changes to support them.
This PR adds the new `v1alpha4` types and utility functions, and adapts the logic so the new types would also work.
> ⚠️ Note: CAPZ node pools are in read only mode for the alpha release: you can't create/update/delete node pools from the UI, and the CLI guides for those operations are also hidden.
=> Add alpha support for node pools on CAPZ clusters

src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx, src/components/MAPI/clusters/utils.ts, src/components/MAPI/utils.ts
As seen on https://gigantic.slack.com/archives/C02FJACQ3D4/p1635861763020500
Looks like we messed this up during the AWS migration 😅
=> Fix not being able to display any information about CAPZ clusters

src/components/MAPI/utils.ts, src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx, src/components/MAPI/workernodes/WorkerNodesCreateNodePoolMachineType.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx, src/components/MAPI/workernodes/patches.ts
Towards https://github.com/giantswarm/roadmap/issues/388
This PR adds the option to enable similar instance types when creating an AWS node pool.
<details>
<summary>NP creation form</summary>
</details>
<details>
<summary>NP uses similar instance types and 3 instance types</summary>
</details>
<details>
<summary>NP uses similar instance types and 3 instance types - hover</summary>
</details>
=> node pools: add support for configuring similar instance types on AWS via MAPI

src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx, src/components/MAPI/clusters/ClusterDetail/utils.ts, src/components/MAPI/clusters/CreateCluster/patches.ts, src/components/MAPI/clusters/utils.ts, src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts, src/components/MAPI/types.ts, src/components/MAPI/utils.ts, src/components/MAPI/workernodes/WorkerNodesCreateNodePoolSpotInstances.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx, src/components/MAPI/workernodes/patches.ts, src/components/MAPI/workernodes/utils.ts, src/model/services/mapi/infrastructurev1alpha2/index.ts, src/model/services/mapi/infrastructurev1alpha2/types.ts
Towards https://github.com/giantswarm/roadmap/issues/388
So turns out that GS-specific `v1alpha2` resources are still used in some old AWS clusters. This PR introduces a very very hacky way of dealing with them. We fool the type system a little bit, but behind the scenes we still operate on `v1alpha3` resources, which is fine, since there are conversion webhooks set up on the backend side.
=> clusters: add support for v1alpha2 resources

src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx, src/components/MAPI/clusters/ClusterDetail/index.tsx, src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx, src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx, src/components/MAPI/clusters/utils.ts, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx
This pretty much only affects AWS clusters, so this is towards https://github.com/giantswarm/roadmap/issues/388
This PR makes sure that we display loading animations when it's right to do so, and we don't display placeholders unless we tried to load everything there is to load.
=> Only display placeholders if the right resources were loaded

src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx, src/components/MAPI/clusters/guides/SetClusterLabelsGuide.tsx
Towards https://github.com/giantswarm/roadmap/issues/388.
This PR updates the CLI guide for setting cluster labels to use the full CRD name for clusters on AWS
=> clusters: update CLI guide for setting cluster labels for AWS clusters

src/components/MAPI/__tests__/utils.ts, src/components/MAPI/utils.ts
This only affects MAPI AWS. Just moving a bracket a couple of lines down 😅
=> Fix memory leak when creating NPs in clusters with HA CP nodes

src/components/UI/Util/FlashMessages/FlashMessagesController.ts, src/components/UI/Util/FlashMessages/FlashMessagesNotification.tsx, src/lib/Queue.ts, src/lib/__tests__/flashMessage.tsx
This PR fixes a bug with flash messages, where duplicate messages were being displayed after the user closes the first one. It also adds the `word-break` property to flash message content to prevent text content from overflowing.
=> Fix flash messages duplication and content overflow

src/components/MAPI/utils.ts, src/components/MAPI/workernodes/WorkerNodesCreateNodePoolSpotInstances.tsx, src/components/MAPI/workernodes/utils.ts
In the node pool creation form, there is an option to enable spot instances, and this option should be disabled by default in both the UI and the resulting CRD created by the form.
The percentage of spot instances is equal to the percentage of instances that are not on-demand. So in order to disable spot instances by default, we set `onDemandPercentageAboveBaseCapacity` to 100. When the option is enabled, we set `onDemandPercentageAboveBaseCapacity` to 0.
=> Fix node pool creation: spot instances should be disabled by default

src/components/Auth/MAPI/MapiUnauthorized.tsx, src/components/MAPI/Experiments.tsx, src/components/MAPI/permissions/usePermissions.ts, src/lib/OAuth2/OAuth2.ts, src/lib/OAuth2/TestOAuth2.ts, src/model/services/mapi/generic/ensureClientAuth.ts
Closes https://github.com/giantswarm/roadmap/issues/564
This PR adds a new `Impersonation` section to the `Experiments` page.
With it we can act as other users, test permissions or debug problems.
This is only visible to Giant Swarm staff, for now. We can create better UI support for customers later on.
Impersonation is also persisted between sessions. If you get stuck, you can delete the `localStorage` entry from the DevTools Inspector.
[Read more about Kubernetes API impersonation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation)
=> Add staff support for impersonating users

src/model/services/mapi/gscorev1alpha1/types.ts, src/model/services/mapi/legacy/keypairs/getKeyPairList.ts
Fixes https://sentry.io/organizations/giantswarm/issues/2796688169/
=> Take into account that the `.spec` property of a StorageConfig can be omited

src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
Towards https://github.com/giantswarm/giantswarm/issues/19161#issuecomment-972737232.
This PR adds a warning message to the client certificates list:
=> Add a warning message to client certificates list

src/components/MAPI/clusters/CreateCluster/index.tsx
As seen here https://gigantic.slack.com/archives/C02HLSDH3DZ/p1637672187203800
=> Account for mixed-case organization names when creating clusters

src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx, src/components/MAPI/clusters/utils.ts, src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts, src/components/MAPI/utils.ts, src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx, src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/utils.ts
Closes https://github.com/giantswarm/roadmap/issues/589.
When a node pool is deleted, for a moment before data refreshes, there is a mismatch between node pool description and other node pool information (e.g. name and instance type). This was because the list of node pools and provider node pools could sometimes be out of sync, and we were iterating through both lists using the index from one.
This PR associates the provider node pools with node pool names, so that we can then map node pools to their provider node pools more accurately (this is similar to [this PR](https://github.com/giantswarm/happa/pull/2929)). It also provides a fix for the node pool description placeholder getting stuck after node pool deletion.
=> Fix node pool list information mismatch

src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx, src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx, src/components/MAPI/organizations/AccessControl/__tests__/index.tsx, src/components/MAPI/organizations/AccessControl/index.tsx, src/components/MAPI/organizations/AccessControl/utils.ts, src/components/MAPI/organizations/permissions/usePermissionsForAccessControl.ts, src/components/MAPI/permissions/utils.ts, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectAddForm.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx, src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleDetail.tsx, src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleList.tsx, src/components/UI/Display/MAPI/AccessControl/types.ts, src/model/services/mapi/rbacv1/getClusterRoleBindingList.ts, src/model/services/mapi/rbacv1/getClusterRoleList.ts, src/model/services/mapi/rbacv1/getRoleBindingList.ts, src/model/services/mapi/rbacv1/getRoleList.ts
This PR re-enables being able to bind and remove bindings for all subjects. It also now includes more granular control over what users can and can't do, all relative to their RBAC permissions.
What we control:
- Fetching `Role`s/`ClusterRole`s or both, depending on what the user has access to
- Not allowing users to remove subjects, if they don't have access to do it
- Not allowing users to bind subjects, if they don't have access to do it
- Hiding the lists of subjects if there are no entries and the user doesn't have access to binding others
- Only allowing users to bind existing service accounts, if they don't have access to creating new ones
- Not fetching service account name suggestions if the user doesn't have access to do it
For the actual RBAC permissions required for all these, …
=> Make access control UI aware of permissions. Re-enable binding subjects.

src/model/services/mapi/generic/ensureClientAuth.ts
I noticed that if `groups` is not set, the condition for setting "Impersonate-Group" in headers still evaluates to true, and impersonation doesn't behave as expected.
=> Only set impersonation group header if groups is defined

helm/happa/Chart.yaml, helm/happa/templates/happaapi-ingress.yaml, helm/happa/templates/ingress.yaml
This PR reverts changed done in #2992 to restore support for kubernetes below 1.19
=> Revert dropping support for k8s > 1.19

src/components/MAPI/apps/permissions/usePermissionsForApps.ts, src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx, src/components/MAPI/clusters/guides/DeleteClusterGuide.tsx, src/components/MAPI/permissions/utils.ts, src/components/MAPI/workernodes/permissions/usePermissionsForNodePools.ts, src/components/MAPI/workernodes/permissions/usePermissionsForSparks.ts, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteAction.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailDeleteAction.tsx
Towards [giantswarm/roadmap#551](https://github.com/giantswarm/roadmap/issues/551).
This PR makes the cluster details > actions tab aware of permissions. The UI is adapted in the following ways for a read-only user:
**Disable "Delete..." button and adapt warning message:**
The cursor is also displayed in the `not-allowed` style on hover over the button.
**Display warning message in CLI guide:**
**Checking for permissions for node pools and apps:**
Although the deletion confirmation step (the step showing number of worker nodes and apps installed in the cluster) is not shown for a read-only user, the data is fetched in the same parent component. Thus, we check whether the user has permissions to read this data before fetching.
=> Make cluster details > actions tab aware of permissions for a read-only user

src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
This PR adds an additional check to how we find a cluster's organization within the organization list, by also checking for a match to the organization ID, if the name doesn't match.
=> Fix not being able to find cluster's organization in organization list

helm/happa/templates/happaapi-ingress.yaml
As discussed in https://gigantic.slack.com/archives/C02FJACQ3D4/p1639653195111200
This takes the default headers from https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#enable-cors and adds `Impersonate-User` and `Impersonate-Group`.
=> Allow impersonation headers via CORS

src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteAction.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailDeleteAction.tsx
Towards https://github.com/giantswarm/giantswarm/issues/20227.
The cluster deletion page on KVM was incorrectly displaying that the user does not have sufficient permissions for deleting clusters. This PR fixes a bug introduced by the permissions check in https://github.com/giantswarm/happa/pull/3035.
=> Fix cluster deletion for KVM

.circleci/config.yml
We would like for new releases to be deployed automatically to the openstack-app-collection so we don't have to update the app collection manually.
=> Push to openstack-app-collection

helm/happa/templates/configmap.yaml, scripts/getConfigurationValues.ts, src/@types/global.d.ts, src/components/index.tsx, src/index.ejs, src/utils/errors/SentryErrorNotifier.ts
This PR adds a [custom tag](https://docs.sentry.io/platforms/javascript/enriching-events/tags/) named `pipeline` to any Sentry event. We can use that to filter out issues created in test installations from notifications.
=> Add a 'pipeline' tag to Sentry events, to distinguish stable/testing

src/model/clients/HttpClient.ts, src/model/stores/batchActions.ts
Towards https://github.com/giantswarm/giantswarm/issues/20464.
This PR improves the handling of fetch errors thrown while a user is logging into the application. While we can't reliably check for specific network errors (e.g. `net::ERR_CONNECTION_CLOSED`), these errors fall under the `TypeError` exception thrown by `fetch()`. We improve handling by including the original error message in the error reported to Sentry, and displaying a more appropriate error message to the user in this case during login:
One thing to bear in mind is that these errors can occur for a number of different reasons (more information can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions)), so it wouldn't be appropriate to display a message that is too specific, and should rather …
=> Improve handling of fetch errors during login

src/components/MAPI/apps/utils.ts
Closes https://github.com/giantswarm/giantswarm/issues/20496.
This PR removes the label selector `application.giantswarm.io/catalog-type: stable` when fetching catalogs for non-admin users (non-GS staff) for the Apps page. This allows these users to see all catalogs with the label selector `application.giantswarm.io/catalog-type: public` in the namespaces they have access to. In the `default` namespace, these would be the Giantswarm and Playground catalogs.
=> Fix non-admin users not able to see Playground catalog

src/components/MAPI/apps/ClusterDetailAppListWidgetUninstall.tsx
Closes https://github.com/giantswarm/roadmap/issues/691.
Currently, the only additional information we show for confirming an app uninstallation is the ambiguous phrase: "There is no undo." This PR seeks to improve the message shown, informing users about what happens to any configuration resources after uninstallation, and that the app can be easily re-installed .
Both ConfigMap and Secret are used to configure the app:
Just ConfigMap exists (the case where just Secret exists is similar):
No configurations exist:
=> Improve app uninstallation confirmation info

src/components/UI/Display/Apps/AppList/AppIcon.tsx
This PR applies the same logic to SVG icons that we apply to PNG icons for making sure that the version shown is optimized for a dark background.
=> Ensure SVG app icons are appropriate for a dark background

src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx, src/components/MAPI/clusters/Clusters.tsx, src/components/MAPI/clusters/utils.ts, src/components/MAPI/utils.ts
Closes https://github.com/giantswarm/roadmap/issues/795.
This PR changes how we determine which provider-specific cluster resources to fetch. This was previously done by checking `infrastructureRef.apiVersion`, which made us dependent on the specific API version specified in the CRD. We change this by checking `infrastructureRef.kind` instead, and matching its lowercased value to "azurecluster" or "awscluster".
This change affects the following components:
- cluster list overview: description, nodepool stats
- cluster details: description, nodepool stats, provider widget, control plane node(s) label
- client certs tab (whether client certificates are supported)
We also display a flash message when there is an error in fetching provider cluster resources, and provide the reason why:
=> Change how we determine provider-specific cluster resources

src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetKubernetesAPI.tsx, src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
Closes https://github.com/giantswarm/giantswarm/issues/20418.
This PR adds a check to whether the "Get Started" guide should be displayed. If the cluster is in the `default` namespace (i.e. if `cluster.metadata.namespace` is set to `default`), then we don't display the "Get Started" guide.
=> Don't display "Get Started" guide if the cluster is not in the organization namespace

.circleci/config.yml
This is needed so we can remove the manifests dir from the app collections.
https://github.com/giantswarm/aws-app-collection/tree/master/manifests
This holds the Argo application CRs and is now obsolete.
=> (chore) bump architect-orb to v4.13.0

src/components/MAPI/clusters/guides/InspectClusterGuide.tsx, src/model/constants/docs.ts
Closes https://github.com/giantswarm/roadmap/issues/796.
This PR fixes the information displayed in the "Inspect this cluster" CLI guide for AWS installations by showing commands to inspect the appropriate CRDs and fixing the links to external CRD documentation:
=> Fix CLI guide for inspecting clusters displaying incorrect information on AWS

src/components/MAPI/organizations/AccessControl/utils.ts, src/model/services/mapi/rbacv1/types.ts
Closes https://github.com/giantswarm/giantswarm/issues/21113, related to the changes in `rbac-operator` from https://github.com/giantswarm/rbac-operator/pull/292.
This PR fixes the error we saw on `gauss` while testing the new changes in `rbac-operator`. It is possible for a `RoleBinding` to exist, and not be bound to any subjects, and the `subjects` field will be omitted if it's empty. We update the interfaces for `IClusterRoleBinding` and `IRoleBinding` to take this into account, and add some checks to prevent us from trying to use the `undefined` value.
=> Don't rely on `Rolebinding.subjects` being defined

src/components/MAPI/apps/ClusterDetailAppListWidgetCatalog.tsx, src/components/UI/Display/Apps/AppList/CatalogLabel.tsx
Towards [giantswarm/roadmap/issues/825](https://github.com/giantswarm/roadmap/issues/825).
The "managed" label in the "Installed Apps" section has different style from the similar labels in other places. In this PR this label was changed so now it's being rendered by the same component that we use for other labels.
Before:
After:
=> Align managed app catalog label

src/components/MAPI/organizations/AccessControl/__tests__/index.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItem.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSetItem.tsx, src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleList.tsx, src/components/UI/Display/RefreshableLabel.js
Closes https://github.com/giantswarm/roadmap/issues/656.
This PR brings some improvements to the roles list in the access control UI to make it easier to see which roles are bound in the namespace. The following changes have been made:
- display number of service accounts bound to a role
- subject labels (i.e. "Groups", "Users", "Service Accounts") have been replaced by subject icons, with a tooltip displaying the label on hover
- display subject icon and count in a "lighter" colour if there are no subjects of that type bound to a role
- briefly highlight the subject icon when the count changes
Hovering over a role list subject icon:
In addition, a small bug was fixed to prevent a newly added subject from being repeatedly highlighted when toggling between items in the roles list.
=> access control: improve roles list

src/components/UI/Inputs/Select/index.tsx
Towards [giantswarm/roadmap/issues/821](https://github.com/giantswarm/roadmap/issues/821).
Version selector inside the app details can overlap the header. To fix that, z-index of the `Select` component was decreased. Alternatively we can increase `z-index` of the `Header` (currently is 1), but that can cause issues with other elements. Currently this is the only place where we use `Select` component.
=> Change Select component z-index

src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx, src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx, src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
Closes https://github.com/giantswarm/roadmap/issues/900, following on from this comment: https://github.com/giantswarm/happa/pull/3251#issuecomment-1064894008.
This PR removes the flash messages we used to display on successful role binding events (creation and deletion). Newly added subjects are already temporarily highlighted, and the subject counts are also temporarily highlighted as they're incremented/decremented. This change minimizes the number of simultaneous events in the UI that convey similar messages.
https://user-images.githubusercontent.com/62935115/158616287-e6a0ca91-b95e-4015-bf43-2d67fb8a5321.mov
Note that flash messages for errors are unchanged, and will continue to be displayed as they occur.
=> access control: don't display flash messages on successful role binding events

src/components/MAPI/organizations/AccessControl/index.tsx, src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx, src/components/UI/Layout/Modal/index.tsx, src/styles/index.ts
Closes https://github.com/giantswarm/roadmap/issues/901.
This PR aligns the style of the scrollbar in the access control UI roles list with that of the app installation modal. The style used is based off of the scrollbar style of the `<CodeBlock>` component. The css rules for the scrollbars are also separated for easier reuse in the future.
=> Align style of scrollbars

src/components/MAPI/permissions/usePermissions.ts
Towards https://github.com/giantswarm/roadmap/issues/870.
We have different hooks for different kinds of permissions, e.g. `usePermissionsForKeyPairs`, `usePermissionsForCertConfigs`, `usePermissionsForStorageConfigs`, etc. All of them use `usePermissions` hook which uses SWR to fetch permissions. As a result `usePermissions` hook is being called a lot and it triggers `useSWR` hook revalidation. (By default SWR should revalidate when it mounts and there is stale data - [docs](https://swr.vercel.app/docs/revalidation#disable-automatic-revalidations).) Revalidation causes a lot of extra re-renders of different components.
In this PR I disable permissions revalidation when stale. We still revalidate permissions `onFocus` and `onInterval`.
=> Disable permissions revalidation when stale

package.json, yarn.lock
`@braintree/sanitize-url` package has a known [security vulnerability](https://security.snyk.io/vuln/SNYK-JS-BRAINTREESANITIZEURL-2339882). It's a sub-dependency of the`mermaid` package. They already merged a [PR](https://github.com/mermaid-js/mermaid/pull/2790) with the fix but it's not released yet. So we temporary add `@braintree/sanitize-url` into the resolutions in `package.json` to upgrade it manually to the latest version.
=> Upgrade @braintree/sanitize-url from 3.1.0 to 6.0.0

src/components/UI/Display/MAPI/AccessControl/AccessControlRolePermissions.tsx
Towards [giantswarm/roadmap/issues/820](https://github.com/giantswarm/roadmap/issues/820).
In the permissions tab we use the `<InfiniteScroll>` component from `Grommet` to lazy-render the items. It's currently configured to remove "off-screen" items. Since the permissions list is not inside a scrollable container (window scroll used instead) `<InfiniteScroll>` component removes items while they are still visible. As a result we can see empty gaps.
In this PR `replace` feature was disabled to improve scrolling experience. This should not bring any performance issues since the items we render in the permissions list are simple and not very interactive. From the `Grommet` [docs](https://v2.grommet.io/infinitescroll#replace):
> `replace` should be set to true within Drop containers and false …
=> Fix permissions list scrolling

helm/happa/templates/deployment.yaml, helm/happa/templates/pdb.yaml
Closes https://github.com/giantswarm/roadmap/issues/972
This PR
- Fixes the anti-affinity selector that should avoid all pods running on the same node
- Adds a `PodDisruptionBudget` template with `minAvailable: 1`
=> Keep happa available during upgrades

src/components/MAPI/apps/__tests__/ClusterDetailAppListItem.tsx, src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx, src/components/MAPI/keypairs/ClusterDetailKeyPairDetailsModal.tsx, src/components/UI/Display/Date/index.tsx, src/components/UI/Display/MAPI/apps/AppVersionInspectorOption.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterDetails.tsx, src/utils/helpers.ts
Towards [giantswarm/roadmap/issues/971](https://github.com/giantswarm/roadmap/issues/971).
We have a `<Date />` component that displays a date in a relative form, e.g. 5 minutes ago, or 1 year ago. After being displayed, relative date stays the same until next rerender - it's unpredictable when a rerender can happen or it can not happen at all. As a result relative dates can be outdated. In this PR I changed the `<Date />` component so it updates the displayed value every minute. "Auto refresh" happens only for dates that are in 45 minutes from current time, because after 45 minutes, formatted date looks like `about 1 hour`, `about [2..24] hours`, `1 day` and so forth and it's not necessary to auto refresh it anymore.
Some other small changes:
- `<Date />` component was reused in some …
=> Auto refresh relative dates

.circleci/config.yml
Towards https://github.com/giantswarm/roadmap/issues/1042.
This PR makes some changes in an effort to reduce build time/credit usage in CircleCI:
- only build and push fe-docs when creating a release
- combine pushing to docker and quay with `build-container` step to prevent building image and attaching workspace multiple times (attaching the workspace takes up most of the time in these steps)
- combine building and pushing fe-docs to quay to prevent building image and attaching workspace twice
=> Improve build time in CI

src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx, src/components/UI/Display/MAPI/workernodes/styles.tsx, src/components/shared/Copyable.tsx, src/styles/index.ts, src/utils/__tests__/helpers.ts, src/utils/helpers.ts
Towards [giantswarm/roadmap/issues/871](https://github.com/giantswarm/roadmap/issues/871).
Currently we use fixed width column to display node pools names. The width is 80px - it's calculated to fit 5 character long names. Names that are longer than 5 characters are being truncated to 5 character strings.
It was decided that we want to display longer names - up to 10 characters. In this PR I changed the width of the name column in the table. The width is being calculated to fit the longest name in the table. The minimum width is kept as it was before - 80px.
=> Allow to display longer node pool names

src/components/MAPI/apps/AppList/__tests__/AppDetail.tsx, src/components/MAPI/apps/AppList/__tests__/index.tsx, src/components/MAPI/apps/__tests__/AppInstallModal.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppListItemStatus.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersion.tsx, src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx, src/components/MAPI/apps/utils.ts, test/mockHttpCalls/applicationv1alpha1/appcatalogentries.ts
Closes https://github.com/giantswarm/roadmap/issues/1052.
This PR fixes the bug described in the linked issue, where an installed app was not being appropriately displayed in the app catalogs. This was caused by matching the App CR's `.metadata.name` instead of its `.spec.name` against the AppCatalogEntry's name.
The mock AppCatalogEntry list items data we use in our tests was also updated to match the data we would expect to receive in a real call, and the affected test cases updated.
=> Check installed app's `.spec.name` against app catalog entry name

src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx, src/components/MAPI/clusters/CreateCluster/index.tsx, src/components/MAPI/clusters/utils.ts, src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx, src/components/MAPI/workernodes/__tests__/WorkerNodesCreateNodePool.tsx, src/components/MAPI/workernodes/utils.ts
Closes https://github.com/giantswarm/roadmap/issues/1014.
This PR changes cluster and node pool creation to allow for resubmission with the same inputs in case of an error. We also update the error flash message prompting users to try again or contact support:
The `createCluster` and `createNodePool` functions are changed to allow toggling behaviour with the `isRetrying` boolean flag. This is to handle errors on retries that an object already exists. In this case we don't return the error as a rejected promise, and fetch the corresponding existing resource.
=> Allow retrying cluster and nodepool creation

src/components/MAPI/apps/ClusterDetailAppListItem.tsx, src/components/MAPI/apps/guides/UpdateAppGuide.tsx
Closes https://github.com/giantswarm/roadmap/issues/1058.
This PR fixes a bug in the CLI guide for updating app: we now use the App CR's `.spec.name` to look up `appcatalogentries` for updating the app.
An example from `gollum` where an App CR's `.spec.name` (`nginx-ingress-controller-app`) differs from its `.metadata.name` (`nginx-ingress-controller`):
=> Update app CLI guide: use an installed app's `.spec.name` to search for app catalog entries for the app

src/components/MAPI/workernodes/utils.ts
This PR fixes a bug with CGroups version checking - the annotations object should not be accessed to get the annotation label.
=> Fix CGroups annotation check

src/components/MAPI/apps/ClusterDetailAppListWidgetConfiguration.tsx
Closes https://github.com/giantswarm/roadmap/issues/1009.
This PR increases the TTL of flash messages we display when configuring app values (ConfigMaps and Secrets) from short (1500ms) to long (10000ms). This is to allow more time for reading the content.
=> Prolong display of flash messages for configuring app values

src/components/MAPI/apps/ClusterDetailAppListItem.tsx, src/components/MAPI/apps/ClusterDetailAppListItemStatus.tsx, src/components/MAPI/apps/ClusterDetailAppListWidgetVersion.tsx, src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx, src/components/MAPI/apps/utils.ts, src/model/services/mapi/applicationv1alpha1/key.ts
Background: https://gigantic.slack.com/archives/C02BBLEE2KW/p1651154989199529
We had previously made a change to handle discrepancies in an installed app's `.spec.version` and `.status.version` (caused by Flux) by stripping the `v-` prefix when making comparisons between versions. However, this created an issue when app catalog entries have a `v-` prefix. GS app catalogs don't have entries with a `v-` prefix, but this poses an issue for customers who create their app catalog entries with the prefix.
This PR fixes the issue by adding an extra check and only normalizes (strips the `v-` prefix) of an app's `.spec.version` if it is managed by Flux. Otherwise, the app versions are unmodified so they can be properly matched with app catalog entry versions.
=> Handle app catalog entry versions with `v-`  prefixes

src/components/MAPI/apps/utils.ts
Follow up to https://github.com/giantswarm/happa/pull/3400.
This PR fixes how we calculate the upgradable apps count  by changing it to use the utility function created in the linked PR. This takes into account app version normalization for Flux- and non-Flux managed resources.
=> Fix upgradable apps count calculation in cluster details overview

src/components/UI/Display/MAPI/permissions/PermissionsUseCases/PermissionsUseCases.tsx, src/components/UI/Display/MAPI/permissions/PermissionsUseCases/StatusesForCategory.tsx
Permissions overview column width was increased to better fit longer organization names. Names that are longer than 30 characters are being truncated.
Before:
After:
=> Increase permissions overview column width

.circleci/config.yml, package.json, src/components/MAPI/permissions/Permissions.tsx, src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx, src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverview.tsx, src/components/MAPI/permissions/SubjectForm/SubjectForm.tsx, src/components/MAPI/permissions/SubjectForm/index.ts, src/components/MAPI/permissions/__tests__/Permissions.tsx, src/components/MAPI/permissions/__tests__/utils.ts, src/components/MAPI/permissions/guides/InspectPermissionsGuide.tsx, src/components/MAPI/permissions/types.ts, src/components/MAPI/permissions/useSubjectPermissions.ts, src/components/MAPI/permissions/useUseCasesPermissions.ts, src/components/MAPI/permissions/utils.ts, src/model/constants/index.ts, src/model/services/mapi/rbacv1/key.ts, test/mockHttpCalls/authorizationv1/selfSubjectAccessReviews.ts, yarn.lock
Closes https://github.com/giantswarm/roadmap/issues/1122.
This PR adds the functionality to inspect permissions for a service account:
The service account prefix remains in place, similar to the customer groups prefix:
The "Inspect Permissions" CLI guide also adapts similarly for service accounts as it does for users and groups:
=> Inspect permissions for a service account

src/components/MAPI/clusters/CreateCluster/CreateClusterServicePriority.tsx, src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx, src/components/MAPI/clusters/CreateCluster/index.tsx, src/components/MAPI/clusters/CreateCluster/patches.ts, src/components/MAPI/clusters/utils.ts, src/components/MAPI/utils.ts, src/model/constants/index.ts, src/model/services/mapi/capiv1beta1/key.ts
The ability to set service priority has been introduced to the create cluster form in this PR. The service priority is set to `highest` by default.
=> Add service priority select box into create cluster form

src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx, src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverview.tsx, src/components/MAPI/permissions/guides/InspectPermissionsGuide.tsx, src/components/MAPI/permissions/utils.ts
Closes https://github.com/giantswarm/roadmap/issues/1185.
This PR adds the "Use web UI" use case to the list of use cases displayed in the permissions overview page. This use case is only evaluated and displayed for User and Group subject types (it doesn't make sense to display it for Service Accounts, and is redundant when inspecting permissions for yourself).
=> Add "Use web UI" use case to permissions overview

.storybook/preview-head.html, src/components/UI/Display/Documentation/Mermaid.tsx, src/index.ejs
Towards https://github.com/giantswarm/giantswarm/issues/22146
Switches Roboto and Inconsolata to use our self-hosted files instead of Google's.
=> Use self hosted fonts for Roboto and Inconsolata

src/components/Cluster/ClusterDetail/AppDetailsModal/YAMLFileUpload.tsx
Closes https://github.com/giantswarm/roadmap/issues/1212.
This PR fixes a bug with uploading files to configure an installed app. When users re-upload a file with the same name, the `onChange` event is not fired. This is because the `<input />` element's value is set to the file's path, and the value has not changed (even if the file contents have).
To circumvent this, we reset the value of `<input />` to an empty string whenever the "Upload/Replace values/secret values" button is clicked.
This PR also fixes a related bug where we try to index an empty array of files - in this case it makes more sense to exit early if there are no files to upload.
=> Fix uploading a file with the same name for configuring an installed app

src/components/MAPI/apps/permissions/usePermissionsForClusterApps.ts, src/components/MAPI/clusters/permissions/usePermissionsForCPNodes.ts, src/components/MAPI/clusters/permissions/usePermissionsForClusters.ts, src/components/MAPI/workernodes/permissions/usePermissionsForNodePools.ts, src/model/constants/providers.ts
Closes https://github.com/giantswarm/roadmap/issues/1214 (towards https://github.com/giantswarm/roadmap/issues/1192).
This PR adds support for determining permissions to CAPG resources, specifically clusters, control plane nodes, and node pools.
For permissions to `get` and `list` resources, this is accomplished in a similar way as we do for existing providers.
For mutating actions (`create`, `update`, `delete`), a new permissions hook is added for determining permissions to cluster apps (Apps and ConfigMaps). Cluster management should be done via cluster apps, so it makes sense to check for permissions to these resources rather than the resulting resources. The [`values.yaml`](https://github.com/giantswarm/cluster-gcp/blob/main/helm/cluster-gcp/values.yaml) file for the `cluster-gcp` app …
=> Add support for determining permissions for CAPG resources

src/components/MAPI/utils.ts, src/model/services/mapi/k8sUrl.ts
Closes https://github.com/giantswarm/roadmap/issues/1215 (towards https://github.com/giantswarm/roadmap/issues/1192).
This PR adds support for fetching CAPG resources - clusters, control plane nodes, and node pools.
=> Add support for fetching CAPG resources

src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx, src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx, src/components/MAPI/clusters/utils.ts, src/components/MAPI/utils.ts, src/model/services/mapi/capiv1beta1/key.ts, test/mockHttpCalls/infrastructurev1alpha3/awsClusters.ts
Closes [giantswarm/roadmap/issues/1226](https://github.com/giantswarm/roadmap/issues/1226).
This PR adds support for displaying a description and a status for CAPG clusters. Only `Cluster creating…` status is supported by now.
=> GCP cluster status and description

src/components/MAPI/apps/AppList/AppDetail.tsx, src/components/MAPI/apps/ClusterDetailAppListItem.tsx, src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx, src/components/MAPI/organizations/AccessControl/index.tsx, src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx, src/components/MAPI/organizations/OrganizationList.tsx, src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/UI/Display/MAPI/CLIGuide/CLIGuidesList.tsx, src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/CLIGuide/__tests__/index.tsx, src/components/UI/Display/MAPI/CLIGuide/index.tsx, src/components/UI/Display/MAPI/CLIGuide/stories/CLIGuide.stories.tsx, src/components/UI/Display/MAPI/CLIGuide/stories/CLIGuidesList.stories.tsx, src/components/UI/Display/MAPI/CLIGuide/stories/CLIGuidesList.tsx
Closes https://github.com/giantswarm/roadmap/issues/1235.
This PR improves how we display multiple CLI guides by combining them into one component, with the goal of reducing visual noise for users. This is implemented wherever we display 2 or more CLI guides in conjunction.
**An example:**
Collapsed
Expanded
=> Combine the display of multiple CLI guides into one component

src/components/MAPI/apps/ClusterDetailAppListItem.tsx, src/components/MAPI/apps/ClusterDetailAppListWidgetCatalog.tsx, src/components/MAPI/apps/ClusterDetailAppListWidgetInstalledAs.tsx, src/components/MAPI/apps/ClusterDetailAppListWidgetName.tsx, src/components/MAPI/apps/ClusterDetailAppListWidgetStatus.tsx, src/components/MAPI/apps/ClusterDetailAppListWidgetVersion.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppListItem.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetInstalledAs.tsx, src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetName.tsx, src/components/UI/Display/MAPI/apps/ClusterDetailAppListWidget/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Display/MAPI/apps/ClusterDetailAppListWidget/index.tsx, src/styles/theme.ts
Closes [giantswarm/roadmap/issues/1057](https://github.com/giantswarm/roadmap/issues/1057).
In this PR application's original name was added to the information displayed about an installed application.  For the "original name" - `.spec.name` field of the App resource is used. `.metadata.name` field, that was previously displayed as an app name, is now displayed as "Installed as". In the collapsed view, "Installed as" name is displayed only if it's different from the original name.
App item is collapsed:
App item is expanded:
=> Display original app name

src/components/__tests__/Layout.tsx, src/model/stores/organization/actions.tsx
Background https://gigantic.slack.com/archives/C02FJACQ3D4/p1660053452432869.
While helping a customer with a happa login issue, it was noticed and reported that the `SelfSubjectAccessReview` we create during login to check if the user has access to list Organizations is performed in the `default` namespace. This is incorrect - Organizations are not namespaced resources, and the `SelfSubjectAccessReview` should instead be created outside of namespaces/at the cluster scope (i.e. omitting the namespace field).
This was returning false positives for access, which then leads to requests for listing organizations to be wrongly made.
=> Fix login: create SelfSubjectAccessReview in correct namespace

src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx, src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx, src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts, src/components/UI/Display/Organizations/OrganizationDetailPage.tsx, src/components/UI/Display/Organizations/types.ts, test/mockHttpCalls/capiv1beta1/clusters.ts
Closes https://github.com/giantswarm/roadmap/issues/1246.
This PR displays information about cluster app and Kubernetes version in the Organizations > General tab. This section is only displayed if at least one cluster in the organization is created from a cluster app. We also don't display the 'Releases' section if the provider does not support releases.
For example, when there is one cluster app and Kubernetes version in use:
When there are 2 different versions in use, we enumerate the versions:
When there are 3 or more versions in use, we display the number of versions in use, as well as the oldest and newest versions:
Kubernetes versions are also displayed using a similar logic, and the EOL date is displayed on mouseover in a tooltip.
=> Display cluster app and Kubernetes version information in Organizations > General tab

README.md
The shield URL is still pointing to `master`. Changing to `main` to make it work again.
=> Fix default branch in CircleCI badge

README.md
Update the hiring banner to be aligned visually with our org page and use less space
No
=> Update hiring banner

src/components/MAPI/utils.ts, src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx, src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx, src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx, src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolListPlaceholder.tsx, src/components/UI/Display/MAPI/workernodes/styles.tsx
This PR makes node pool management "read-only" for node pools belonging to clusters that are managed by an app (i.e. it has the `app: cluster-PROVIDER` label). Node pool creation, deletion, and updating an existing node pool's description and scaling are disabled.
Users on GCP installations will not be able to add/edit/delete node pool resources from the web UI. Users on vintage installations should notice no change.
- the "Add node pool" button and any placeholder messages prompting users to create node pools when the cluster doesn't have any node pools is hidden
- the node pool list item menu button is hidden
- node pool description is displayed as uneditable text
Closes https://github.com/giantswarm/roadmap/issues/1382, which is a task towards our first milestone of providing a …
=> Make node pool management read-only for GCP

src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx, src/components/MAPI/keypairs/ClusterDetailWidgetKeyPairs.tsx, src/components/MAPI/keypairs/utils.ts, src/components/MAPI/utils.ts
This PR ensures that we don't try to fetch cluster-service StorageConfigs for CAPI providers.
Currently, users on GCP are seeing this error message when navigating to the "Client certificates" tab in cluster details:
With the changes of this PR, we check whether the provider supports client certificates from cluster-service before fetching them. The providers that support them should be the non-CAPI (vintage) providers (AWS and Azure).
Users should no longer see the flash error message, and also shouldn't see failed network requests fetching cluster-service StorageConfigs in the browser's console.
Users should also be able to see the MAPI CLI guide for creating a client certificate displayed in the "Client certificates" tab.
Towards our [roadmap …
=> Don't fetch cluster-service StorageConfigs for CAPI providers

src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
Fixes 2 UI bugs in the app details page:
- horizontal scrollbar displayed automatically when user is using a mouse
- app keywords not wrapping
Users should no longer see the horizontal scrollbar displayed automatically when using a mouse, and should only see it if there is horizontal overflow content.
App keywords should also wrap automatically.
**Before:**
**After:**
Closes https://github.com/giantswarm/roadmap/issues/1000 and https://github.com/giantswarm/roadmap/issues/1405
=> Fix app details UI bugs

src/components/Footer/FooterUtils.tsx
This PR changes the release notes link to point to the happa releases page for the version, replacing the link to the docs releases page.
When clicking on the "release notes" link in the footer, users should be directed to happa's releases page for the specified version.
No tracking issue, reported internally on Slack. Due to our documentation page's workflow, sometimes the link does not point to an existing page. This ensures that the the link always points to an existing page with the release notes.
=> Change web UI release notes link

src/components/MAPI/clusters/permissions/usePermissionsForClusters.ts, src/components/MAPI/utils.ts, src/model/constants/providers.ts, test/mockHttpCalls/capav1beta1/awsClusters.ts, test/mockHttpCalls/capav1beta1/index.ts, test/mockHttpCalls/capiv1beta1/clusters.ts
This PR adds support for fetching CAPA cluster resources, specifically by refactoring the `fetchProviderClusterforCluster` function to add a case for CAPA clusters. It also updates the permission hook for determining permissions to cluster resources, and adds some test mocks for CAPA clusters.
Hopefully this is sufficient enough to allow us to work concurrently on displaying cluster, node pools, and control planes details.
On a CAPA installation, users should now be able to see clusters listed in the cluster list page instead.
Closes https://github.com/giantswarm/roadmap/issues/1450.
=> Add support for fetching CAPA cluster resources

src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetVersions.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx, src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx, src/components/MAPI/clusters/utils.ts, src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx, src/components/MAPI/utils.ts, test/mockHttpCalls/capiv1beta1/clusters.ts
This PR adds support for displaying a description and a status for CAPA clusters. Only `Cluster creating…` status is supported for now.
Closes https://github.com/giantswarm/roadmap/issues/1474.
=> Display details for CAPA clusters

src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.tsx, src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx, src/components/MAPI/apps/AppInstallModal.tsx, src/components/MAPI/apps/utils.ts, src/components/UI/Inputs/FileInput/index.tsx
This PR fixes the `TypeError` encountered when we try to parse `YAMLException`s, by replacing manual formatting with the [`toString` method](https://github.com/nodeca/js-yaml/blob/0d3ca7a27b03a6c974790a30a89e456007d62976/lib/exception.js#L50) available on the `YAMLException class`.
It also fixes not being able to upload a file with the same name (but with different contents), and resets the errors when the user navigates away from the app installation form.
Closes https://github.com/giantswarm/roadmap/issues/1499.
=> Fix YAMLException error parsing for app installation

src/model/services/mapi/applicationv1alpha1/key.ts
This PR makes a small change to add support for properly displaying installed apps for CAPA - previously default apps were showing up as user-installed apps.
As we don't currently have tests for apps in organization namespaces, I added an item to our CAPA todo list for that rather than add some here. I thought it made more sense to approach that holistically.
Closes https://github.com/giantswarm/roadmap/issues/1501
=> Support displaying installed apps for CAPA

src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteAction.tsx, src/components/UI/Display/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailDeleteAction.tsx
This PR fixes a bug in the cluster deletion form's confirmation step, where a user was able to bypass inputting the cluster name as confirmation for deletion, by pressing the "Enter" key.
This is fixed by not just relying on the "Delete" button being disabled, but also adding an additional check in the deletion handler function to check if the input name matches the cluster name.
Reported internally: https://gigantic.slack.com/archives/C02FJACQ3D4/p1666270256211769
=> Fix bug in cluster deletion confirmation form

src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
App keywords and cluster labels are logically similar. This PR changes the styles of the keyword component to the styles of cluster labels.
Users will see logically similar components also visually similar.
**Before**:
Keywords (left), cluster labels (right)
**After**:
Keywords (left), cluster labels (right)
closes https://github.com/giantswarm/roadmap/issues/1191
As you can see it is not possible to use the background color of the cluster label component for the keyword component, because then the background color of the keyword component would be indistinguishable from the background.
It would be possible to change the background color of the cluster label component to the background color of the keyword component. 
I did not do that, because I think changing the color of the cluster …
=> Align style of keywords and cluster labels

src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx, src/components/MAPI/clusters/ClusterDetail/index.tsx, src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx, src/components/MAPI/clusters/ClusterStatus/ClusterStatus.tsx, src/components/MAPI/clusters/CreateCluster/index.tsx, src/components/MAPI/clusters/hooks/useClusterStatus.ts, src/components/MAPI/clusters/utils.ts, src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
This PR updates the cluster creation message displayed for GCP clusters to inform users that the creation process usually takes 5 minutes instead of 15 minutes.
Users should now see a more accurate representation of the cluster creation duration.
Closes https://github.com/giantswarm/roadmap/issues/1438.
=> Update cluster creation message for GCP

src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx, src/components/MAPI/clusters/ClusterDetail/utils.ts, src/components/MAPI/clusters/CreateCluster/patches.ts, src/components/MAPI/clusters/utils.ts, src/components/MAPI/types.ts, src/components/MAPI/utils.ts, src/components/MAPI/workernodes/utils.ts, src/model/services/mapi/infrastructurev1alpha2/index.ts, src/model/services/mapi/infrastructurev1alpha2/types.ts
Reverts giantswarm/happa#3875
While there aren't any more clusters using `awsclusters` from API group `infrastructure.giantswarm.io/v1alpha2`, there are still infrastructure references that haven't been updated to the use the new API version. This unfortunately breaks happa's checks for the API version, and we need to revert the changes of the linked PR.
=> Revert "Remove infrastructure.giantswarm.io/v1alpha2 types and checks"

src/components/Apps/AppDetail/InstallAppModal/ClusterPicker.tsx, src/components/MAPI/clusters/ClusterList/ClusterList.tsx, src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx, src/components/UI/Display/Cluster/ClusterIDLabel/index.tsx, src/components/UI/Util/Truncated.tsx
In this PR cluster name truncation limit was increased to 10 characters. In list views, if there are clusters with various name length, cluster label width is set to fit the longest name. 
Cluster list:
App installation modal > cluster selection list:
When cluster name is longer that 10 characters.
Cluster list:
App installation modal > cluster selection list:
Closes https://github.com/giantswarm/roadmap/issues/1538.
=> Display longer cluster names

.circleci/config.yml
Edit circle ci config to only build fe-docs when creating tags.
When testing the abs migration, I had to build fe-docs on every commit, to test it. I forgot to revert that change.
=> Only build fe docs when creating tags

src/components/MAPI/clusters/CreateCluster/CreateClusterAppForm.tsx, src/components/UI/JSONSchemaForm/ArrayFieldTemplate/index.tsx, src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx, src/components/UI/JSONSchemaForm/CheckboxWidget/index.tsx, src/components/UI/JSONSchemaForm/ObjectFieldTemplate/index.tsx, src/components/UI/JSONSchemaForm/SelectWidget/index.tsx, src/components/UI/JSONSchemaForm/ToggleWidget/index.tsx, src/components/UI/JSONSchemaForm/UpDownWidget/index.tsx, src/components/UI/JSONSchemaForm/index.tsx
This PR introduces a custom wrapper around `react-jsonschema-form`'s  `<Form />` component that uses our own UI form inputs. The work is still in progress.
=> Add custom json schema form wrapper

src/components/MAPI/clusters/CreateCluster/CreateClusterAppForm.tsx
This PR fixes the 2 bugs we discussed yesterday. Namely:
- submitted form data had missing fields
- form being re-rendered unnecessarily
I also added a live preview for the form data so we could more easily see what would be submitted:
JSON:
YAML:
=> Fix submitted form data and form re-rendering

jest.config.ts, src/components/MAPI/__tests__/utils.ts, src/components/MAPI/clusters/CreateCluster/ClusterNameWidget.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterAppForm.tsx, src/components/MAPI/utils.ts, src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx, src/components/UI/JSONSchemaForm/ObjectFieldTemplate/index.tsx
In this PR:
- `clusterName` and `clusterDescription` ordering was added based on the `uiSchema`.
- `ClusterNameWidget` was added to automatically generate `clusterName`. This is mostly to demonstrate how it could look like. Do we want it to be autogenerated? Do we also want to edit it manually?
- `generateUID` utility function was fixed. Before it used to cause an infinite loop when length parameter was an even number.
=> WIP Cluster app creation form fixes

src/components/MAPI/apps/AppList/utils.tsx, src/components/MAPI/apps/__tests__/utils.ts, src/components/MAPI/apps/utils.ts, src/components/MAPI/clusters/CreateCluster/CreateClusterAppForm.tsx, src/utils/helpers.ts
This PR adds basic support for resolving external schema references. This feature is currently and unfortunately not supported by `react-json-schema-form`, so we implement our own external schema resolution, which functions as follows:
- we collect all `$ref` from a cluster app schema that references a URL of http/https protocol (e.g. `$ref: https://giantswarm.schema.io/someSchema`)
- we fetch the schema from each URL and patch the original (parent) schema, so that the `$ref` now references a relative schema defined in the parent schema's `$def`
The tests accompanying this PR might shed some more light on the resolution behaviour.
Caveats:
~~- we don't currently handle external schema that reference other external schema - we only fetch from the URLs found in the parent schema~~
- …
=> Resolve external schema references

src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx, src/components/UI/JSONSchemaForm/SelectWidget/index.tsx
In this PR:
- support for displaying schema examples was added;
- `SelectWidget` was improved to support `oneOf` schema property. It will allow us to provide custom labels for select values, e.g.:
```
"servicePriorityLabel": {
"type": "string",
"oneOf": [
{"const": "lowest", "title": "Lowest"},
{"const": "medium", "title": "Medium"},
{"const": "highest", "title": "Highest"}
]
}
```
Displaying schema examples:
=> Cluster app form fields suggestions

src/components/MAPI/permissions/SubjectForm/SubjectForm.tsx
Currently the permission inspection UI in its "Group" mode restricts the user entry to group names starting with `customer:`. Recently we started to allow for additional `Dex` connectors to be configured so the group name prefix could be different. In this PR the group name restriction was removed. We still pre-fill group name input with `customer:` prefix to remind people that most likely they need it, but it's possible to delete it.
Now it's possible to submit permissions form with any group name.
Towards https://github.com/giantswarm/roadmap/issues/1697.
=> Allow to delete a group prefix in permissions overview

README.md
Replaces references to old `ginger` cluster with `gauss`
None.
`ginger` was torn down.
No.
No.
=> Replace old testing installation in README.md

src/components/MAPI/clusters/CreateCluster/ClusterNameWidget.tsx, src/components/MAPI/clusters/CreateCluster/CreateClusterAppForm.tsx, src/components/UI/JSONSchemaForm/AccordionFormField/index.tsx, src/components/UI/JSONSchemaForm/ArrayFieldTemplate/index.tsx, src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx, src/components/UI/JSONSchemaForm/CheckboxWidget/index.tsx, src/components/UI/JSONSchemaForm/ErrorListTemplate/index.tsx, src/components/UI/JSONSchemaForm/FieldErrorTemplate/index.tsx, src/components/UI/JSONSchemaForm/FieldTemplate/index.tsx, src/components/UI/JSONSchemaForm/ObjectFieldTemplate/index.tsx, src/components/UI/JSONSchemaForm/ObjectFormField/index.tsx, src/components/UI/JSONSchemaForm/SelectWidget/index.tsx, src/components/UI/JSONSchemaForm/ToggleWidget/index.tsx, src/components/UI/JSONSchemaForm/index.tsx
- Validation errors were added to the json schema form.
- `ArrayFieldTemplate` and `ObjectFieldTemplate` were refactored to share the accordion logic.
Form field errors:
Form errors:
=> Add validation errors to json schema form

src/components/MAPI/apps/ClusterDetailApps.tsx, src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
When there is an app bundle in the list of the preinstalled apps (on Vintage), child apps of that bundle were duplicated in the list of apps installed by a user. The problem is in the order of steps needed to prepare a list of apps for being displayed. The order is:
1) split all the apps into preinstalled or installed by a user;
2) filter out all the child apps of app bundles (display logic works that way that we only need a "top level" apps);
3) sort the lists by app name;
In this order, second step of filtering child apps works incorrectly when there is an app bundle in the preinstalled apps list.
In this PR the order of apps preparation steps was changed - now the filtering of the child apps happens in the beginning.
Incorrectly displayed list of user installed apps should be fixes. …
=> Fix user installed apps view

package.json, src/utils/MapiAuth/makeDefaultConfig.ts, src/utils/OAuth2/OAuth2.ts, src/utils/OAuth2/OAuth2CustomMetadata.ts, src/utils/OAuth2/OAuth2User.ts, yarn.lock
This PR replaces our fork of `oidc-client-js` with `oidc-client-ts`. The TS fork of the project has been actively maintained over the past year, and is also now suggested as a successor to `oidc-client-js`.
Some properties and methods were renamed, and some defaults have changed, but there should be no major changes to functionality.
Towards https://github.com/giantswarm/roadmap/issues/694.
=> Replace oidc-client with oidc-client-ts

src/components/MAPI/clusters/CreateCluster/CreateClusterAppForm.tsx, src/components/MAPI/clusters/CreateCluster/schemaUtils.ts
This PR adds a way for us to define UI schema to be used in the cluster app creation form.
Currently, UI schema are defined separately for each provider, with one UI schema for each major version. This is based on [previous discussions](https://github.com/giantswarm/roadmap/issues/1181#issuecomment-1340797851) we had about breaking changes in cluster apps, and we can adjust the granularity of this support if required.
A preliminary UI schema has been defined for each provider (including `Azure`, a new addition). More information about what can be defined via UI schema may be found in the [docs](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/uiSchema/), but the most relevant functionality for us would be:
- …
=> UI schema for cluster app creation form

src/components/MAPI/clusters/CreateCluster/CreateClusterAppForm.tsx, src/components/MAPI/clusters/CreateCluster/schemaUtils.ts, src/components/UI/JSONSchemaForm/FieldTemplate/index.tsx, src/components/UI/JSONSchemaForm/test.schema.json
- test schema with all the supported features was added to the json schema form prototype;
- `asterisk` sign was added to the required fields labels.
Test schema is selected:
Provider schema is selected:
Asterisk sign in the required field label:
=> Test schema for JSON schema form

renovate.json
A new group for `react-jsonschema-form` packages was added to the `renovate` config.
=> Add react-jsonschema-form group to renovate config

package.json, src/components/MAPI/clusters/CreateCluster/CreateClusterAppBundles.tsx, src/components/UI/JSONSchemaForm/test.schema.json
By default, the `@rjsf/validator-ajv8` uses the `draft-07` schema version. In this PR, validator was customized to use `draft-2020-12` version. It allows us to specify the latest draft for schemas, like this
```
{
"$schema": "https://json-schema.org/draft/2020-12/schema"
}
```
=> JSON schema form 2020-12 draft support

src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap, src/components/UI/Inputs/TextArea/index.tsx
Fixes a bug introduce in https://github.com/giantswarm/happa/pull/4095 so the value passed to `<TextArea />`  component is actually displayed.
No tracking issue, we saw this during refinement.
=> Fix displaying values passed to TextArea component

src/components/MAPI/clusters/CreateCluster/CreateClusterAppBundles.tsx, src/components/MAPI/clusters/CreateCluster/__tests__/schemaUtils.ts, src/components/MAPI/clusters/CreateCluster/schemaUtils.ts, src/utils/helpers.ts
This PR adds support for removing schema fields during the schema preprocessing step. This allows us to specify fields to omit from JSON schema for both the form data and the form UI.
An example use case for this functionality is the `internal` field for cluster app schema. The removal of this field during preprocessing has also been implemented by this PR.
Towards https://github.com/giantswarm/roadmap/issues/2052 and https://github.com/giantswarm/roadmap/issues/1181.
=> Support removing schema fields

src/components/MAPI/clusters/CreateCluster/schemaUtils.ts, src/components/UI/JSONSchemaForm/ObjectFieldTemplate/index.tsx
This PR allows hiding schema fields in the JSON schema form UI via the `ui:widget: hidden` UI schema configuration. Note that this differs from the mechanism in https://github.com/giantswarm/happa/pull/4112, in that it only hides the display of the field but still allows values for that field in form data.
Towards https://github.com/giantswarm/roadmap/issues/2052 and https://github.com/giantswarm/roadmap/issues/1181
=> Allow hiding schema fields

src/components/MAPI/clusters/CreateCluster/schemaUtils.ts
This PR hides properties that are currently part of the schema for internal purposes only, but should be filled in automatically e. g. by operators.
The form appears more clean and does not offfer input widgets for purely internal settings.
There is more detail in https://github.com/giantswarm/roadmap/issues/1733
Not necessary
=> Hide Azure cluster app schema properties

src/components/MAPI/clusters/CreateClusterAppBundles/schemaUtils.ts
This PR adds configuration to improve the AWS CAPI cluster creation form by
- Hiding unwanted properties
- Sorting properties
- Customizing certain properties (instance type, cluster name)
See below
Issue https://github.com/giantswarm/roadmap/issues/1181
No
No
=> Re-arrange AWS cluster creation form properties, hide some

.circleci/config.yml
This PR removes the job that pushes happa to the shared app collection catalog, as the catalog will be archived in 2 weeks.
Towards https://github.com/giantswarm/roadmap/issues/2355
Nothing special.
No.
No.
=> Remove shared app collection from circle CI

ats/test-values.yaml, helm/happa/values.schema.json, helm/happa/values.yaml
This PR removes `kubernetes.auth.controlPlaneAdminTargetGroup` from happa's `values.yaml`. We don't currently use this value anywhere within the codebase, and its value is currently [configured](https://github.com/giantswarm/config/blob/7003df373c606d9db26c6ea8d4a4a7c004acf450/default/apps/happa/configmap-values.yaml.template#L28) in `config` to overlap with `oidc.giantswarm.writeAllGroups`.
No tracking issue. We realized with the changes in https://github.com/giantswarm/config/pull/1743 that the value doesn't seem to be used and is a duplicate.
=> Remove `kubernetes.auth.controlPlaneAdminTargetGroup`

src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetControlPlaneNodes.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetKubernetesAPI.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetVersions.tsx, src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx, test/mockHttpCalls/capiv1beta1/clusters.ts
This PR adds tests for cluster details features on CAPZ so that they have the same coverage as other providers.
Towards https://github.com/giantswarm/giantswarm/issues/25907.
=> Add tests for cluster details on CAPZ

README.md, docs/Release.md
The README and release docs contained some broken links and outdated info that should be updated by this PR.
Closes https://github.com/giantswarm/roadmap/issues/2107.
=> Update readme and release documentation

helm/happa/templates/happaapi-ingress.yaml
When a user is a member of many AD groups authentication header can become bigger than a limit NGINX sets by default (8KB). As a result requests to the API are being aborted. In this PR, header size limit was increased for happa API ingress.
=> Increase NGINX header size for happa API

helm/happa/templates/happaapi-ingress.yaml
`large_client_header_buffers` Ingress configuration was deleted. We will need to configure it again when `allow-snippet-annotations` is enabled on all MCs.
Towards https://github.com/giantswarm/adidas/issues/1133.
=> Roll back Happa API ingress configuration change

src/components/MAPI/clusters/CreateClusterAppBundles/ClusterAppSchemaTester.tsx, src/components/MAPI/clusters/CreateClusterAppBundles/CreateClusterAppBundlesForm.tsx, src/components/MAPI/clusters/CreateClusterAppBundles/index.tsx, src/components/UI/JSONSchemaForm/ErrorListTemplate/ErrorList.tsx, src/components/UI/JSONSchemaForm/ErrorListTemplate/ValidationStatus.tsx, src/components/UI/JSONSchemaForm/ErrorListTemplate/index.tsx, src/components/UI/JSONSchemaForm/index.tsx
This PR improves the display of validation errors in the cluster creation form to align with the spec.
As the the default error list component from `react-json-schema-form` is only rendered when there are errors, we handle displaying the error list outside of the library's form component to allow displaying an `OK` status when there are no validation errors.
Validation OK (default state):
Tooltip displayed when hovering over the info icon displays more information regarding validation:
Error states:
The "Create cluster now" button is also displayed in a disabled state when there are validation errors:
Towards https://github.com/giantswarm/roadmap/issues/2431.
=> Improve display of validation errors in cluster creation form

src/components/MAPI/apps/utils.ts, src/components/MAPI/clusters/Cluster.tsx, src/components/MAPI/clusters/CreateClusterAppBundles/CreateClusterStatus.tsx, src/components/MAPI/clusters/CreateClusterAppBundles/index.tsx, src/components/UI/Display/ErrorMessage/index.tsx, src/components/UI/Display/MAPI/clusters/ClusterCreationStatus/index.tsx, src/components/UI/Display/StatusList/StatusListItem.tsx, src/components/UI/Display/StatusList/index.tsx, src/model/constants/routes.ts, src/model/services/mapi/applicationv1alpha1/createApp.ts, yarn.lock
Cluster creation progress UI was added to the cluster creation flow.
Node pools section that is present in the specs was not implemented in this version. It would require additional investigation and could be implemented in a separate PR.
Error handling implementation is a little bit different from the specs - if an error happens during the initial app resources creation (on form submit), it's being displayed immediately on the form page, above the submit button, and redirection to the progress step doesn't happen. All other errors are being displayed on the progress page, according to the specs.
Towards https://github.com/giantswarm/roadmap/issues/2431.
=> Add cluster creation progress UI

renovate.json
Some not critical packages are being updated much more often than others. It significantly increases overall CI build time. In this PR update schedule for some packages was set to be once per week.
Closes https://github.com/giantswarm/roadmap/issues/1589.
=> Change renovate schedule for some packages

src/components/UI/JSONSchemaForm/__tests__/schemaUtils.ts, src/components/UI/JSONSchemaForm/schemaUtils.ts, src/components/UI/JSONSchemaForm/utils.ts
In our implementation we clean up generated form data from the default values. The way how the default values are being populated into the form data was changed in the [5.7.0](https://github.com/rjsf-team/react-jsonschema-form/releases/tag/v5.7.0) release of the `react-jsonschema-form` library. It broke our cleanup function. In this PR several improvements were made:
- implicit default values ('', [], {}, false, etc.) are being deleted from the schema during the schema preprocessing step.
- additional check for default values of array properties were added.
- when there is a referenced schema for a property, it's being merged with "local" schema. Otherwise default values were missing when they were overridden in local schema.
Broken user config before:
After:
Towards …
=> Payload cleaning fix

src/model/constants/docs.ts
Updates the docs URL that we use when indicating that a cluster is managed via gitops.
The user will land on the page with the relevant content section. Currently, the user gets sent to the Gitops overview page https://docs.giantswarm.io/advanced/gitops/#web-ui-restrictions by redirection.
No visible change
n/a
If yes, please apply one of the following labels: `kind/feature`, `kind/change`, `kind/bug`, `kind/removal`, `kind/ux-enhancement`, `kind/security`
=> Update docs URL for GitOps icon

__tests__/Apps.js, src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.tsx, src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx, src/components/MAPI/apps/AppInstallModal.tsx, src/components/MAPI/apps/__tests__/utils.ts, src/components/MAPI/apps/utils.ts
This PR removes deprecated exceptions for the `nginx-ingress-controller-app`.
`nginx-ingress-controller-app` does not get installed to `kube-system` by default anymore.
(Please add screenshots or screen recordings demonstrating the change.)
The `ingress-controller-values` are not used and the upcoming major release isn't called `nginx-ingress-controller-app` anymore.
No.
=> Apps: Remove exceptions for `nginx-ingress-controller-app`.

Dockerfile, nginx/nginx.conf
Relevant [issue](https://github.com/giantswarm/roadmap/issues/3220)
Update nginx server image to support NDK & LUA
Allow us to expose an endpoint `/jwt-token` via nginx, that reads the `Teleport-Jwt-Assertion` header and write as response.
=> NGINX modules ndk,lua + route for teleport

.circleci/config.yml, Dockerfile.fe-docs, helm/fe-docs/ci/ci-values.yaml, helm/fe-docs/templates/deployment.yaml, helm/fe-docs/templates/ingress.yaml, helm/fe-docs/values.schema.json, helm/fe-docs/values.yaml, nginx/fe-docs-nginx.conf
Towards https://github.com/giantswarm/giantswarm/issues/29470
This PR attempts to make the fe-docs chart deployable on k8s 1.25
Included changes:
- Adds security details to values.yaml which are already applied in the chart
- Updates schema for values.yaml
- Adds ci values
- Sets explicit NGINX configuration for fe-docs
- Updates nginx-unprivileged to 1.25
- Sets separate liveness probe path
=> Adapt fe-docs chart for new operations cluster

helm/fe-docs/Chart.yaml, helm/happa/Chart.yaml
Team annotations should not carry the `team-` prefix.
=> Fix team annotation value

helm/happa/templates/deployment.yaml
Mitigates these kubelinter complaints as seen [here](https://app.circleci.com/pipelines/github/giantswarm/happa/18443/workflows/1c2cfa20-90fa-4b52-9f39-a49b2f9b93b7/jobs/134668):
```
/root/project/helm/happa/templates/deployment.yaml: (object: giantswarm/happa apps/v1, Kind=Deployment)
container "happa" does not expose port 8000 for the HTTPGet (check: liveness-port, remediation:
Check which ports you've exposed and ensure they match what you have specified in the liveness probe.)
/root/project/helm/happa/templates/deployment.yaml: (object: giantswarm/happa apps/v1, Kind=Deployment)
container "happa" does not expose port 8000 for the HTTPGet (check: readiness-port, remediation:
Check which ports you've exposed and ensure they match what you have specified in the readiness probe.)
```
=> Expose container port explicitly to mitigate kubelinter complaint

.circleci/config.yml
Exclude the main branch from CircleCI runs
https://github.com/giantswarm/giantswarm/issues/31824
No
No
=> Prevent job runs for commits to default branch

helm/happa/templates/happaapi-ingress.yaml, helm/happa/values.schema.json, helm/happa/values.yaml
Extends allowed origins for Happa API ingress.
Support for more allowed origins.
N/A
See this [issue](https://github.com/giantswarm/giantswarm/issues/32009)
A review of the proposed change.
Nope.
IDK, should it?
=> Extend allowed origins

src/components/UI/Controls/Navigation/MainMenu.js
Towards https://gigantic.slack.com/archives/C01RPJ7TSCE/p1750161492488549?thread_ts=1748341853.182179&cid=C01RPJ7TSCE and https://github.com/giantswarm/giantswarm/issues/33560
This PR removes the orgID parameter from the happa monitoring link because users might not have access to this organization.
(Please add screenshots or screen recordings demonstrating the change.)
(Please link public issues or summarize if not public.)
If yes, please apply one of the following labels: `kind/feature`, `kind/change`, `kind/bug`, `kind/removal`, `kind/ux-enhancement`, `kind/security`
=> Remove orgId from happa link

.circleci/config.yml, Dockerfile, ats/test-values.yaml
Changes Dockerfile and more to use gsoci.azurecr.io in favour of quay.io
Towards https://github.com/giantswarm/roadmap/issues/3935
=> Switch image registry to gsoci
