package.json
src/components/organizations/detail.js
src/components/users/user_row.js

This fixes a potential vulnerability which didn't affect us, as it was related to server side rendering, but I would like to get rid of the warning.
I also had to upgrade webpack-related modules in order to make the sev-server work again. And I fixed quoting warnings I had introduced myself.

Upgrade react-dom to 16.4.2

---

docker-compose.yml

This adds env variables to the dev setup for the recent changes to passage.

Add env variables for fixed passage.

---

src/components/users/user_row.js
src/index.html
src/styles/_base.sass
src/styles/components/_cluster_dashboard.sass
src/styles/components/_configure_containers.sass
src/styles/components/_node_table.sass
src/styles/components/_release_selector.sass
src/styles/components/_table.sass
src/styles/vendor/_simple-grid.scss

For https://github.com/giantswarm/giantswarm/issues/4276

Heavier fonts

---

src/components/organizations/cluster_key_pairs.js
src/styles/_base.sass
src/styles/components/_form.sass
src/styles/components/_modal.sass

For https://github.com/giantswarm/giantswarm/issues/4275

Add validation for the CN prefix in key pair creation

---

src/components/organizations/cluster_key_pairs.js

This should fix https://github.com/giantswarm/giantswarm/issues/4445

Relax CN prefix validation to allow for email addresses

---

src/components/button/index.js
src/components/organizations/cluster_detail.js
src/styles/_base.sass
src/styles/components/_create_cluster.sass
src/styles/components/_progress_button.sass

Just some cosmetic fixes to the loading spinners.
Also makes sure the cluster detail screen shows a loader while there is no content loaded yet.

Add loader to cluster detail screen. Fix some loader positions.

---

src/components/create_cluster/new_aws_worker.js

Towards: https://github.com/giantswarm/giantswarm/issues/4498

Add more c5 instance types.

---

package.json

Tested locally in dev. Waiting for CI for the prod build.

Upgrade webpack to 4.25.1

---

src/actions/actionTypes.js
src/actions/clusterActions.js
src/actions/organizationActions.js
src/components/modal/index.js
src/reducers/modalReducer.js
src/reducers/organizationReducer.js

For more intuitive understanding of what they really mean.

Rename redux actions and types from *confirm to *confirmed

---

README.md

Add Quay and CircleCI badge to README

---

src/components/layout.js

Towards https://github.com/giantswarm/happa/issues/125

Decrease timeout to 10s from default 60s.

---

Makefile
package.json
src/components/create_cluster/index.js
src/reducers/appReducer.js
yarn.lock

Towards https://github.com/giantswarm/giantswarm/pull/2202.

adds option to pick number of availability zones when creating clusters

---

src/components/organizations/cluster_detail.js

Towards https://github.com/giantswarm/giantswarm/pull/2202.

shows AZ in cluster details page

---

src/components/organizations/detail.js

As noticed / requested by @xh3b4sd here: https://gigantic.slack.com/archives/C13MG9F0W/p1543330855000700

Allow the cluster detail button to open in a new tab

---

docker-compose.yml

This fixes the network settings to work with the API testing setup.

Fixes links and networking in docker-compose

---

src/components/users/index.js

Fixes: https://github.com/giantswarm/giantswarm/issues/4819

Ensure we have a fresh token when trying to invite.

---

src/components/create_cluster/index.js
src/components/create_cluster/new_kvm_worker.js
src/components/create_cluster/number_picker.js
src/components/organizations/scale_cluster_modal.js
src/styles/components/_create_cluster.sass
src/styles/components/_flash_messages.sass
src/styles/components/_nav.sass
src/styles/components/_number_picker.sass

Towards: https://github.com/giantswarm/giantswarm/issues/3824
Also fixes some styles for KVM's create cluster screen:
before:
after:

Allow user input in number picker.

---

src/components/create_cluster/index.js

I made some changes to the number picker, this updates the feature-auto-scaling branch so it works as expected.

Update min max scaler for new number picker

---

src/components/create_cluster/index.js
src/components/create_cluster/vm_size_selector.js

Brings back the azure vm size selector, now that the create cluster form has changed somewhat.

Add azure vm size selector

---

.circleci/config.yml

Towards https://github.com/giantswarm/giantswarm/issues/4874
This adds lighthouse report comparison between master and the feature branch, as seen in https://github.com/giantswarm/giantswarmio-webapp/pull/527

Compare lighthouse reports

---

.circleci/config.yml
package.json
yarn.lock

Closes https://github.com/giantswarm/giantswarm/issues/4996

Upgrade bootstrap

---

README.md

Little improvement on the last PR

Let pre-commit hook only fire when JavaSript files have changed

---

src/components/cluster_detail/cluster_detail_table.js
src/components/cluster_detail/index.js

A straight up extraction of the lines related to just the table in the cluster details screen.
Has further refactoring potential, but starting with this.

Extract cluster detail table into a component.

---

src/components/getting-started/2_configure_kubectl.js

Towards: https://github.com/giantswarm/giantswarm/issues/5032

Update gsctl download instructions in Happa

---

package.json
src/components/cluster_detail/key_pairs.js
yarn.lock

Towards https://github.com/giantswarm/happa/issues/316

Add debounce function for CN prefix validation

---

src/components/organizations/credentials.js

The order that you enter these credentials is not the same that they are displayed.

Fix order of credentials

---

src/components/layout.js
src/components/navigation/index.js

It wasn't firing the 'select organization' function anymore,
because I didn't take it with me during the refactoring.

Fix the org selector dropdown

---

src/actions/clusterActions.js
src/components/cluster_detail/cluster_detail_table.js
src/components/cluster_detail/scale_cluster_modal.js

Some fixes for happa's autoscaling changes

Adjust labels in cluster details and scaling

---

src/components/cluster_detail/index.js
src/components/cluster_detail/key_pairs.js
src/components/cluster_detail/upgrade_cluster_modal.js
src/components/create_cluster/release_selector.js
src/components/flash_messages/index.js
src/components/getting-started/2_configure_kubectl.js
src/components/home/index.js
src/components/layout.js
src/components/modals/release_details_modal.js
src/components/navigation/index.js
src/components/organizations/detail.js
src/components/organizations/index.js
src/components/users/index.js
src/lib/helpers.js
src/reducers/appReducer.js
src/reducers/clusterReducer.js

In Happa we occasionally used underscore to map over an array and other times just normal native javascript.
This is an effort to standardize and reduce dependencies at the same time.

Replace underscore's map with native javascript map.

---

README.md

Attempt to improve the happa dev docs a bit

Development docs update

---

src/components/account_settings/change_email_form.js
src/components/account_settings/change_password_form.js
src/components/cluster_detail/cluster_detail_table.js
src/components/cluster_detail/key_pairs.js
src/components/create_cluster/new_kvm_worker.js
src/components/flash_messages/flash_message.js
src/components/forgot_password/index.js
src/components/getting-started/0_overview.js
src/components/getting-started/1_download_kubectl.js
src/components/getting-started/2_configure_kubectl.js
src/components/getting-started/2_configure_kubectl_alternative.js
src/components/getting-started/3_simple_example.js
src/components/getting-started/4_next_steps.js
src/components/getting-started/codeblock.js
src/components/getting-started/fileblock.js
src/components/navigation/index.js
src/components/organizations/credentials.js
src/components/organizations/organization_row.js
src/components/shared/aws_account_id.js
src/components/shared/cluster_id_label.js
src/components/users/index.js
src/index.html
src/styles/components/_component_slider.sass

Towards https://github.com/giantswarm/giantswarm/issues/5378
This replaces our Font Awesome icons with ones from Material Design.
Current library:
New library:

Replace Font Awesome with Material Design icons

---

src/components/create_cluster/aws_instance_type_selector.js
src/components/create_cluster/vm_size_selector.js

Aftermath for https://github.com/giantswarm/giantswarm/issues/5378, replacing a forgotton icon

Replace bars icon with menu

---

src/components/organizations/credentials.js

Towards https://gigantic.slack.com/archives/C13MG9F0W/p1550752550018200

Add role name in credentials inputs

---

.circleci/config.yml
scripts/start.sh

Link commit hash to GitHub commit URL

---

src/components/app.js
src/components/auth/oauth_callback.js

I found it confusing that some components were imported here using local names instead of simply the component name.

User CamelCase component names in app.js

---

src/components/account_settings/change_email_form.js
src/components/account_settings/change_password_form.js
src/components/auth/login.js
src/components/auth/oauth_callback_debug.js
src/components/cluster_detail/expiry_hours_picker.js
src/components/cluster_detail/key_pairs.js
src/components/cluster_detail/upgrade_cluster_modal.js
src/components/create_cluster/release_selector.js
src/components/flash_messages/flash_message.js
src/components/forgot_password/index.js
src/components/forgot_password/set_password.js
src/components/getting-started/1_configure_kubectl.js
src/components/getting-started/1_configure_kubectl_alternative.js
src/components/getting-started/2_simple_example.js
src/components/getting-started/codeblock.js
src/components/getting-started/fileblock.js
src/components/modals/index.js
src/components/modals/release_details_modal.js
src/components/organizations/detail.js
src/components/shared/cluster_id_label.js
src/components/shared/email_field.js
src/components/shared/input_field.js

This PR removes all constructors that
- do nothing
- only initialize state
and fixes a few possible bugs along the way

Remove or simplify constructors

---

src/styles/components/_form.sass

Fixes https://github.com/giantswarm/giantswarm/issues/5379

Make input field selector not match radio, checkbox

---

src/components/getting-started/0_overview.js
src/styles/components/_step_selector.sass

Fixes https://github.com/giantswarm/giantswarm/issues/5470
- Increase font size
- Use flexbox layout
- Derive colors from background color

Improve rendering of getting started front page

---

src/components/account_settings/change_password_form.js

Fixes https://github.com/giantswarm/giantswarm/issues/5467
This makes the password change form functional again.

Fix password change request payload

---

src/components/users/index.js

Fixes https://github.com/giantswarm/giantswarm/issues/5534

Fix expiry status in users list

---

src/components/cluster/new/view.js

Fixes https://github.com/giantswarm/giantswarm/issues/5468
Preview

Move release selection up in cluster creation form

---

docs/Release.md

As discussed on Slack https://gigantic.slack.com/archives/C13MG9F0W/p1553512913030900

Publish semver versioning guidelines

---

src/components/cluster/detail/cluster_detail_table.js
src/components/home/cluster_dashboard_item.js

plus one additional error regarding RefreshableLabel supporting exactly one child.

Fix access to undefined workers array on cluster details page

---

src/components/cluster/detail/cluster_detail_table.js

Capitalize scaling labels

---

src/components/cluster/detail/view.js
src/components/home/cluster_dashboard_item.js

Labels change with k8s 1.14 - this is basically the same PR as https://github.com/giantswarm/gsctl/pull/352 for gsctl. 
I tested this briefly on gauss and everything seems to be working fine.

Add label checks for labels used in k8s 1.14

---

src/lib/password_validation.js

Continued from: https://github.com/giantswarm/happa/pull/563
related to: https://github.com/giantswarm/happa/issues/234

Fix empty password is not valid anymore

---

CONTRIBUTORS.md

This PR adds a CONTRIBUTORS.MD file to acknowledge contributions to Happa from the community.

Add contributors.md file.

---

src/components/cluster/detail/key_pair_details_modal.js

This aligns creation and expiry date display

Add time zone and relative date for key pair creation

---

src/components/cluster/new/view.js
yarn.lock

Hiding this row when on Azure or KVM:
it is of no value to the user here and is more in the way.

Remove availability zones in case provider != aws

---

src/components/cluster/detail/cluster_apps.js

Use the right version field.

---

.gitignore
src/components/cluster/detail/view.js

From now on we let all users upgrade clusters

Remove admin conditional in upgrade action

---

package.json
src/actions/clusterActions.js
src/components/app_catalog/detail/fileinput.js
src/components/app_catalog/detail/install_app_form.js
src/components/app_catalog/detail/install_app_modal.js
src/components/cluster/detail/view.js
yarn.lock

This adds a way for users to upload a `values.yaml` file during app creation which will get correctly associated with the app they are creation.

Add a way to upload values.yaml during app installation.

---

package.json

This got through, would like to correct it before releasing.

Go back to master branch.

---

.eslintrc
src/components/getting-started/0_overview.js
src/components/getting-started/1_configure_kubectl.js
src/components/getting-started/2_simple_example.js
src/components/getting-started/3_next_steps.js

According to what I read, not having a type attribute on a button can be "bad".

Enforce button type

---

src/components/account_settings/change_email_form.js

Removes an unnecessary constructor, renames the state variables for better readability

ChangeEmailForm: remove constructor, rename state variables

---

src/components/UI/cluster_name.js
src/components/cluster/detail/view.js
src/styles/components/_form.sass

Towards https://github.com/giantswarm/happa/pull/600

Move ClusterName component into UI

---

src/components/UI/refreshable_label.js

Changing the notation from JS objects to CSS string.

Use string notation for emotion/styled

---

Dockerfile
helm/happa-chart/templates/deployment.yaml
helm/happa-chart/templates/psp.yaml
helm/happa-chart/templates/rbac.yaml
helm/happa-chart/templates/service-account.yaml
helm/happa-chart/values.yaml
nginx.conf

Towards giantswarm/giantswarm/issues/6013

Add serviceaccount, psp and supporting rbac

---

.circleci/config.yml

This is me trying something based on ograu's test setup branch https://github.com/giantswarm/happa/pull/620

Try to use node 10.16.0 in Circle

---

src/components/UI/app_container.js
src/components/UI/app_details/index.js
src/components/UI/navigation/index.js
src/components/app_catalog/app_list/index.js
src/components/app_catalog/catalogs/index.js
src/components/app_catalog/detail/index.js
src/components/app_catalog/index.js
src/components/cluster/detail/cluster_apps.js
src/components/layout.js
src/styles/components/_app_catalog.sass

We'd like to add some more text to the catalog descriptions, currently that doesn't work so good in the layout we have.
These are some quick changes for now.

Adjust catalog overview to allow for more text in the descriptions.

---

src/components/app_catalog/catalogs/index.js

I only see it in production, but the small loading spinners for the catalogs are sometimes spinning off axis and it looks very silly.

Try to fix a weird behaviour of the loading spinner.

---

src/components/app_catalog/detail/install_app_modal.js

Adjust the max length for an app name.

---

src/components/app.js
src/styles/index.js
src/styles/theme.js

Added styles/index.js and moved theme.js to styles folder because I think it makes more sense

Styles library

---

src/components/UI/empty_state_display.js
src/components/organizations/list/index.js

A quick little refactoring we discussed earlier today in slack.
I'll probably use this EmptyStateDisplay component in a few more places later.

Refactor conditional into new EmptyStateDisplay component.

---

src/components/app_catalog/app_list/index.js

We are returning the first app of the index.yaml but sometimes it is not served order by date. We need to order first to pick first up

WIP Consider data in the index.yaml for getting first app

---

src/components/app_catalog/app_list/index.js

I knew I felt a bit suspicious about that `pop` :)

Fix bug when visiting the app list more than once

---

.circleci/config.yml

Towards https://github.com/giantswarm/giantswarm/issues/6621

Remove lighthouse installation from CI tools step

---

src/components/UI/availability_zones_label.js
src/components/UI/availability_zones_labels.js

`key` is not a prop, it's for React's internal use.

Fix proptypes on AvailabilityZonesLabels

---

src/components/cluster/detail/cluster_detail_table.js

And underscore library removed as it can be done with vanilla JS

Simplified props for readibility in ClusterDetailTable

---

src/actions/catalogActions.js

Do not show internal catalogs in Happa.

---

src/components/cluster/new/view.js

As a follow-up from support questions, this adds some info regarding storage usage for KVM.

Add info on KVM node storage use and size

---

src/components/UI/catalog_type_label.js

I think it's best to keep our console clean of errors or warnings. Here is how I think we shoud proceed in case of ESLint warning:
- Change the line/s responsible of triggering this error, or
- Change/remove the rule

Double to single quotes

---

src/actions/clusterActions.js

Though I know it is not sctricly necessary, I had to do it, couldn't help it 🤓

Concise syntax & implicit return

---

src/components/cluster/detail/cluster_detail_node_pools_table.js
src/utils/cluster_utils.js

Fix, comment and simplify RAM and CPU calculations for node pools clusters

Fix RAM and CPUs in NPs Clusters

---

src/components/UI/view_edit_name.js

Quick fix to my own PR: we should not be touching the dom when accessing DOM values.

Fix dom touching

---

src/components/UI/view_edit_name.js

Remove unused variable (my fault, sorry)

Removed variable & warning

---

src/actions/clusterActions.js
src/reducers/clusterReducer.js

- Extracted impure logic to actions 
- Reducer with Immer
ps: I am testing manually and everything seems to work 🤞

Immutable Cluster reducer

---

src/actions/releaseActions.js
src/reducers/releaseReducer.js

- Immer in reducer
- Moved logic to actions
- Short syntax for action creators

Immutable Releases reducer

---

src/reducers/organizationReducer.js

⚠️ ⚠️ ⚠️ Can't test deletion of organization, never worked on my local Happa ⚠️ ⚠️ ⚠️

Immutable Organization reducer

---

src/actions/clusterActions.js
src/components/home/index.js
src/mockedStatus.js
src/reducers/clusterReducer.js
src/utils/cluster_utils.js

Now it is working, but I wouldn't merge this to master. 
Not proud at all of this code 😢 
- Fix conditionals for checking status in `clusterUtils`
- Added hardcoded `status` object for developing
- Commented refresh function: `Home` component has to be rewritten as now we have an immutable store and what made sense before (force re-renderings, deep comparisions) now not only doesn't make sense but also kind of clashes with what we have done with Immer.
Also I think that that actions should be redefined, simplified and some of them removed.

Fix number of Nodes, CPU and RAM

---

webpack.dev.js

0.0.0.0 triggers an error in auth0.com

0.0.0.0 to localhost

---

src/components/cluster/detail/scale_cluster_modal.js

Fixes a bug when trying to scale clusters.

Fix params for cluster patch

---

src/actions/clusterActions.js

Should help with the issues we are experiencing in one case.
ping @JosephSalisbury

Be ok with 404 status responses.

---

src/components/UI/dropdown_menu.js
src/components/UI/view_edit_name.js
src/components/cluster/detail/node_pool.js
src/components/cluster/detail/node_pool_dropdown_menu.js

- Conditional styles for node pools in `ViewAndEditName`
- Trigger edit mode from dropdown

Node pool name edit

---

helm/happa-chart/templates/network-policy.yaml
helm/happa-chart/values.yaml

towards giantswarm/giantswarm/issues/4383
(blocks giantswarm/g8s-oauth2-proxy/pull/11)

Network policy

---

src/components/app.js
src/components/cluster/detail/__tests__/cluster_details_node_pools_table.js
src/lib/giantswarm_client_wrapper.js
src/stores/configureStore.js
test_utils/initialState.js
test_utils/renderRouteWithStore.js

The way I made a weird singleton out of `history` and `store` was confusing things in the tests.
Also the way `initialState` was implemented means that it is shared between test cases, which confused things for me a bit as well.
These changes make it possible to really test the full 'stack' of the app, make sure that things navigate and render the right components.

Fix history and initialState sharing.

---

.circleci/config.yml
__tests__/login.js
package.json
src/components/auth/login.js
yarn.lock

This adds an integration test for logging in.
The boundary are the actual network requests to the API, which are mocked using `nock`. 
Nock works by overriding Node's http.request function. 
https://github.com/nock/nock
The stuff under `GIVEN` could be extracted somehow into a 'Happy API setup' function somehow.
Since I think we will be repeating it often.

Add a login test.

---

__tests__/login.js
test_utils/mockHttpCalls.js

To reuse nock function and responses. WDYT?

Added nock utils

---

__tests__/login.js

I adjusted a little bit the way I do the given/when/then commenting, no need for the capitalization or the indentation.

Finish up the login tests.

---

src/components/UI/ValidationErrorMessage.js
src/components/UI/number_picker.js
src/components/cluster/new/aws_instance_type_selector.js
src/components/cluster/new/view.js
src/components/shared/input_field.js
src/styles/theme.js

For consistency. Added a new UI component that takes a string and renders a span.
Before: 
After:

Unified validation messages

---

src/components/cluster/detail/expiry_hours_picker.js
src/components/cluster/detail/key_pair_create_modal.js
src/components/cluster/detail/key_pairs.js
src/lib/helpers.js
src/styles/components/_create_key_pair.sass
src/styles/components/_expiry_hours_picker.sass

Towards: https://github.com/giantswarm/giantswarm/issues/6924
Related to: https://github.com/giantswarm/gsctl/pull/435

Add internal api endpoint toggle to key pair creation on AWS

---

src/components/cluster/detail/cluster_detail_node_pools_table.js
src/components/cluster/detail/node_pool.js

@marians just realized that *NAME* heading was not properly alligned with its value above and corrected it:

Fix nth child warning (2)

---

src/components/cluster/new/ReleaseSelector.js
src/components/cluster/new/view.js

Release selector in one line

---

src/components/cluster/detail/cluster_detail_node_pools_table.js
src/index.html

Added message in v5 cluster view when there are no node pools

---

src/index.html

And so avoid warnings of default type being incorrect in cluster creation and node pools creation forms

Added default instance type to global config

---

src/components/cluster/new/NewCluster.js

Forgot to add this in previous PR...

Azure installations cant acces v5 form

---

src/actions/__mocks__/organizationActions.js
src/actions/organizationActions.js
src/components/UI/organization_list/index.js
src/components/UI/organization_list/row.js
src/components/layout.js
src/components/organizations/detail/index.js
src/components/organizations/index.js
src/components/organizations/list/index.js

Fixes giantswarm/giantswarm#6632 and giantswarm/giantswarm#6875

Fix organization navigation

---

__tests__/logout.js
src/components/cluster/__tests__/cluster_managament.js
src/components/cluster/detail/AddNodePool.js
src/components/cluster/detail/ClusterDetailTable.js
src/components/cluster/detail/cluster_detail_node_pools_table.js
src/components/cluster/detail/scale_node_pool_modal.js
src/components/cluster/new/CreateNodePoolsCluster.js
src/components/home/cluster_dashboard_item.js
src/index.html

This was the checks, fixes and cleanups that I was doing when `unhide-nodepools` branch was accidentally merged

Unhide nodepools fixes and cleanup

---

src/components/cluster/detail/cluster_detail_node_pools_table.js

Closes https://github.com/giantswarm/giantswarm/issues/7562

Remove number from INSTANCE TYPE column header

---

src/components/app.js

Ensures we don't send exceptions when working locally but talking a live API.

Don't report exceptions in dev envs

---

.gitignore
.vscode/launch.json
webpack.common.js

Fixes giantswarm/giantswarm#7807
Been trying to get this to work for years!
Also added the vscode configuration, so when anyone who has the project opens it with VSCode, they'll have the debug configuration already there

Add debugging configuration for VSCode

---

src/reducers/userReducer.js

Immutable userReducer

---

webpack.prod.js

Then I can use it when `api` receives an exception notification.

Generate and publish source map in production.

---

src/components/UI/app_details/body.js
src/components/UI/app_details/item.js
src/components/app_catalog/app_detail/InstallAppForm.js
src/components/app_catalog/app_detail/InstallAppModal.js
src/components/app_catalog/app_list/AppList.js
src/components/app_catalog/catalog_list/CatalogList.js
src/components/cluster/detail/ClusterApps.js
src/components/cluster/detail/KeyPairCreateModal.js

Replaces `<React.Fragment></React.Fragment>` with `<></>` everywhere.

Use short form of React.Fragment

---

src/actions/clusterActions.js

Related to: https://github.com/giantswarm/giantswarm/issues/7979

Remove org filter from cluster load action.

---

package.json
src/components/Layout.js
yarn.lock

- Fix https://github.com/giantswarm/happa/network/alert/yarn.lock/serialize-javascript/closed
- Remove leftover git conflict markup

Update the serialize javascript dependency

---

.eslintrc

I pushed accidentally to master 🤦‍♂ 
Reverting this last change.
Aaand sorry for the mess in committs history!

Revert changes in master

---

.eslintrc

Are you ok deleting this? I think it doesn't make much sense ...

Remove ESLint no-use-before-define

---

src/actions/appActions.js
src/actions/appConfigActions.js
src/actions/appSecretActions.js
src/actions/catalogActions.js
src/actions/clusterActions.js
src/actions/userActions.js
src/lib/patchedAirbrakeRequester.js
src/shared/constants/index.js
src/shared/constants/statusCodes.js

Fixes https://github.com/giantswarm/giantswarm/issues/8275
- Create constants for all common HTTP status codes
- Replace all magic number status code usage with constants

Create and use constants for all common HTTP status codes

---

yarn.lock

my yarn.lock after running yarn

---

__tests__/Organization.js
src/components/Modals/Modals.js
testUtils/mockHttpCalls/constantsAndHelpers.js

This test checks if the modal for organization creation and the organization success flash works
Part of #759

Test for organization create modal & success flash

---

src/components/Cluster/ClusterDetail/AvailabilityZonesParser.js

Momentary fix for https://github.com/giantswarm/giantswarm/issues/8384 bug, introduced in https://github.com/giantswarm/happa/pull/944

Fix infinite loop in AvaliabilityZonesParser

---

__tests__/AppCatalog.js
src/actions/appActions.js
src/actions/appConfigActions.js
src/actions/appSecretActions.js
src/actions/catalogActions.js
src/actions/clusterActions.js
src/components/AppCatalog/AppDetail/AppDetail.js
src/components/AppCatalog/AppDetail/FileInput.js
src/components/AppCatalog/AppDetail/InstallAppForm.js
src/components/AppCatalog/AppDetail/InstallAppModal.js
src/components/AppCatalog/AppList/AppListInner.js
src/components/AppCatalog/AppList/AppListItems.js
src/components/UI/AppContainer.js
testUtils/browserMocks.js
testUtils/mockHttpCalls/appCatalogs.js
testUtils/mockHttpCalls/catalogIndex.js
testUtils/mockHttpCalls/index.js

This allows you to upload a YAML file for secrets during app creation. Much like the Config Map.

Allow setting secrets during app creation

---

__tests__/GettingStarted.js
src/components/GettingStarted/Steps/ConfigureKubectl.js
src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
src/components/GettingStarted/Steps/SimpleExample.js
testUtils/mockHttpCalls/clusters.js

Fixes
```
TypeError: Cannot read property 'withLoadingFlags' of undefined
at withLoadingFlags (webpack:///./src/actions/clusterActions.js:399:48)
at apply (webpack:///./node_modules/redux/es/redux.js:477:34)
at clusterLoadDetails (webpack:///./src/components/GettingStarted/Steps/ConfigureKubectl.js:30:7)
at componentDidMount (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:251:359)
at b (webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js:18:436)
at Lf (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:120:324)
at fg (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:244:436)
at Yj (webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js:223:419)
at c …
```

Fix arguments for clusterLoadDetails in Getting Started guide.

---

__tests__/Organization.js
src/components/Organizations/Detail/View.js

This ticks the last box (Removing a member from an org) in #759 under Organizations

add organization member removal test

---

src/components/Home/Home.js
src/styles/_base.sass

I saw the BETA tag on ginger.. I think it got reintroduced sometime after it was removed in #898

remove BETA tag from Home.js

---

__tests__/ClusterManagement.js
src/actions/clusterActions.js
src/utils/__tests__/computeCapabilities.js
src/utils/clusterUtils.js

Based on what we discussed yesterday, also added some tests. Perhaps over tested.

Refactor computeCapabilities and add hasOptionalIngress

---

src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js

To revert https://github.com/giantswarm/happa/pull/1019

Change Cancel button style to default

---

package.json
yarn.lock

btw @giantswarm/sig-front-end I've reduced the dep bump frequency to once a week, on mondays. But for now, just getting these out of the PR queue.

Update deps 2020-01-20

---

jsconfig.json

Enable VSCode tools for testUtils and integration tests

Add integration tests and testUtils paths to TS config

---

src/components/Home/ClusterDashboardResources.js

Fix flash in v4 cluster resources in list

---

src/components/GettingStarted/Steps/ConfigureKubectl.js
src/components/GettingStarted/Steps/SimpleExample.js

My intention was to fix those potential memory leaks that tests were revealing, and end up removing what I believe is useless code. 
We don't need to check for cluster details being loaded in this nested component, we do it in one of the parents.
Please correct me if I am wrong. Thanks!

Fix memory leaks and errors in tests console

---

src/components/Users/InviteUserModal/InviteUserSuccess.js

Fixes https://github.com/giantswarm/giantswarm/issues/8747

Fix invite modal logic

---

src/lib/helpers.js

Fixes https://github.com/giantswarm/giantswarm/issues/8680

Make generated kubeconfigs have custom values for each cluster

---

src/components/Auth/OAuthCallback.js

This pull request refactors the `OAuthCallback` class component into an function component.
The old component used `setState` in the constructor. State got never updated to it showed the spinner instead of showing an error to users.

[CHANGE] refactor OAuthCallback route into function component

---

.github/workflows/main.yml

Makes pull requests name require a prefix, in order to be able to automatically generate the changelog.
Prefixes can be:
* **[FEATURE]** - For a new feature
* **[CHANGE]** - For changes in existing functionality
* **[DEPRECATE]** - For soon-to-be removed features
* **[REMOVE]** - For removing features
* **[BUGFIX]** - For bug fixes
* **[SECURITY]** - For vulnerability fixes
Very much a work in progress, might need to make a couple of PRs to test it

[FEATURE] Add pull request title validation GitHub action

---

.github/release-template.yml

I believe this should fix the automatic release drafting

[CHANGE] Switch release template category labels type

---

src/components/Home/ClusterDashboardItem.js
src/components/UI/ErrorFallback.js

And so we can pass different errors at once.

Change ErrorFallback so that it accepts an array

---

__tests__/AdminLogin.js
src/components/Auth/OAuthCallback.js
testUtils/renderUtils.js

Towards https://github.com/giantswarm/happa/issues/759

Write integration test for the OAuth admin login user flow

---

src/actions/releaseActions.js

Towards https://github.com/giantswarm/giantswarm/issues/6862

Change error messages when releases fetching or data processing fails

---

__tests__/V5ClusterManagement.js
src/components/Cluster/ClusterDetail/NodesRunning.js
src/components/Home/ClusterDashboardResources.js
src/shared/constants/fallbackMessages.js
src/shared/constants/index.js

Reverts giantswarm/happa#1108 as cluster data doesn't include timezone, so date comparisons are not possible.

Revert "Fallback message when nodes are not ready yet"

---

src/components/Cluster/ClusterDetail/NodesRunning.js
src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
src/components/Home/ClusterDashboardResources.js
src/shared/constants/fallbackMessages.js
src/shared/constants/index.js
src/utils/clusterUtils.js

This is basically the same that I merged and then reverted last week -  https://github.com/giantswarm/happa/pull/1103 - except that in `clusterUtils.js` now we are using utc time.
Sorry for the back and forth.

Fallback message when nodes are not ready yet with UTC

---

.circleci/config.yml
Dockerfile
helm/happa-chart/templates/deployment.yaml
helm/happa-chart/templates/ingress.yaml
helm/happa-chart/values.yaml
nginx.conf
scripts/start.sh
webpack.common.js
webpack.prod.js

This pull request contains the following chages:
- Upgrade nginx image from 1.14 to 1.16
- gzip compress all static files in container build
- Adds some security headers to the ingress
- Some tweaks in the nginx configuration file
- Move all assets to the `assets` subdirectory in order to utilize caching directives present in nginx config

Update production build

---

src/components/AppCatalog/AppDetail/AppDetail.js

Fixes https://github.com/giantswarm/giantswarm/issues/9028

Fix app details infinite spinner

---

.babelrc
package.json
src/components/app.js
webpack.common.js
yarn.lock

This fixes a `cannot read property 'displayname' of null` error for me in development.
Did anyone else get this all the time too?

Fix 'cannot read property 'displayname' of null' error in dev.

---

src/components/Organizations/Detail/CredentialsForm.js

I spotted a missing word so I added it - now the sentence makes sense (unlike this one).

Added a missing word

---

__tests__/Users.js
__tests__/V4AzureClusterManagement.js
src/components/Users/InviteUserModal/InviteUserForm.js
testUtils/mockHttpCalls/index.js
testUtils/mockHttpCalls/invites.js
testUtils/mockHttpCalls/organizations.js
testUtils/mockHttpCalls/user.js

Towards https://github.com/giantswarm/happa/issues/759

Add integration tests for the Users page and modals

---

src/components/Cluster/NewCluster/CreateNodePoolsCluster.js

Fixes https://github.com/giantswarm/giantswarm/issues/7801#issuecomment-590897544

Cluster name input autofocus and autoselect

---

__tests__/AccountSettings.js
__tests__/AdminLogin.js
__tests__/AppCatalog.js
__tests__/ClusterManagement.js
__tests__/ForgotPassword.js
__tests__/GettingStarted.js
__tests__/Login.js
__tests__/Logout.js
__tests__/Organization.js
__tests__/SignUp.js
__tests__/Users.js
__tests__/V4AWSClusterManagement.js
__tests__/V4AzureClusterManagement.js
__tests__/V4KVMClusterManagement.js
__tests__/V5ClusterManagement.js
jest.config.js
src/components/AccountSettings/__tests__/ChangeEmailForm.js
src/components/AccountSettings/__tests__/ChangePasswordForm.js
src/components/Cluster/ClusterDetail/ClusterApps.js
src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
src/components/SignUp/SignUp.js
testUtils/setupTests.js

Hopefully this will fix all the weird test behaviour
* Moved all the common test behaviour that we would normally just copy and paste around to a global config
* You can now enable seeing which pending requests hang in which tests by uncommenting some lines in the global test config

Clean up automated tests

---

src/model/clients/GiantSwarmClient.js

Only accept json as response in GS client

---

src/components/Cluster/ClusterDetail/ClusterApps.js

Something @Oshratn noticed and preferred removed at the onsite.

Remove an exclamation mark.

---

.github/workflows/main.yml

Just to make our lives easier. This automatically asigns the author of a PR as an `Assignee`

Add action for automatic-assigning of authors

---

src/components/Home/ClusterDashboardResources.js

Fixes https://github.com/giantswarm/giantswarm/issues/9376
Not sure about that, but I believe the problem has to be caused by the modified line because it is in Happa's home.

Check cluster existence in dashboard resouces component

---

src/selectors/clusterSelectors.js

A second attempt to fix this: giantswarm/giantswarm#9376

Return empty array if no cluster in selectClusterNodePools

---

src/actions/clusterActions.js
src/actions/nodePoolActions.js
src/components/Home/Home.js
src/components/UI/ErrorFallback.js

Fixes an exception raised in our channel
https://gigantic.slack.com/archives/C3MCF5EJK/p1584687346000100
Addressess the case that the error is not an array (it usually is an error object or a server response)

Address objects inside of the error fallback helper

---

helm/happa-chart/templates/ingress.yaml

Remove AWS condition from the whitelisting Ingress annotation

Remove AWS condition from the whitelisting Ingress annotation

---

src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js

This puts the button in the loading state after pressing submit.

(version picker) Show the button loading when the request is in flight.

---

.circleci/config.yml
Makefile
package.json
src/components/App.tsx

This is an extra step, to make sure that our TypeScript code has no issues.

Run typechecking before committing and as a CI step

---

webpack.common.js

Fixes this error during development

Avoid polyfilling fs

---

__tests__/AppDetailPane.js
src/actions/appActions.js

Fixes https://github.com/giantswarm/giantswarm/issues/8818

Add explicit app deletion message

---

src/shared/constants/index.js

Follow-up to https://github.com/giantswarm/happa/pull/1292

Improve wording/grammar

---

src/actions/clusterActions.js
src/actions/nodePoolActions.js

Fix for [this error](https://gigantic.slack.com/archives/C3MCF5EJK/p1586335138000100).

Check if error.response object exist in catch blocks

---

src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
src/shared/constants/index.js

This adds more column header tooltips to the node pools table.

Add more tooltips to node pools list

---

__tests__/KeyPairs.js
src/components/Cluster/ClusterDetail/ExpiryHoursPicker.js
src/components/Cluster/ClusterDetail/KeyPairCreateModal.js
src/shared/constants/index.js
src/styles/components/_expiry_hours_picker.sass

Closes https://github.com/giantswarm/giantswarm/issues/10038
Also fixes a bug that would make the keypair creation form keep the values between opens.
**No warning**
**Warning**

Display warning if keypair TTL > 30 days

---

src/components/Cluster/ClusterDetail/URIBlock.js
src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js

Fixes giantswarm/giantswarm#10119
**Same scenario as in the issue**
**Even smaller screens**
* URI bar is scrollable horizontally by sliding with the finger

Fix get started button positioning on small screens for v4 clusters

---

src/components/GettingStarted/Steps/SimpleExample.js

I noticed the prompt output didn't totally match how the latest kubectl and helloworld repo shows things.

Update prompt output for the simple example.

---

src/components/UI/ComponentChangelog.js

closes: https://github.com/giantswarm/giantswarm/issues/10100

Open changelog links in new tab

---

__tests__/AppCatalog.js
__tests__/AppDetailPane.js
__tests__/ClusterManagement.js
__tests__/KeyPairs.js
__tests__/V4AWSClusterManagement.js
__tests__/V4AzureClusterManagement.js
__tests__/V4KVMClusterManagement.js
__tests__/V5ClusterManagement.js
package.json
src/actions/batchedActions.js
src/components/AppCatalog/AppDetail/InstallAppModal.js
src/components/Cluster/Cluster.js
src/components/Cluster/ClusterDetail/ClusterDetail.js
src/components/Cluster/ClusterDetail/ClusterDetailView.js
src/components/Home/ClusterDashboardItem.js
src/components/Organizations/Detail/View.js
src/components/UI/AppDetails/AppDetails.js
src/components/shared/Tabs.js
src/components/shared/Tabs.tsx
src/components/shared/__tests__/Tabs.js
src/components/shared/__tests__/Tabs.tsx
src/shared/constants/routes.js
testUtils/renderUtils.js
yarn.lock

Closes https://github.com/giantswarm/giantswarm/issues/9942
* Refactored the `Tabs` component to support routing
* The user is now redirected to the `Apps` tab in cluster details after installing an app.

Stay on app page after installing app

---

.circleci/config.yml
src/components/Cluster/ClusterDetail/Ingress/Components.tsx
src/components/Cluster/ClusterDetail/UserInstalledApps/InstalledApp.js
src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
src/components/Home/ClusterDashboardItem.js
src/components/UI/ReleaseComponentLabel.js
src/components/UI/ValueLabel.tsx
src/styles/index.ts
src/styles/theme.ts

This PR tries to apply some improvements made in #1359 early into master.
It introduces a new theme color called `foreground` which is then used throughout the application.
It also increases the resouce class for test and build ci steps

introduce & use foreground color to theme

---

src/components/Users/InviteUserModal/InviteUserSuccess.js

Forgot to push these in https://github.com/giantswarm/happa/pull/1452 😅 
Without these changes, the code block doesn't actually look like in the screenshots

Add forgotten InviteUser modal style changes

---

yarn.lock

Updates giantswarm-js-client to newest version
The changes are mostly due to cluster labeling, spot instances & some minor things (https://github.com/giantswarm/giantswarm-js-client/compare/b2ce0a1fd0de4bbb13a4042dca6e868df65b7ad6...fbc4838ae77f65ca9edd00884392e3c583ef6e04)

update giantswarm-js-client for cluster labeling & other recent changes

---

SECURITY.md

Towards giantswarm/giantswarm#10313
Adds a security policy to send concerned users to official channels.

Add link to security policy

---

.circleci/config.yml
helm/happa/Chart.yaml
helm/happa/ci/default-values.yaml
helm/happa/templates/deployment.yaml
helm/happa/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/10177

Move Happa to app collection deployment method

---

src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
src/shared/FeatureFlags.ts
webpack.common.js

Enable cluster labelling for production builds & do some last minute changes for firefox

Enable cluster labelling through feature flag

---

src/styles/components/_button.sass

Part of https://github.com/giantswarm/happa/pull/1486

Make the success button the same size as the regular button

---

jest.config.js
src/shared/constants/index.js
src/utils/__tests__/computeCapabilities.js
src/utils/clusterUtils.js
testUtils/mockHttpCalls/clusters.js

Part of https://github.com/giantswarm/happa/pull/1486/

Add boilerplate for the HA masters feature

---

src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
src/components/Cluster/NewCluster/CreateRegularCluster.js
src/components/Cluster/NewCluster/MasterNodes.tsx
src/components/Cluster/NewCluster/NewCluster.js
src/components/Cluster/NewCluster/__tests__/MasterNodes.ts

Add HA Masters cluster creation components

---

src/components/ExceptionNotificationTest/ExceptionNotificationTest.tsx
src/components/Layout.js
src/shared/constants/routes.js

To test the exception notification feature.

Add a page that lets us generate uncaught exceptions.

---

__tests__/V5ClusterManagement.js
src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx

Towards https://github.com/giantswarm/giantswarm/issues/11424
Here is a screenshot of how it'll look after merging this PR:

Move add labels button out of the info text

---

webpack.common.js

Fix feature flag loading from environment

---

webpack.common.js

We forgot to handle regular booleans 😬

Fix feature flags, part 2

---

src/components/Cluster/ClusterDetail/AvailabilityZonesWrapper.js
src/components/Cluster/ClusterDetail/NodePool.tsx
src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
src/selectors/clusterSelectors.js

Towards https://github.com/giantswarm/giantswarm/issues/11475
This also simplifies the logic for displaying availability zones

Center node pools availability zones

---

__tests__/AdminLogin.js
__tests__/Login.js
src/actions/appActions.js
src/actions/batchedActions.js
src/actions/catalogActions.js
src/actions/clusterActions.js
src/actions/invitationActions.js
src/actions/nodePoolActions.js
src/actions/organizationActions.js
src/actions/userActions.js
src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
src/lib/pageVisibilityTracker.js

Towards https://github.com/giantswarm/giantswarm/issues/11388

Remove all console.error calls

---

scripts/webpack/getServiceURL.js

Update the changed opsctl command name

Update opsctl command

---

src/components/AppCatalog/CatalogList/CatalogRepo.js
src/components/shared/ImgWithFallback.tsx

- Uses the url for color generation
- Does not set the generated color when image is available

Catalog Icon fixes

---

.circleci/config.yml

This is required for pushing to CP catalog 😅

Update architect to 0.10.0

---

package.json
yarn.lock

closes: https://github.com/giantswarm/happa/pull/1415

Force a updated lodash

---

src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
src/components/UI/Truncated.tsx
src/components/UI/__tests__/Truncated.ts

Reported by @marian here: https://gigantic.slack.com/archives/CQ465CFG8/p1596037745003500

Remove some superfluous tooltips.

---

.circleci/config.yml
README.md
helm/happa/ci/default-values.yaml
helm/happa/templates/configmap.yaml
helm/happa/templates/deployment.yaml
jest.config.js
scripts/start.sh
scripts/webpack/proxyPlugin.js
src/@types/global.d.ts
src/index.html
src/shared/FeatureFlags.ts
webpack.common.js
webpack.dev.js

Part of the larger https://github.com/giantswarm/happa/pull/1547
Includes environment configuration, such as env variables, deployment configuration, local proxy settings etc.

[CP Auth 1/5]: Add environment configuration

---

src/components/GettingStarted/Steps/SimpleExample.js

Closes https://github.com/giantswarm/giantswarm/issues/12441
See issue for before image
How it looks now

Update Getting Started code example to mention kubectl label selector

---

__tests__/V5ClusterManagement.js
src/actions/clusterActions.js
src/actions/userActions.js
src/components/Auth/Login.tsx
src/components/Cluster/ClusterDetail/NodesRunning.js
src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
src/components/Cluster/NewCluster/CreateRegularCluster.js
src/utils/clusterUtils.js

Some of the older TODOs can be easily fixed, or even removed, since some of them have been already fixed.

Fix or remove already fixed TODOs in code

---

Dockerfile
scripts/start.sh

This PR adds a compress stage and updates the nginx image for container builds

split container build & update nginx image version

---

package.json

Towards https://github.com/advisories/GHSA-6x33-pw7p-hmpq

Force http-proxy to version >=1.18.1

---

src/components/Cluster/ClusterDetail/UserInstalledApps/UserInstalledApps.js

Before:
New text:
Browse the App Catalogs to find any apps to install.

Improve wording regarding installing apps

---

docs/Release.md

Link to the intranet guide for creating a release

De-duplicate release information

---

.github/workflows/release-notes.yml

Use the correct release format in the 'release-drafter' latest version

---

src/components/Cluster/ClusterDetail/NodesRunning.tsx
src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js

Small conversion of `NodesRunning` component into TypeScript

refactor ClusterDetail/NodesRunning into typescript

---

src/components/UI/DropdownMenu.js
src/components/UI/Navigation/OrganizationDropdown.js
src/components/UI/Truncated.tsx

Fixes giantswarm/giantswarm#13502
This PR:
- restricts the maximum length of the organization dropdown trigger
- allows maximum length of the organization dropdown menu
<details>
<summary>Screenshots</summary>
</details>

change dropdown trigger & menu width

---

src/components/Home/ClusterDashboardItem.js
src/shared/constants/index.ts

Display node pools loading errors on a new line

---

scripts/start.sh

Missed this change while working on previous PR

Do not check for non-related capabilities in start script

---

src/stores/main/__tests__/selectors.ts
src/stores/main/selectors.ts

As seen on https://gigantic.slack.com/archives/C03CPNRTS/p1601930766351800

Don't let user execute requests if they are not logged in

---

src/components/index.tsx

Towards https://github.com/giantswarm/giantswarm/issues/13497
This also adds a custom user action for the page load event, so that we record the screen and window size for every session.

Record window and screen size on page load

---

package.json
src/@types/realUserMonitoring.d.ts
src/@types/web-vitals.d.ts
src/components/index.tsx
src/shared/constants/realUserMonitoring.ts
yarn.lock

This PR explores recording of [core web vitals](https://web.dev/vitals/#core-web-vitals) with the help of the [web-vitals](https://github.com/GoogleChrome/web-vitals) library.
They are three important performance indicators for the UX of web applications.
- **Largest Contentful Paint (LCP)**: measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.
- **First Input Delay (FID)**: measures interactivity. To provide a good user experience, pages should have a FID of less than 100 milliseconds.
- **Cumulative Layout Shift (CLS)**: measures visual stability. To provide a good user experience, pages should maintain a CLS of less than 0.1.
- Most metrics are only available in Chrome/Chromium based browsers. See …

Record core web vitals

---

src/components/AppCatalog/AppDetail/AppDetail.js
src/components/UI/AppDetails/AppDetails.js
src/shared/constants/index.ts
src/stores/appcatalog/actions.ts
src/stores/appcatalog/selectors.ts

towards: https://github.com/giantswarm/giantswarm/issues/13624
This adds a link renderer and some logic to generate a valid base URL for relative links in our App README's.

Fix relative URLs in READMEs

---

__tests__/Users.js
src/components/Users/InvitesTable.js
src/components/Users/Users.js
src/components/Users/UsersTable.js
src/components/Users/UsersUtils.js
testUtils/mockHttpCalls/invites.js
testUtils/mockHttpCalls/user.js

This PR separates user invites from user accounts to solve some usability problems.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Clarify invites and expiry dates on users page

---

src/components/AppCatalog/AppList/AppListSearch.js

Fixes: https://github.com/giantswarm/giantswarm/issues/13844

Don't reload the page when pressing enter in the app search form.

---

src/components/UI/AppContainer.js

Fixes: https://github.com/giantswarm/giantswarm/issues/13839

Fix app names that disappear on hover

---

src/components/UI/AppDetails/AppDetails.js

Closes https://github.com/giantswarm/giantswarm/issues/13820
https://user-images.githubusercontent.com/273727/96248163-6e57bc80-0fab-11eb-8c2e-8f94530b15c4.png

In app details, don't show PROVIDES label if appVersion is not given

---

jest.config.js
package.json
scripts/start.sh
src/components/index.tsx
src/index.html
src/shared/constants/realUserMonitoring.ts
yarn.lock

Towards https://github.com/giantswarm/giantswarm/issues/12047
Uses https://github.com/giantswarm/api/pull/1164
Also adds `bowser` to collect basic client/browser information.
Suggestions on how to tweak are highly welcome.

Write RUM data to custom analytics endpoint

---

src/stores/batchActions.ts

Closes https://github.com/giantswarm/giantswarm/issues/14226
With this PR:
* When creating a cluster with node pools at the same time, and node pool creation fails, you are redirected to the cluster detail page (because that was created successfully), and a flash message with the node pool creation error from the API is shown to you.

Display that NP creation failed when trying to create a cluster and NPs at the same time

---

src/lib/Version.ts
src/lib/__tests__/Version.ts

Towards https://github.com/giantswarm/giantswarm/issues/14345
This will come in use while dealing with different types of pre-release versions.

Create utility class for parsing semver-formatted versions

---

src/components/Organizations/Detail/Detail.js
src/components/Organizations/Detail/View.js
src/components/Organizations/Detail/__tests__/View.tsx

Closes https://github.com/giantswarm/giantswarm/issues/14685
Pretty straightforward fix, just a missing prop...

Fix organization credential form not appearing

---

src/components/Organizations/Detail/Detail.js
src/components/Organizations/Detail/View.js
src/components/Organizations/Detail/__tests__/View.tsx
src/components/Organizations/List/List.js
src/components/UI/OrganizationList/OrganizationList.js
src/components/UI/OrganizationList/OrganizationListRow.js
src/stores/organization/utils.ts

Closes https://github.com/giantswarm/giantswarm/issues/14985
Also renames an internal variable accordingly

Align terminology by replacing term "BYOC credentials" to "provider credentials"

---

src/components/UI/AppDetails/AppDetailsItem.js

Towards: https://github.com/giantswarm/roadmap/issues/250

Open app detail links in a new tab

---

README.md
__tests__/Organization.js
src/components/Cluster/ClusterDetail/ScaleClusterModal.js
src/components/Organizations/Detail/CredentialsDisplay.js
src/components/Organizations/Detail/CredentialsForm.js
src/components/UI/CatalogTypeLabel.js

Towards https://github.com/giantswarm/giantswarm/issues/14961

Rename tenant cluster to workload cluster and control plane to management cluster

---

src/components/Cluster/ClusterDetail/NodePoolScaling.tsx

Fix wrong NP nodes display on Azure

---

src/components/Cluster/ClusterDetail/NodePoolScaling.tsx

Fixes https://github.com/giantswarm/giantswarm/issues/15187
Really don't know what I had in mind when I wrote this

Show correct node pool size on Azure autoscaling clusters

---

src/components/Apps/Apps.tsx
src/components/Apps/AppsList/AppsList.tsx
src/components/UI/AppList/App.tsx
src/components/UI/AppList/Icon.tsx
src/components/shared/ImgWithFallback.tsx
yarn.lock

This PR is focused mainly on the styling for the app component, and the fallback outlined letter icon style.
Towards: https://github.com/giantswarm/giantswarm/issues/13652

Add new app component and app listing area

---

src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstances.tsx
src/components/Cluster/ClusterDetail/NodePool.tsx
src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
src/components/Cluster/ClusterDetail/NodePoolScalingSpotInstancesDetails.tsx

Towards https://github.com/giantswarm/giantswarm/issues/13435
Moving stuff around to allow easier customization for Azure NP Spot instances.

Refactor spot instances stuff to allow provider-specific customization

---

src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairSuccessTemplate.tsx
src/components/Cluster/ClusterDetail/KeypairCreateModal/DownloadKubeconfigButton.tsx
src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
src/components/Cluster/NewCluster/CreateRegularCluster.js
src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
src/components/Organizations/Detail/CredentialsDisplay.js
src/components/Organizations/Detail/View.js
src/components/Organizations/List/List.js
src/components/UI/Controls/Button.js
src/components/Users/UsersTable.js

The underlying bootstrap button actually doesn't permit 'outline' as a value for the bsStyle prop.

Replace 'outline' with 'default'

---

package.json
yarn.lock

There's a bug which prevents us from starting the local dev server in v4.4.0

Upgrade webpack-cli to latest version

---

__tests__/Apps.js
src/components/Apps/AppDetail/AppDetail.tsx
src/components/UI/Controls/Navigation/Navigation.js

Fixes: https://github.com/giantswarm/happa/issues/2199

Fix app breadcrumbs

---

helm/happa/templates/configmap.yaml

Fix a problem that would prevent the app from being deployed

---

src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.stories.tsx

Fixes https://github.com/giantswarm/giantswarm/issues/16186

Fix read me app story

---

.circleci/config.yml
src/components/Layout.js
src/components/MAPI/organizations/OrganizationIndex.tsx
src/components/MAPI/organizations/OrganizationList.tsx
src/components/UI/Display/Organizations/OrganizationListPage.tsx
src/components/UI/Display/Organizations/stories/OrganizationListPage.stories.tsx
src/components/UI/Display/Organizations/stories/Simple.tsx
src/lib/__tests__/organizationValidation.ts
src/lib/organizationValidation.ts
src/styles/theme.ts

This PR implements the UI behaviour specced for creating and listing organisations. https://github.com/giantswarm/giantswarm/issues/16300
There is a story at `Display/Organizations/OrganizationListPage` so you can check out the behaviour if you'd like.

Add new organization listing and creating ui elements

---

src/components/Auth/MAPI/MapiUnauthorized.tsx

Add a logout link to the insufficient permissions screen

---

src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetailLoadingPlaceholder.tsx
src/components/UI/Display/MAPI/AccessControl/AccessControlRolePermissions.tsx
src/components/UI/Display/MAPI/AccessControl/AccessControlRoleType.tsx
src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx
src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleDetail.tsx
src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRolePermissions.tsx

Towards giantswarm/giantswarm#16306
This PR adds all the other components required for rendering the Role Detail View.

access control: add other components required for rendering the role detail view

---

src/components/Modals/Modals.js

This change accompanies https://github.com/giantswarm/api/pull/1254 on the client side.

Update the validation regex for organization names

---

src/components/MAPI/organizations/AccessControl/index.tsx
src/components/MAPI/organizations/AccessControl/utils.ts
src/components/UI/Display/MAPI/AccessControl/AccessControlDescription.tsx
src/components/UI/Display/MAPI/AccessControl/AccessControlRoleType.tsx

Towards giantswarm/giantswarm#16306
This PR adds the extra components required to render Access Control. This is still missing a bigger integration test with all the request/parsing/etc. logic. I have a plan for that, don't worry 😜

access control: add other components required to render the whole thing

---

src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.stories.tsx

This PR adds some required props to components in a storybook story, to mitigate some warnings.

Add props to mitigate warnings in storybook

---

src/components/Cluster/ClusterDetail/UserInstalledApps/InstalledApp.tsx
src/components/Cluster/ClusterDetail/UserInstalledApps/__tests__/InstalledApp.tsx
src/components/Cluster/ClusterDetail/UserInstalledApps/stories/InstalledApp.stories.tsx

Add InstalledApp to storybook, convert to TS

---

src/stores/main/utils.ts

Rename admin group

---

.circleci/config.yml
helm/happa/ci/default-values.yaml
helm/happa/templates/configmap.yaml
helm/happa/templates/deployment.yaml
scripts/start.sh
src/@types/global.d.ts
src/index.ejs
src/stores/main/utils.ts

My last PR had auto-merge on and I missed this

authentication: get admin group from configmap

---

Dockerfile

From 1.18-alpine to 1.19-alpine

Update nginx to 1.19-alpine

---

helm/fe-docs/templates/ingress.yaml
helm/happa/templates/happaapi-ingress.yaml
helm/happa/templates/ingress.yaml

Towards https://github.com/giantswarm/giantswarm/issues/17206

Update Ingress to use networking.k8s.io/v1 or v1beta1

---

src/components/Auth/MAPI/MapiAuthProvider.tsx
src/lib/OAuth2/OAuth2.ts
src/lib/OAuth2/TestOAuth2.ts
src/stores/main/actions.ts
src/stores/main/middleware.ts

Closes https://github.com/giantswarm/giantswarm/issues/16830
This PR fixes a memory leak when renewing the auth token fails. It now also displays a flash message when that happens.

auth: fix memory leak when renewing the auth token fails

---

src/components/Apps/AppDetail/AppDetail.tsx
src/components/Cluster/ClusterDetail/ClusterDetailView.js
src/components/GettingStarted/Steps/InstallIngress.js

As seen on https://gigantic.slack.com/archives/C13MG9F0W/p1621521645007200

apps: disable app features via MAPI on KVM installations

---

src/stores/user/actions.ts

Towards https://github.com/giantswarm/giantswarm/issues/17359

Fix uncaught error when fetching user invitations fails

---

src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx
src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
src/components/MAPI/organizations/AccessControl/index.tsx
src/components/MAPI/organizations/AccessControl/utils.ts
src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx
src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleDetail.tsx
src/components/UI/Display/MAPI/AccessControl/types.ts
testUtils/mockHttpCalls/rbacv1/roleBindings.ts

Closes https://github.com/giantswarm/giantswarm/issues/17407
This PR also takes the preliminary steps towards making access control aware of permissions.

access control: disable adding/deleting groups and users

---

src/components/GettingStarted/Steps/InstallIngress.js

The beauty of JS
As seen on https://sentry.io/organizations/giantswarm/issues/2423987080/?project=5739870

Actually import 'supportsMapiApps' before using it

---

__tests__/V5ClusterManagement.js
src/components/Cluster/ClusterDetail/MasterNodes/MasterNodes.tsx
src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesConverter.tsx
src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesUtils.ts
src/components/Cluster/ClusterDetail/MasterNodes/__tests__/MasterNodes.ts
src/components/Cluster/ClusterDetail/MasterNodes/__tests__/MasterNodesUtils.ts
src/components/Cluster/NewCluster/MasterNodes.tsx
src/components/Cluster/NewCluster/__tests__/MasterNodes.ts
src/stores/cluster/__tests__/utils.ts

Terminology change towards https://github.com/giantswarm/giantswarm/issues/14964

Rename master node to control plane node

---

src/stores/batchActions.ts

This PR disables all the GS API cluster (and everything else related - node pools, releases) if the MAPI cluster management feature flag is turned on.
With this change and the feature flag enabled, we only execute GS API requests for:
- `/v4/info/` - when the app loads initially
- `/v5/users/` - on the `Users` page
- `/v5/analytics/` - when reporting analytics
Bonus points: This makes the app load super quickly (compared to before)

clusters: don't execute cluster-specific GS API requests if MAPI cluster FF is turned on

---

src/components/MAPI/clusters/CreateCluster/CreateClusterDescription.tsx
src/components/MAPI/workernodes/WorkerNodesCreateNodePoolDescription.tsx
src/lib/__tests__/helpers.ts
src/lib/helpers.tsx

Closes [giantswarm/giantswarm#18137](https://github.com/giantswarm/giantswarm/issues/18137).

Fix MAPI cluster and node pool description validation messages

---

src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.tsx
src/components/MAPI/apps/AppDetailsModal/__tests__/index.tsx
src/components/MAPI/apps/AppDetailsModal/index.tsx
src/components/MAPI/apps/AppInstallModal.tsx
src/components/MAPI/apps/ClusterDetailApps.tsx
src/components/MAPI/apps/__tests__/AppInstallModal.tsx
src/components/MAPI/apps/__tests__/ClusterDetailApps.tsx
testUtils/mockHttpCalls/applicationv1alpha1/appcatalogentries.ts
testUtils/mockHttpCalls/applicationv1alpha1/index.ts

Towards https://github.com/giantswarm/giantswarm/issues/18136
Nothing too crazy, just to create a base of happy path tests, so we can refactor easier.

apps: write tests for cluster app management

---

src/components/MAPI/apps/AppList/__tests__/AppDetail.tsx
src/components/MAPI/apps/AppList/__tests__/index.tsx
src/components/MAPI/apps/AppList/utils.tsx
src/components/UI/Display/Apps/AppList/App.tsx
src/components/UI/Display/Apps/AppList/Toolbar.tsx
testUtils/mockHttpCalls/applicationv1alpha1/appcatalogindexes.ts
testUtils/mockHttpCalls/applicationv1alpha1/appcatalogs.ts
testUtils/mockHttpCalls/applicationv1alpha1/index.ts

Again, nothing too crazy. Happy paths.

Add tests for displaying data on the Apps page

---

src/components/MAPI/guides/LoginGuideStep.tsx
src/components/MAPI/organizations/AccessControl/guides/BindRolesToSubjectsGuide.tsx
src/components/MAPI/organizations/AccessControl/guides/InspectRoleGuide.tsx
src/components/MAPI/organizations/AccessControl/guides/ListRolesGuide.tsx
src/components/MAPI/organizations/AccessControl/index.tsx
src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
src/components/MAPI/organizations/OrganizationList.tsx
src/components/MAPI/organizations/guides/CreateOrganizationGuide.tsx
src/components/MAPI/organizations/guides/GetOrganizationDetailsGuide.tsx
src/components/MAPI/organizations/guides/ListOrganizationsGuide.tsx
src/components/MAPI/utils.ts
src/components/UI/Display/Documentation/CodeBlock.js
src/components/UI/Display/Documentation/Styles.js
src/components/UI/Display/Documentation/__tests__/CodeBlock.js
src/components/UI/Display/MAPI/CLIGuide/CLIGuideAdditionalInfo.tsx
src/components/UI/Display/MAPI/CLIGuide/CLIGuideStep.tsx
src/components/UI/Display/MAPI/CLIGuide/CLIGuideStepList.tsx
src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
src/components/UI/Display/MAPI/CLIGuide/index.tsx
src/components/UI/Display/MAPI/CLIGuide/stories/AdditionalInfo.tsx
src/components/UI/Display/MAPI/CLIGuide/stories/Simple.tsx
src/lib/docs.ts
src/styles/theme.ts

Closes https://github.com/giantswarm/giantswarm/issues/16564
This PR adds CLI guides for Management API, organization-specific operations. Guides are customized for the installation and for the selected organization (where applicable).
<details>
<summary>Just chilling</summary>
</details>
<details>
<summary>One of the guides</summary>
</details>

Add guides for using the CLI for fetching the data displayed in the UI

---

__tests__/ForgotPassword.js
__tests__/Login.tsx
src/components/Auth/Login.tsx

Disable username and password login when SSO feature flag is enabled

---

src/components/UI/Display/Apps/AppDetails/AppDetails.js
src/components/UI/Display/Tabs/stories/Tabs.stories.mdx

Remove leftover bootstrap tabs

---

Dockerfile
Dockerfile.fe-docs

Update base Docker images

---

helm/happa/Chart.yaml

Off course I forgot to revert the WIP branch name...

Fix config version in chart

---

.circleci/config.yml

Closes https://github.com/giantswarm/giantswarm/issues/18755

Push happa to docker.io

---

src/components/MAPI/guides/utils.ts
src/components/MAPI/organizations/guides/CreateOrganizationGuide.tsx

Depends on https://github.com/giantswarm/kubectl-gs/pull/470
Before
After

Use the new 'template organization' command in kubectl-gs in the CLI guide for creating an organization

---

src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
src/components/MAPI/workernodes/utils.ts

Towards https://github.com/giantswarm/roadmap/issues/388
Nothing special, it works by updating the `AWSMachineDeployment` resource.

node pools: add support for changing descriptions on AWS via MAPI

---

src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
src/components/MAPI/workernodes/guides/ModifyNodePoolGuide.tsx

Towards https://github.com/giantswarm/roadmap/issues/388

node pools: adapt NP modifying guide to work for AWS

---

renovate.json

Remove reviewers from happa dependency PRs

---

src/components/Layout.js
src/lib/OAuth2/OAuth2.ts
src/stores/batchActions.ts

As seen on
https://sentry.io/organizations/giantswarm/issues/2768544887/?project=5739870
https://sentry.io/organizations/giantswarm/issues/2752925680/?project=5739870

Prevent trying to use user information if the user gets logged out

---

src/components/ForgotPassword/SetPassword.js

As seen on https://gigantic.slack.com/archives/C02EVLE9W/p1637756165387300

Make the password reset form work properly

---

src/components/MAPI/apps/utils.ts

Closes https://github.com/giantswarm/roadmap/issues/680.
This PR fixes a bug in the cluster details overview page > apps widget, where the number of upgradable apps displayed was incorrect. This is similar to the issue described in https://github.com/giantswarm/roadmap/issues/647. Some error handling was also added to prevent `n/a` values from being incorrectly displayed when some of the requests for determining the number of upgradable apps fail due to insufficient permissions.

Fix upgradable apps count in cluster details overview > apps widget

---

src/components/SignUp/SignUp.tsx

Closes https://github.com/giantswarm/giantswarm/issues/20427

Avoid reporting invalid invite token errors to Sentry

---

src/components/MAPI/apps/ClusterDetailApps.tsx

Closes https://github.com/giantswarm/giantswarm/issues/20530.

Fix accessing method on undefined value

---

src/components/Cluster/ClusterDetail/Ingress/Instructions.tsx
src/components/Cluster/ClusterDetail/Ingress/__tests__/Ingress.ts
src/components/MAPI/clusters/guides/InspectClusterReleaseGuide.tsx
src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedGetAccess.tsx

I went over CLI guides, Getting Started, and the Ingress tab in order to align placeholders. I ended up changing a bit more than that. I hope that the diff makes it clear enough.

Update placeholders and more

---

helm/happa/templates/configmap.yaml
helm/happa/values.yaml

This PR allows to set the default request timeout via installation config.

Make default request timeout configurable

---

helm/happa/templates/configmap.yaml

The goal of this PR is to have slightly better overview in the happa ConfigMap, grouping related things together.

Sort ConfigMap options

---

helm/fe-docs/templates/deployment.yaml

Towards https://github.com/giantswarm/giantswarm/issues/22623

Reduce resource requests and limits for fe-docs.giantswarm.io

---

src/components/MAPI/apps/utils.ts

This PR adds support for displaying app installation status for app resources in organization namespaces. This was previously implemented for app resources in workload cluster namespaces.
Users viewing the UI on GCP installations should now see app installation status displayed correctly.
Closes https://github.com/giantswarm/roadmap/issues/1434.

Support displaying app installation status for app resources in organization namespaces

---

helm/happa/templates/happaapi-ingress.yaml
helm/happa/templates/ingress.yaml
helm/happa/values.yaml

allow configure custom clusterIssuer for happa certs

add-custom-cluster-issuer

---

src/components/MAPI/clusters/CreateCluster/ClusterNameWidget.tsx
src/components/UI/JSONSchemaForm/ArrayFieldTemplate/index.tsx
src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx
src/components/UI/JSONSchemaForm/CheckboxWidget/index.tsx
src/components/UI/JSONSchemaForm/FieldTemplate/index.tsx
src/components/UI/JSONSchemaForm/ObjectFieldTemplate/index.tsx
src/components/UI/JSONSchemaForm/SelectWidget/index.tsx
src/components/UI/JSONSchemaForm/ToggleWidget/index.tsx

Descriptions were added for the `cluster app` form fields.

Add form fields descriptions

---

LICENSE

Small bump in the license text

Update date in license

---

README.md

Remove hiring banner from README
None
https://github.com/giantswarm/giantswarm/issues/19183#issuecomment-1400394738

Remove hiring banner

---

src/components/MAPI/clusters/CreateCluster/CreateClusterAppBundles.tsx
src/components/MAPI/clusters/CreateCluster/schemaUtils.ts
src/components/UI/JSONSchemaForm/AccordionFormField/index.tsx
src/components/UI/JSONSchemaForm/ArrayFieldItem/index.tsx
src/components/UI/JSONSchemaForm/ArrayFieldItemActions/index.tsx
src/components/UI/JSONSchemaForm/ArrayFieldTemplate/index.tsx
src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx
src/components/UI/JSONSchemaForm/FieldTemplate/index.tsx
src/components/UI/JSONSchemaForm/ObjectFieldTemplate/index.tsx
src/components/UI/JSONSchemaForm/ObjectFormField/index.tsx
src/components/UI/JSONSchemaForm/test.schema.json

Visual improvements for hierarchical object and array fields according to the [design specs](https://www.figma.com/file/DsMPSXboZwWQjEryN5Y8wv/Happa-generated-hierarchical-form?node-id=0%3A1&t=RSAys5SdSeNqhUUC-0).

Add JSON schema form visual improvements

---

src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterName.tsx
src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolListPlaceholder.tsx

Fix cluster details UI bugs as reported in https://github.com/giantswarm/roadmap/issues/2372 and https://github.com/giantswarm/roadmap/issues/2378.

Fix cluster details UI bugs

---

src/components/MAPI/clusters/CreateClusterAppBundles/index.tsx

This PR adds a selector to allow selecting the version of the cluster app used for cluster creation via app bundles.
Hovering on the info icon displays more information regarding cluster app versions.
The `GitHub` link leads to the releases page of the relevant cluster app for the provider.
Towards https://github.com/giantswarm/roadmap/issues/2431.

Allow selecting cluster app version for cluster creation

---

helm/fe-docs/values.yaml
helm/happa/values.yaml

Towards
- https://github.com/giantswarm/roadmap/issues/3017

Set default registry domain to gsoci

---

helm/fe-docs/templates/_helpers.tpl
helm/happa/templates/_helpers.tpl

Towards https://github.com/giantswarm/giantswarm/issues/30245

Fix app labels

---

src/index.ejs

Towards https://github.com/giantswarm/giantswarm/issues/31814

Add TelemetryDeck script

---

src/model/constants/docs.ts

Fixes https://github.com/giantswarm/roadmap/issues/3714

Update docs URLs
